<?php
$framecolor= Mage::app()->getStore()->getConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkopcbgcolor');
if($framecolor == ''){  $framebgcolor='#337BAA'; }else{ $framebgcolor = $framecolor; }
$framebrdcolor= Mage::app()->getStore()->getConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkopcbordercolor');
if($framebrdcolor == ''){  $framebordercolor='#CCCCCC'; }else{ $framebordercolor = $framebrdcolor; }
$frametxtcolor= Mage::app()->getStore()->getConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgktxtcolor');
if($frametxtcolor == ''){  $frametitlecolor='#FFFFFF'; }else{ $frametitlecolor = $frametxtcolor; }
?>
<style>
div.mgkosc-frametitle {background-color: <?php echo $framebgcolor ?>;color:<?php echo $frametitlecolor ?>}
div.mgkosc-framecontent{border:1px solid <?php echo $framebordercolor ?>;}
div.mgkosc-framecontentinfo{border:1px solid <?php echo $framebordercolor ?>;}
.mgkosc-logininfo { background-color:<?php echo $framebgcolor ?>;}
.mgkosc-agreeinfo{ background-color:<?php echo $framebgcolor ?>; color:<?php echo $frametitlecolor ?>}
</style>

<?php 
$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude from version 5 -->
<div class="page-heading">
    <div class="row">     
        <div class="page-title">
          <h1><?php echo Mage::helper('onestepcheckout')->getcheckoutPagetitle(); ?></h1>
        </div><!--page-title-->     
    </div><!--row-->  
</div><!--page-heading-->
<?php } ?> <!-- Exclude from v5 -->

<?php if(($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 5 -->
  
<?php } ?> <!-- For version 5 -->

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
       <div class="main-container col1-layout wow bounceInUp animated">
           <div class="main container">   
<?php } ?> <!-- For version 3,5 -->  

    <p style="margin-top:10px;"><?php echo Mage::helper('onestepcheckout')->getcheckoutPagedescp(); ?></p>
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
    <p class="onepagecheckout_loginarea">
        <a href="javascript:void(0)" class="onepagecheckout_loginlink" id="mgkoscshowlogin">
            <?php echo $this->__('Registered user? Login here') ?>
        </a>
    </p>
    <?php  //echo $this->getChildHtml('customer.login');
	  // echo $this->getChildHtml('customer.forgot');
    }    
    ?>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $seq_http	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'); ?>
<script type="text/javascript">
	var http_type	= '<?php if($seq_http){echo 'https';}else{echo 'http';}?>';
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('mgkoscheckout/js/onestepcheckout.js') ?>"></script>
<!--<script type="text/javascript" src="<?php //echo $this->getSkinUrl('mgkoscheckout/js/jquery-1.7.1.min.js') ?>"></script>-->
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<form action="" id="mgkosc_form">
<div class="mgkosc-datacontent" id="mgkosc-datacontent1">
    <div class="mgkosc-left">
        <?php echo $this->getChildHtml('billing.address') ?>
        <?php echo $this->getChildHtml('shipping.address') ?>
    </div>

    <div class="mgkosc-right">
        <div class="mgkosc-method">
	    <?php echo $this->getChildHtml('shipping.method'); ?>
	    <?php echo $this->getChildHtml('payment.method'); ?>
	    <div class="clear_both">&nbsp;</div>
	</div>
	<div class="mgkosc-review">
	      <div class=""><?php echo $this->getChildHtml('review'); ?></div>
	      
	</div>
    </div>
</div>

</form>
<script>
jQuery.noConflict();
      jQuery(document).ready(function(){
		    jQuery("#mgkoscshowlogin").click(function(){
			  jQuery("div#mgkoscloginoverlay").fadeIn("fast");       
			  jQuery("div#mgkosc-login").fadeIn("fast");     
			  return false;     
		    });                            
                    jQuery("#mgkoschidelogin").click(function(){                       
                                jQuery("div#mgkosc-login").fadeOut("fast");      
				jQuery("div#mgkoscloginoverlay").fadeOut("fast");  
				return false;  
                    });
		    jQuery("#mgkoscforgotpass").click(function(){
			    jQuery("div#mgkosc-login").hide();
			    jQuery("div#mgkosc-password").show();
			    return false;     
		    }); 
		    jQuery("#mgkoscloginback").click(function(){
			    jQuery("div#mgkosc-login").show();
			    jQuery("div#mgkosc-password").hide();
			    return false;     
		    }); 
		    jQuery("#mgkoschidepassword").click(function(){                       
                                jQuery("div#mgkosc-password").fadeOut('300');      
                               jQuery("div#mgkoscloginoverlay").delay('300');
                                jQuery("div#mgkoscloginoverlay").fadeOut('300');  
				return false;  
                    });
                });
</script>
<script type="text/javascript">
//<![CDATA[
    var checkout = new MGKOSC('mgkosc_form', {
    	save    : '<?php echo $this->getUrl('onestepcheckout/index/saveOrder', array('_secure'=>$seq_http)) ?>',
    	update  : '<?php echo $this->getUrl('onestepcheckout/index/updateCheckout', array('_secure'=>$seq_http)) ?>',
        success : '<?php echo $this->getUrl('onestepcheckout/index/success', array('_secure'=>$seq_http)) ?>',
        failure : '<?php echo $this->getUrl('checkout/cart') ?>'
    }, "<?php echo $this->__('Please agree to all the terms and conditions.') ?>");

    document.observe("dom:loaded", function() {
        var win_triggers	= Array();
   		$$('.checkout-agreements .agree a').each(function(item){
   			var obj	= {
   				el: $$('.' + item.className),
   		   		event: 'click',
				window: $(item.className + '-window')
			};
   			win_triggers.push(obj);
        });
		mgkosc_window	= new MGKOSC.Window({triggers: win_triggers});
    });
//]]>
</script>

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
   </div>
        </div>
<?php } ?> <!-- For version 3,5 -->