<div id="popup1" class="overlay">
<div class="popup">
<a class="close" href="#">&times;</a>
  <div class="formbuilder">

    	<div class="pop-product">
     <div class="col-md-5 col-sm-5 col-xs-12"><div class="pop-img">
        <img src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/our-story.jpg" alt="customize products" /></div>
       </div>
<div class="col-md-7 col-sm-7 col-xs-12"><?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','1')->setTemplate('formbuilder/form.phtml')->toHtml(); ?> 
</div>

        


</div><!--formbuilder-form-->
	</div>
	</div>
	</div>
    
    
   <div id="popup2" class="overlay">
<div class="popup">
<a class="close" href="#">&times;</a>
  <div class="formbuilder">

    	<div class="pop-product">
     <div class="col-md-5 col-sm-0 col-xs-12"><div class="pop-img1">
                            <div class="register007">
                                <ul>
                                    <li><img alt="Kit Price" src="<?php echo $this->getSkinUrl('kit-price.png'); ?>" /> <span>Starting from  <B>Rs 1,00,000</B></span></li>
                                    <li><img alt="Cupen 4" src="<?php echo $this->getSkinUrl('cupen4.png'); ?>" /> <span>10 years <B>WARRANTY</B></span></li>
                                    <li><img alt="Kit Delivery" src="<?php echo $this->getSkinUrl('kit-delivery.png'); ?>" /> <span><b>30 days </b> delivery</span></li>
                                    <li><img alt="Cupen 3" src="<?php echo $this->getSkinUrl('cupen3.png'); ?>" /> <span>Free <b>INSTALLATION</b></span></li>
                                </ul>
                            </div>
                            <img src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/register-popup.png" alt="Register" class="register-img">
                    </div>
       </div>
<div class="col-md-7 col-sm-12 col-xs-12"><?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','4')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
</div>

        


</div><!--formbuilder-form-->
	</div>
	</div>
	</div>
    
    
    <div id="popup3" class="overlay">
<div class="popup">
<a class="close" href="#">&times;</a>
  <div class="formbuilder">

    	<div class="pop-product">
     <div class="col-md-5 col-sm-0 col-xs-12"><div class="pop-img1">
                            <div class="register007">
                                <ul>
                                    <li><img src="<?php echo $this->getSkinUrl('kit-price.png'); ?>" /> <span>Starting from  <B>Rs 50,000</B></span></li>
                                    <li><img src="<?php echo $this->getSkinUrl('cupen4.png'); ?>" /> <span>5 years <B>WARRANTY</B></span></li>
                                    <li><img src="<?php echo $this->getSkinUrl('kit-delivery.png'); ?>" /> <span><b>30 days </b> delivery</span></li>
                                    <li><img src="<?php echo $this->getSkinUrl('cupen3.png'); ?>" /> <span>Free <b>INSTALLATION</B></span></li>
                                </ul>
                            </div>
                            <img src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/register-popup.png" alt="Register" class="register-img">
                    </div>
       </div>
<div class="col-md-7 col-sm-12 col-xs-12"><?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','2')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
</div>

        


</div><!--formbuilder-form-->
	</div>
	</div>
	</div>
    
    
    <div id="popup4" class="overlay">
<div class="popup">
<a class="close" href="#">&times;</a>
  <div class="formbuilder">

    	<div class="pop-product">
     <div class="col-md-5 col-sm-0 col-xs-12"><div class="pop-img1">
                            <div class="register007">
                                <ul>
                                    <li><img src="<?php echo $this->getSkinUrl('kit-qua.png'); ?>" /> <span>Get <B>QUOTATION</B></span></li>
                                    <li><img src="<?php echo $this->getSkinUrl('kit-com.png'); ?>" /> <span>Compare  <B>PRODUCTS</B></span></li>
                                    <li><img src="<?php echo $this->getSkinUrl('cupen4.png'); ?>" /> <span>Get the <b>BEST PRICE</b> </span></li>
                                    <li><img src="<?php echo $this->getSkinUrl('kit-opa.png'); ?>" /> <span>Take Second  <b>OPINION</b></span></li>
                                </ul>
                            </div>
                            <img src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/register-popup.png" alt="Register" class="register-img">
                    </div>
       </div>
<div class="col-md-7 col-sm-12 col-xs-12"><?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','3')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
</div>

        


</div><!--formbuilder-form-->
	</div>
	</div>
	</div>



