<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $this->setData('column_count',3);
?>
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $category_name = Mage::getModel('catalog/layer')->getCurrentCategory()->getName();
if( $category_name != 'Sale' ){
	echo '<div class="container">';
}
?>
<div class="page-title">
<h1><?php echo $this->getLayer()->getCurrentCategory()->getName() ?></h1>
</div>
<!-- <div class="container"> -->
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>
<?php if(!$_productCollection->count()): ?>
<?php
$empty_category_block = Mage::getModel('cms/block')->load('elantra_empty_category');
 if($empty_category_block->getIsActive()){
     echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_empty_category')->toHtml();
 } else { ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php } ?>
<?php else: ?>

<?php echo $this->getToolbarHtml() ?>

<!-- BEGIN CATEGORY PRODUCTS -->
<div class="category-products">

    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>

    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item odd<?php if(($i-1)%$_columnCount==0): ?> first1<?php elseif($i%$_columnCount==0): ?> last1<?php endif; ?>">
        <!-- BEGIN PRODUCT IMAGE -->
          <div class="product-image">

<?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                <?php //$_imgSize = 230; ?>
<div id="box">
<img class="small-image" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" width="230" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
</div>
            </a>
            
          </div> <!--product-image-->
          <!-- BEGIN PRODUCT SHOP -->
          <div class="product-shop">
            <h2 class="product-name">
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
            </h2>
            
                 <?php  if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                 <?php else: ?>
                        <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                 <?php  endif;  ?>
             
            <div class="desc std">
              <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
              <p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a></p>
            </div> <!--desc std-->

            <?php echo $this->getPriceHtml($_product, true) ?>

<?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
            
            <!-- BEGIN ACTIONS -->
            <div class="actions"> 
            <?php if($_product->isSaleable()): ?>
                   <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
              <?php else: ?>
                   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
              <?php endif; ?>            
              <span class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"><span><?php echo $this->__('Add to wishlist');?></span></a>
                <?php endif; ?>
                
              </span> <!--add-to-links-->
            </div> <!--actions-->

          </div> <!--product-shop-->
        </li>
    <?php endforeach; ?>
    </ol>

    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
   

  <ul class="products-grid">       
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>

        <?php endif ?>
   
<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- for version 1,2, 5 -->   

  <li class="item col-lg-4 col-md-4 col-sm-6 col-xs-12">
    <div class="item-inner">
      <div class="item-img">
        <div class="item-img-info">
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php //$_imgSize = 210; ?>
					<div id="box">
					<img class="small-image" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago1.gif"
					data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" width="230"
					alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					</div>
           </a>
           <div class="actions">
                  
                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                  <div class="link-wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-original-title="<?php echo $this->__('Wishlist');?>" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Wishlist');?></span></a></div>
                  <?php endif; ?>
                  
                  <?php if($_product->isSaleable()): ?>
                    <div class="add_cart"><button type="button"  data-original-title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Cart') ?></span></button></div>        
                  <?php else: ?>
                    <p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?> 
                </div><!--actions-->
                <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!--Exclude from v5-->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!--Exclude from v5-->
        </div>
      </div><!--item-img-->
      <div class="item-info">
        <div class="info-inner">
          <div class="item-title">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
              <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                      if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
            </a>
          </div>
          <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
          ?>
          <?php if(($get_current_layout=='custom_static_page_five')) { ?> <!--for v5-->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!--for v5-->
          <div class="item-content">                 
            <div class="price-box"><?php echo $this->getPriceHtml($_product, true) ?></div>
          </div>
        </div><!--info-inner-->
      </div><!--item-info-->
    </div><!--item-inner--> 
  </li>
  
<?php } ?><!-- End for version 1,2 -->

<?php if(($get_current_layout=='custom_static_page_three')) { ?> <!-- for version3 -->

  <li class="item col-lg-6 col-md-3 col-sm-4 col-xs-6">
    <div class="item-inner">
      <div class="item-img">
        <div class="item-img-info">
           <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php //$_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <div class="item-box-hover">
              <div class="box-inner">
               
                 <div class="actions">
                   <span class="add-to-links">
                      <?php if ($this->helper('wishlist')->isAllow()) : ?>
                         <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"><span><?php echo $this->__('Add to Wishlist');?></span></a>
                      <?php endif; ?>
                     
                   </span>
                 </div><!--actions-->
                 <div class="add_cart">
                   <?php if($_product->isSaleable()): ?>
                     <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                   <?php else: ?>
                     <p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                   <?php endif; ?> 
                 </div><!--add_cart-->
              </div><!--box-inner-->
            </div><!--item-box-hover-->
        </div><!--item-img-info-->
      </div><!--item-img-->
      <div class="item-info">
        <div class="info-inner">
          <div class="item-title">
             <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                  if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
             </a>
          </div><!--item-title-->
          <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
          ?>
          <div class="item-content">
            <?php  if($_product->getRatingSummary()): ?>
               <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
             <?php else: ?>
               <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
             <?php  endif;  ?>
             <div class="item-price">
               <?php echo $this->getPriceHtml($_product, true) ?>
             </div><!--item-price-->
          </div><!--item-content-->
        </div><!--info-inner-->
      </div><!--item-info-->
    </div><!--item-inner-->
    <div class="clearfix"> </div>   
  </li>

<?php } ?> <!-- end for version 3-->

<?php if(($get_current_layout=='custom_static_page_four')) { ?> <!-- for version4 -->

<li class="item col-lg-4 col-md-3 col-sm-4 col-xs-6">
    <div class="item-inner">
      <div class="item-img">
        <div class="item-img-info">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            
           
        </div><!--item-img-info-->
      </div><!--item-img-->
      <div class="item-info">
        <div class="info-inner">
          <div class="item-title">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                  if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
            </a>
          </div><!--item-title-->
          <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
          <div class="item-content">
             <?php  if($_product->getRatingSummary()): ?>
               <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
             <?php else: ?>
               <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
             <?php  endif;  ?>
             <div class="item-price">
               <?php echo $this->getPriceHtml($_product, true) ?>
             </div><!--item-price-->
             <div class="actions">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"></a>
                <?php endif; ?>
                <div class="add_cart">
                  <?php if($_product->isSaleable()): ?>
                    <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                  <?php else: ?>
                    <p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?> 
                </div> <!--add_cart-->
               
             </div><!--actions-->
          </div><!--item-content-->
        </div><!--info-inner-->
      </div><!--item-info-->
        <div class="clearfix"> </div>   
    </div> <!--item-inner-->
  </li>

<?php } ?> <!-- end for version 4 -->

  <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>

        <?php endif ?>
         
        <?php endforeach ?>   
   </ul>        
   <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
   <?php endif; ?>

</div> <!--category-products-->

<?php $category_name = Mage::getModel('catalog/layer')->getCurrentCategory()->getName();
if( $category_name != 'Sale' ){
	echo '</div>';
}
?>
<!--div class="toolbar-bottom">
    <?php //echo $this->getToolbarHtml() ?>
</div-->

<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
<div class="container"><p><?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription(); ?></p></div>