<?php 
/* New Products */
?>
<?php  $_helper = $this->helper('catalog/output'); ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

  <div class="pdt-content pdt_new_arrivals is-loaded">
    
    <ul class="pdt-list products-grid-home zoomOut play">

<?php $_columnCount = $this->getColumnCount(); ?> 
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>      
        <?php endif ?> 

<li class="item item-animate <?php if(($i-1)%$_columnCount==0): ?>wide-first<?php elseif($i%$_columnCount==0): ?> last<?php elseif($i%$_columnCount!==0): ?> odd1<?php endif; ?>">
<div class="item-inner">
           <div class="item-img">
             <div class="item-img-info">
               <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img class="img-responsive" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>"></a>
               <?php echo $this->helper('elantrasettings')->getLabel($_product);  ?>
               <div class="item-box-hover">
                 <div class="box-inner">
                   <?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1){?> 
                    <div class="product-detail-bnt">
                      <a rel="nofollow" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_product->getId(); ?>" data-fancybox-type="iframe" class="magik-btn-quickview button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>
                    </div><!--product-detail-bnt-->
                   <?php }  ?>
                   <div class="actions">
                     <span class="add-to-links">
                       <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"></a>
                       <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <a href="<?php echo $_compareUrl ?>" class="link-compare add_to_compare" title="<?php echo $this->__('Add to Compare');?>"></a>
                       <?php endif; ?>
                     </span>
                   </div><!--actions-->
                   <div class="add_cart">
                     <?php if($_product->isSaleable()): ?>
                        <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                      <?php else: ?>
                        <p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                      <?php endif; ?> 
                   </div><!--add_cart-->
                 </div><!--box-inner-->
               </div><!--item-box-hover-->

               
             </div> <!--item-img-info-->
           </div> <!--item-img-->
           <div class="item-info">
            <div class="info-inner">
              <div class="item-title">
                 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                      <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                      if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
                 </a>
              </div> <!--item-title-->
              <div class="item-content">
                    <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                    <div class="item-price"><?php echo $this->getPriceHtml($_product, true, '-new') ?></div>
                    
              </div> <!--item-content-->
            </div><!--info-inner-->
           </div><!--item-info-->       
         </div> <!--item-inner-->
</li><!--item item-animate-->
                   
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        <?php endif ?>       
    <?php endforeach; ?>

    </ul>
  </div> <!--pdt-content pdt_new_arrivals is-loaded-->

<?php endif; ?> <!-- Endif collection -->

