<?php
$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate();

              // some helpers
              $_helper = $this->helper('catalog/output');
              $storeId = Mage::app()->getStore()->getId();
              $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
              $productCount = $this->getData('num_products');

$visibility = array( 
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH, 
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                );
$attributeInfo = Mage::getResourceModel('eav/entity_attribute_collection')
              ->setCodeFilter('magikrecommended')
              ->getFirstItem();
  $attribute_info = $attributeInfo->getData();
 
  if($attribute_info['attribute_code'] == 'magikrecommended'){
$collection = Mage::getResourceModel('reports/product_collection') 
                      ->addAttributeToSelect('*')     
                      ->setStoreId($storeId) 
                      ->addStoreFilter($storeId)     
                      ->addAttributeToFilter('visibility', $visibility)
                      ->addAttributeToFilter('magikrecommended', true) 
                      ->setOrder('updated_at', 'desc')
                      ->addAttributeToSelect('status') 
                      ->setPageSize($productCount);
Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($collection);
$collection->addFieldToFilter(array(array('attribute' => 'magikrecommended', 'eq' => 1)));

/*  To display product by category id */
if($categoryId=$this->getData('category_id')){
      $category = Mage::getModel('catalog/category')->load($categoryId);
      $collection->addCategoryFilter($category);
    } ?>

<div class="featured-pro container wow bounceInUp animated animated" style="overflow:visible">
    <div class="slider-items-products">
<?php if(($get_current_layout=='custom_static_page_one')) { ?>  
     <div class="new_title center">
        <div class="starSeparator"><span aria-hidden="true" class="icon-star"></span></div>
        <h2><?php echo $this->__('Recommended') ?></h2>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_recommended_text_block')->toHtml() ?>
     </div>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_two')) { ?>  
     <div class="new_title center">
         <h2><?php echo $this->__('Recommended') ?></h2>
        <div class="starSeparator"></div>
      </div>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_five')) { ?>  
     <div class="new_title center">
         <h2><?php echo $this->__('Recommended') ?></h2>
      </div>
<?php } ?>

<?php             // if no products are currently recommended, display some text
              if (!$collection->count()) :
?>
      <p class="note-msg"><?php echo $this->__('There are no recommended products at the moment.') ?></p>
      <?php else : ?>
        
        <div id="featured-slider" class="product-flexslider hidden-buttons">
          <div class="slider-items slider-width-col4 products-grid">

        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 5;
                $i = 0;
               
                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());

        ?>
        
        <?php if ($i++%$_columnCount==0): ?>            
        <?php endif ?>  
   <div class="item">
     <div class="item-inner">
       <div class="item-img">
         <div class="item-img-info">
            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>"></a>
            <?php echo $this->helper('elantrasettings')->getLabel($_product);  ?>
            <div class="actions">
                  <?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1) { ?> 
                    <div class="quick-view-btn"><a rel="nofollow" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_product->getId(); ?>" data-fancybox-type="iframe" class="magik-btn-quickview quick-view" data-original-title="<?php echo $this->__('Quickview') ?>" data-placement="right" data-toggle="tooltip" ><span><?php echo $this->__('Quick View') ?></span></a>
                     </div>
                  <?php }  ?>
                  <div class="link-wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-original-title="<?php echo $this->__('Wishlist');?>" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Wishlist');?></span></a></div>
                  <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <div class="link-compare"><a href="<?php echo $_compareUrl ?>" data-original-title="<?php echo $this->__('Compare');?>" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Compare');?></span></a></div>
                  <?php endif; ?>
                  <?php if($_product->isSaleable()): ?>
                    <div class="add_cart"><button type="button"  data-original-title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Cart') ?></span></button></div>        
                  <?php else: ?>
                    <p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?> 
            </div><!--actions-->
            <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!--Exclude from v5-->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!--Exclude from v5-->
         </div>
       </div><!--item-img-->
       <div class="item-info">
              <div class="info-inner">
                <div class="item-title">
                   <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                      <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                      if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
                 </a>
                </div>
                <?php if(($get_current_layout=='custom_static_page_five')) { ?> <!-- for v5-->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!-- for v5-->
                <div class="item-content">
                  <div class="price-box"><?php echo $this->getPriceHtml($_product, true) ?></div>
                </div>
              </div>
            </div>
     </div><!--item-inner-->
       </div> <!--item-->
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>            
            <?php endif ?>      
                <?php endforeach ?> 

      </div> <!-- slider-items slider-width-col3-->
    </div> <!-- product-flexslider hidden-buttons-->
      <?php endif ?>  <!--Endif !$collection->count() -->

    </div> <!--slider-items-products-->
  </div> <!--featured-pro container wow bounceInUp animated animated-->

<?php } ?> <!-- chk attribute_code -->



