	 <div class="row">
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>
  <?php $_helper = $this->helper('catalog/output'); ?>
  <?php $_product = $this->getProduct(); ?>

   <?php if (Mage::getStoreConfig('elantrasettings/elantrasettings_products/nextprevious_product')): ?>

    <?php // Previous and Next product links in product page

    $_product = $this->getProduct();

    if(!$_product->getCategoryIds())
    return; // Don't show Previous and Next if product is not in any category

    $cat_ids = $_product->getCategoryIds(); // get all categories where the product is located
    $cat = Mage::getModel('catalog/category')->load( $cat_ids[0] ); // load first category, you should enhance this, it works for me

    $order = Mage::getStoreConfig('catalog/frontend/default_sort_by');
    $direction = 'asc'; // asc or desc

    $category_products = $cat->getProductCollection()->addAttributeToSort($order, $direction);
    $category_products->addAttributeToFilter('status',1); // 1 or 2
    $category_products->addAttributeToFilter('visibility',4); // 1.2.3.4

    $cat_prod_ids = $category_products->getAllIds(); // get all products from the category
    $_product_id = $_product->getId();

    $_pos = array_search($_product_id, $cat_prod_ids); // get position of current product
    $_next_pos = $_pos+1;
    $_prev_pos = $_pos-1;

    // get the next product url
    if( isset($cat_prod_ids[$_next_pos]) ) {
      $_next_prod = Mage::getModel('catalog/product')->load( $cat_prod_ids[$_next_pos] );
    } else {
      $_next_prod = Mage::getModel('catalog/product')->load( reset($cat_prod_ids) );
    }
    // get the previous product url
    if( isset($cat_prod_ids[$_prev_pos]) ) {
      $_prev_prod = Mage::getModel('catalog/product')->load( $cat_prod_ids[$_prev_pos] );
    } else {
      $_prev_prod = Mage::getModel('catalog/product')->load( end($cat_prod_ids) );
    }

    ?>

  <?php endif; ?>  <!-- Endif Next Previous Product -->

 <?php if(($get_current_layout=='custom_static_page_three')) { ?>
  <div class="product-view wow bounceInUp animated" itemscope itemtype="http://schema.org/Product" itemid="#product_base">
<?php }else{?>
<div class="product-view" itemscope itemtype="http://schema.org/Product" itemid="#product_base">
<?php } ?>
    <script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    </script>
    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
   
     <?php if(($get_current_layout!='custom_static_page_five')) { ?>
     <div class="product-next-prev">
        <?php if($_next_prod != NULL): ?>
          <a class="product-next" title="<?php echo $this->__('Next')?>" href="<?php print $_next_prod->getProductUrl(); ?>"><span></span></a>
        <?php endif; ?>  
        <?php if($_prev_prod != NULL): ?>
          <a class="product-prev" title="<?php echo $this->__('Previous')?>" href="<?php print $_prev_prod->getProductUrl(); ?>"><span></span></a>
        <?php endif; ?>  
     </div> <!--product-next-prev-->
     <?php } ?>

    <?php if(($get_current_layout=='custom_static_page_three')) { ?>
  <div class="product-essential container">
<?php }else{?>
<div class="product-essential">
<?php } ?>
   
  <?php if(($get_current_layout=='custom_static_page_five')) { ?>
   <div class="container">
     <div class="row">
  <?php } ?>
   
	<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>


<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_four')) { ?>
    <div class="product-img-box col-sm-6 col-xs-12">
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two')) { ?>
    <div class="product-img-box col-sm-7 col-xs-12">
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_five')) { ?>
    <div class="product-img-box col-lg-7 col-sm-5 col-xs-12">
<?php } ?>

      <?php echo $this->helper('elantrasettings')->getLabel($_product);  ?>    
      <?php echo $this->getChildHtml('media') ?>           
      <div class="clear"></div>
    </div>
  
<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_four') ) { ?>
    <div class="product-shop col-sm-6 col-xs-12">
  <?php } ?>
  <?php if(($get_current_layout=='custom_static_page_two')) { ?>
    <div class="product-shop col-sm-5 col-xs-12">
  <?php } ?>
  <?php if(($get_current_layout=='custom_static_page_five')) { ?>
    <div class="product-shop col-lg-5 col-sm-7 col-xs-12">
  <?php } ?>
    
    <div class="no-display">
      <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
      <input type="hidden" name="related_product" id="related-products-field" value="" />
    </div>

  <?php if(($get_current_layout=='custom_static_page_five')) { ?>
    <div class="product-next-prev">
        <?php if($_next_prod != NULL): ?>
          <a class="product-next" title="<?php echo $this->__('Next')?>" href="<?php print $_next_prod->getProductUrl(); ?>"><span></span></a>
        <?php endif; ?>  
        <?php if($_prev_prod != NULL): ?>
          <a class="product-prev" title="<?php echo $this->__('Previous')?>" href="<?php print $_prev_prod->getProductUrl(); ?>"><span></span></a>
        <?php endif; ?>  
     </div> <!--product-next-prev-->
  <?php } ?>

     <div class="product-name">
	     <h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
	</div> <!--product-name-->

    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?> 
    <?php echo $this->getChildHtml('alert_urls') ?>
    <?php echo $this->getChildHtml('product_type_data') ?>
    <?php echo $this->getChildHtml('bundle_prices') ?>
    <?php echo $this->getTierPriceHtml() ?>
    
	<?php 
		/* $quote = Mage::getSingleton('checkout/session')->getQuote();
		foreach ($quote->getAllItems() as $item){
		$pcp = $item->getDiscountAmount();
		$getmprice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false);
		$total= $getmprice - $pcp;
		echo $total;
		} 	 
	
		$originalPrice = $_product->getPrice();
		$finalPrice = $_product->getFinalPrice();
		$percentage = 0;
		if ($originalPrice > $finalPrice) {
			$percentage = ($originalPrice - $finalPrice) * 100 / $originalPrice;
		}

		if ($percentage) {
			echo $this->__('You save %s', $percentage . '%');
		}
		*/	
		
	?>
	
	
	
    <?php echo $this->getChildHtml('extrahint') ?>      
    
    <br>
	
    <?php if ($_product->getShortDescription()):?>
	<div class="emi-div"><span>EMI</span> also available</div>
    <!-- <div class="short-description">  
     <h2><?php //echo $this->__('Quick Overview') ?></h2> 
     <p><?php //echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
    </div> -->
				
  <?php endif;?>
				<div class="add-info1">
				<h2><?php echo $this->__('Product details') ?></h2> 
				
				<?php if ($_product->getsku ()):?>  
                <div class="row-fluid product-item-wrp"><div class="span4 product-item-bar">Product ID : </div><div class="span8 product-item-detail"><?php echo $_product->getResource()->getAttribute('sku')->getFrontend()->getValue($_product); ?></div></div>
                <?php endif;?>
				
				<?php if ($_product->getMaterial ()):?>  
                <div class="row-fluid product-item-wrp"><div class="span4 product-item-bar">Material : </div><div class="span8 product-item-detail"><?php echo $_product->getResource()->getAttribute('material')->getFrontend()->getValue($_product); ?></div></div>
                <?php endif;?>
				
				<?php if ($_product->getDimension ()):?>  
                <div class="row-fluid product-item-wrp"><div class="span4 product-item-bar">Dimension : </div><div class="span8 product-item-detail"><?php echo $_product->getResource()->getAttribute('dimension')->getFrontend()->getValue($_product); ?></div></div>
                <?php endif;?>
				
				<?php if ($_product->getColor ()):?>  
                <div class="row-fluid product-item-wrp"><div class="span4 product-item-bar">Color : </div><div class="span8 product-item-detail"><?php echo $_product->getResource()->getAttribute('color')->getFrontend()->getValue($_product); ?></div></div>
                <?php endif;?>
				
				</div>
 <?php if (!$this->hasOptions()):?>  
 <div class="add-to-box">  
 
 <?php echo $this->getChildHtml('product.info.checkdelivery'); ?>


<?php  $current_cat_id  = Mage::getModel('catalog/layer')->getCurrentCategory()->getId(); 

$cats = array();					
$children = Mage::getModel('catalog/category')->getCategories(110);
foreach ($children as $category) {
  
   $cats[] = $category->getID();
   
	$the_current_id =  $category->getID();
  $children_sub = Mage::getModel('catalog/category')->getCategories($the_current_id);
 if( $children_sub ) { foreach ($children_sub as $childr_sub) {
	  
	   $cats[] = $childr_sub->getID();
  }
  
 }
}

 if(in_array($current_cat_id,$cats)) { ?>
<div class="price-div01">
<div class="price-div-left01"><a class="tooltips" href="#"><img alt="" src="http://www.yagotimber.com/media/wysiwyg/vip-partpay.png" /><br />Part Pay <span><h2>PART PAYMENT</h2>
<p>Pay 25% online and remaining on cash on delivery</p></span></a>

</div>
<div class="price-div-left02"><a class="tooltips1" href="#"><img alt="" src="http://www.yagotimber.com/media/wysiwyg/vip-cashpay.png" /><br />Payment<span><h2>100% PAYMENT</h2>
<p>Pay 100% online and pay in easy installments.</p></span></a>

</div>
<div class="price-div-left01"><a class="tooltips2" href="#"><img alt="" src="http://www.yagotimber.com/media/wysiwyg/vip-cod.png" /><br />Cash Pick up <span>
<h2>CASH PICK UP</h2>
<p>Pay 100% in cash. 25% on order and remaining 75% on delivery.</p>
</span></a>

</div>
</div>
<?php } else {?>
 <!--25% Price block --> 
 <div class="price-div">
<div class="price-div-left"><a class="tooltips" href="#"><img alt="" src="http://www.yagotimber.com/media/wysiwyg/vip-partpay.png" /><br />Part Pay <span><h2>PART PAYMENT</h2>
<p>Pay 25% online and remaining on cash on delivery</p></span></a>

</div>
<div class="price-div-left"><a class="tooltips1" href="#"><img alt="" src="http://www.yagotimber.com/media/wysiwyg/vip-cashpay.png" /><br />EMI <span><h2>EMI OPTION</h2>
<p>Pay 100% online and pay in easy installments.</p></span></a>

</div>
<div class="price-div-left"><a class="tooltips2" href="#"><img alt="" src="http://www.yagotimber.com/media/wysiwyg/vip-cod.png" /><br />Cash Pick up <span>
<h2>CASH PICK UP</h2>
<p>Pay 100% in cash. 25% on order and remaining 75% on delivery.</p>
</span></a>

</div>
</div>

<?php } ?>
 <?php if($_product->isSaleable()): ?>
 
  <?php echo $this->getChildHtml('addtocart') ?>

<?php endif; ?>                
<?php echo $this->getChildHtml('addto') ?>

<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("magik/socialbar/socialbar.phtml")->setBlockId(2)->toHtml(); ?>


<?php echo $this->getChildHtml('extra_buttons') ?>  


</div> <!--add-to-box-->            
<?php elseif (!$_product->isSaleable()): ?>                
  <?php echo $this->getChildHtml('addto') ?>                
<?php endif; ?>           
 
 <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>/jquery.popupoverlay.js"></script>


<?php echo $this->getChildHtml('other');?>

<?php if ($_product->isSaleable() && $this->hasOptions()):?>
  <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
<?php endif;?>

<?php if ($_product->isSaleable() && $this->hasOptions()):?>
 <?php echo $this->getChildChildHtml('container2', '', true, true) ?>  
<?php endif;?>
    


</div> <!--product-shop-->  

<?php if(($get_current_layout=='custom_static_page_one')) { ?> <!-- for version 1 -->
  <div class="product-shop col-sm-2 col-xs-12">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_detail_banner_block')->toHtml() ?>
  </div>
<?php } ?>

</form>
<!-- Fade & scale -->



<script>
jQuery(document).ready(function () {

    jQuery('#fadeandscale').popup({
        pagecontainer: '.container',
        transition: 'all 0.3s'
    });

});
</script>

  <?php if(($get_current_layout=='custom_static_page_five')) { ?>
   </div>
     </div>
  <?php } ?>

</div> <!--product-essential-->







<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
      if (this.validator.validate()) {
        var form = this.form;
        var oldUrl = form.action;

        if (url) {
         form.action = url;
       }
       var e = null;
       try {
        this.form.submit();
      } catch (e) {
      }
      this.form.action = oldUrl;
      if (e) {
        throw e;
      }

      if (button && button != 'undefined') {
        button.disabled = true;
      }
    }
  }.bind(productAddToCartForm);

  productAddToCartForm.submitLight = function(button, url){
    if(this.validator) {
      var nv = Validation.methods;
      delete Validation.methods['required-entry'];
      delete Validation.methods['validate-one-required'];
      delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                  if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                  }
                }

                if (this.validator.validate()) {
                  if (url) {
                    this.form.action = url;
                  }
                  this.form.submit();
                }
                Object.extend(Validation.methods, nv);
              }
            }.bind(productAddToCartForm);
    //]]>
    </script>
    <?php if(($get_current_layout=='custom_static_page_two')) { ?> <!-- for version 2 -->
      <div class="product-collateral  col-lg-12 col-sm-12 col-xs-12 bounceInUp animated">
	<!-- Tabs -->
	  <?php echo $this->getChildHtml('product_additional_data') ?>     
      </div> <!--product-collateral-->
    <?php }else{?>

<div class="product-collateral col-lg-12 col-sm-12 col-xs-12 bounceInUp animated">
	<!-- Tabs -->
	  <?php echo $this->getChildHtml('product_additional_data') ?>     
      </div> <!--product-collateral-->
    <?php } ?>


    <?php if($get_current_layout=='custom_static_page_three') { ?> <!-- for version 3 -->
      <div class="box-additional"> 
            <!-- BEGIN CATEGORY PRODUCTS -->
           
	      <?php echo $this->getChildHtml('related_products') ?>
	 
	  <?php echo $this->getChildHtml('upsell_products') ?>

	    
    </div>
    <?php } ?>
  </div> <!--product view image-->
  			<div class="container">
            	<div class="product_img_landing01">
				<?php if ($_product->getImgLook ()):?>  
                <?php echo $_product->getResource()->getAttribute('img_look')->getFrontend()->getValue($_product); ?>
                <?php endif;?>
                </div>
  			</div>
  </div><!--row-->
		<div class="container">
		<?php if ($_product->getMoreinfo ()):?>  
		<div class="product-info-more"><h2>PRODUCT BLOG</h2>
		<p><?php echo $_product->getResource()->getAttribute('moreinfo')->getFrontend()->getValue($_product); ?></p></div>
		<?php endif;?>
		</div>
