<?php
/**
 * StarGenius_ProductLikeCount extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       StarGenius
 * @package        StarGenius_ProductLikeCount
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * ProductsLike link widget template
 *
 * @category    StarGenius
 * @package     StarGenius_ProductLikeCount
 * @author      Ultimate Module Creator
 */
?>
<?php $_productslike = $this->getCurrentProductslike();?>
<?php if ($_productslike) :?>
    <div class="productslike-widget-link">
        <a href="<?php echo $_productslike->getProductslikeUrl()?>"><?php echo $_productslike->getProductSku()?></a>
    </div>
<?php endif;?>
