<?php
/**
 * StarGenius_Yagostudio extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       StarGenius
 * @package        StarGenius_Yagostudio
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Yagostudio link widget template
 *
 * @category    StarGenius
 * @package     StarGenius_Yagostudio
 * @author      Ultimate Module Creator
 */
?>
<?php $_yagostudio = $this->getCurrentYagostudio();?>
<?php if ($_yagostudio) :?>
    <div class="yagostudio-widget-link">
        <a href="<?php echo $_yagostudio->getYagostudioUrl()?>"><?php echo $_yagostudio->getDesignerName()?></a>
    </div>
<?php endif;?>
