<?php 
$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<div class="col-main col-sm-9">
	<?php if(($get_current_layout!='custom_static_page_three') && ($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude From version 3,5 -->
  	<div class="page-title">
       <h2><?php echo $this->__('Blog') ?></h2>
    </div>
    <?php } ?> <!-- Exclude From version 3,5 -->
<div id="main" class="blog-wrapper">
    
	<div id="primary" class="site-content">
		<div id="content" role="main">
			<?php
			$processor = Mage::getModel('core/email_template_filter');
			
			//$post_title_slug = $this->getRequest()->getParam('p');
			$currentUrl = Mage::helper('core/url')->getCurrentUrl();
			$post_title_slug = substr( $currentUrl, strrpos( $currentUrl, '/' )+1 );
			$post_data = $this->getPostDataBySlug($post_title_slug);
			$post_value = $post_data[0];

				?>
				<div itemscope itemtype ="http://schema.org/BlogPosting">
				<article id="post-29" class="blog_entry clearfix">
					<header class="blog_entry-header clearfix">
                                          <div class="blog_entry-header-inner">
						<h1 itemprop="headline" class="blog_entry-title">
							<?php echo $title = $processor->filter($post_value['title']);?>
						</h1>
                                          </div> <!--blog_entry-header-inner-->
					</header> <!--blog_entry-header clearfix-->
					<div class="entry-content">
						<?php echo $blog_content = $processor->filter($post_value['blog_content']);?>
					</div>
					<div class="entry-meta blog_top_box">
						<?php echo $this->__('This entry was posted') ?>
						<?php
						$categories_selected = $post_value['categories_selected'];
						$categories_selected = explode(',', $categories_selected);
						foreach ($categories_selected as $category_key => $category_id) {
							$category_detail = $this->getCategoryById($category_id);
							//$category_url = $home_url.'blogmate/view/category/c/'.$category_detail[0]['title_slug'].'/';
							$urlKey = $category_detail[0]['title_slug'];
							$curl = Mage::getUrl('blog/view/category/c/'.$urlKey, array('_direct' => $urlKey)); 
							$cnt=Mage::getModel('blogmate/blog')->chkIfExists('index/'.$urlKey,$urlKey);
							$store_id=Mage::app()->getStore()->getId();
							if($cnt==0 && ($urlKey!=''))
							{	
								$curl1=$category_detail[0]['title_slug'];
								$rewrite = Mage::getModel('core/url_rewrite');
								$rewrite->setStoreId($store_id)
								->setIdPath('index/'.$urlKey)
								->setRequestPath($curl1)
								->setTargetPath('blog/view/category/c/'.$urlKey)
								->setIsSystem(true)
								->save();

							}
							$category_url =$curl;
							

							if($category_key==0) echo 'in ';
							else echo ', ';
							?>
							<a href="<?php echo $category_url;?>" title="View all posts in <?php echo ucfirst($category_detail[0]['title']);?>" rel="category tag"><?php echo ucfirst($category_detail[0]['title']);?></a>
						<?php
						}
						
						?>
						<?php echo $this->__('On') ?> <time itemprop="datePublished" class="entry-date" datetime="<?php echo date('c', strtotime($post_value['created_at']));?>"><?php echo date('M d, Y', strtotime($post_value['created_at']));?></time>.
					</div>
                    
                    <div class="blog_boot1">
                <div class="social blog_social">      
       <ul class="link">
		 <li class="fb">
			  <a href="http://www.facebook.com/share.php?u=<?php echo $currentUrl; ?>&amp;t=" rel="nofollow" target="_blank" style="text-decoration:none;">
				</a>
				</li>
				<li class="tw">
				<a href="http://twitter.com/home?status=%20-%20<?php echo $currentUrl; ?>" rel="nofollow" target="_blank" style="text-decoration:none;">				
				</a>
				</li>
				<li class="pintrest">
				<a href="http://pinterest.com/pin/create/link/?url=<?php echo $currentUrl; ?> inches&#10;Width: 59 inches&#10;Depth:&nbsp;35 inches&#10;Seating Height:&nbsp;18&#10;Assembly:&nbsp;Taken care by us&#10;Colour:&nbsp;Provincial Teak&#10;Warranty:&nbsp;3 year warranty&#10;Dimensions:&nbsp;Table : H 30 x W 59 x D 35; Bench : H 18 x W 47 x D 14; Seating Height - 18&#10;Primary Material: Mango Wood&#10;Room Type:&nbsp;Dining Room" rel="nofollow" target="_blank" style="text-decoration:none;">
					
				</a>
				</li>
				<li class="googleplus">
				<a href="https://plus.google.com/share?url=<?php echo $currentUrl; ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				</a>
			</li>
		</ul>
        </div>
<div class="call_action01">For Assistance Please <img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/phone036.png"> <b>8010 255 255</b></div>
</div>
				</article>
				</div>
                
                
				<?php
			
			?>
		
		
			
			<div class="comment-content wow bounceInUp animated">
				<?php
					$comment_config = Mage::getStoreConfig('blogmate/comment_setting');
					if($comment_config['enabled'] && $post_value['enable_comment']) {
						echo $this->getChildHtml('blog_comments');

					}
				?>
			</div>
		</div>
	</div>

</div> <!--#main wrapper grid_8-->

        

  </div> <!--col-main col-sm-9-->
  <?php
                echo $this->getChildHtml('blog_right');
        ?>
