<?php if (!$_agree = $this->getAgreements()) return; ?>

<div class="checkout-agreements">
    <p class="agree">
	<input type="checkbox"   class="checkbox" />I Agree <a href="#" id="mgkoscshowpopup">Terms and Conditions</a>
	<!--<div id="mgkosc-popup">
	  <a href="#" id="mgkoschidepopup" class="mgkosc-popupclose"><img src="<?php //echo $this->getSkinUrl('mgkoscheckout/images/onestepcheckout/c-icon.png') ?>"  alt="" /></a>
	      <div class="mgkosc-popuptext">
		    <p class="mgkosc-agreeinfo">Terms and Conditions</p>
		      <div class="mgkosc-popuptextblock">
			    <div class="mgkosc-popuptextdetails"><?php //echo Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcterms_group/mgktermscontent'); ?> </div>
		      </div>
		  </div>
	</div>-->
   </p>
   <!--<div id="mgkoscoverlay"></div>-->
</div>
