<div class="add-to-cart">
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>  
  <div class="pull-left">  
  
    <div class="custom pull-left">
        <?php if(!$_product->isGrouped()): ?>         

          <button onClick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 0 ) result.value--;return false;" class="reduced items-count" type="button"><i class="fa fa-minus"></i></button>
             
          <input type="text" name="qty" id="qty"  maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Quantity:') ?>" class="input-text qty" />
       
          <button onClick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;" class="increase items-count" type="button"><i class="fa fa-plus"></i></button>
                   
        <?php endif; ?>        
        <?php echo $this->getChildHtml('', true, true) ?>   
    </div> <!--custom pull-left-->
  </div> <!--pull-left-->     
<?php endif; ?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

  
   <ul class="add-to-links">
     <li>
        <?php if ($this->helper('wishlist')->isAllow()) : ?>
          <a class="link-wishlist" href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" title="<?php echo $this->__('Add To Wishlist') ?>" ><span><?php echo $this->__('Add To Wishlist') ?></span></a>
        <?php endif; ?>
     </li>
    
   </ul>  <!--add-to-links-->


  
<button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><?php echo $buttonTitle ?></span></button>  
  
</div> <!--add-to-cart-->