<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/flexslider.css" type="text/css" />
<script src="<?php echo $this->getSkinUrl(); ?>js/jquery.flexslider.js" type="text/javascript"></script>

 <?php if(($get_current_layout=='custom_static_page_three')) { ?>
<script src="<?php echo $this->getSkinUrl(); ?>js/cloud-zoom3.js" type="text/javascript"></script>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_four')) { ?>
<script src="<?php echo $this->getSkinUrl(); ?>js/cloud-zoom4.js" type="text/javascript"></script>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_five')) { ?>
<script src="<?php echo $this->getSkinUrl(); ?>js/cloud-zoom.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 1,2,3,5 -->
<div class="product-image">
  <div class="large-image">
<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" class ="cloud-zoom" id="zoom1" rel="useWrapper: false, adjustY:0, adjustX:20">
    <?php
        $_img = '<img itemprop="image" id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image'); 
    ?>
</a> 
</div>
<?php  if (count($this->getGalleryImages()) > 0): ?>
  <div class="flexslider flexslider-thumb">
    <ul class="previews-list slides">
      <?php foreach ($this->getGalleryImages() as $_image): ?>
      <li>
        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" class="cloud-zoom-gallery" rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>' " title="<?php echo $_product->getName();?>">
            <img class="zoom-tiny-image" itemprop="image" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>"  />
        </a>
      </li>
      <?php endforeach; ?>
    </ul>
  </div>

<?php endif; ?>
</div> <!--product-image-->
<?php } ?> <!-- End For version 1,2,3 -->

<?php if($get_current_layout=='custom_static_page_four') { ?> <!-- For version 4 -->

  <div class="product-img-list">
    <?php  if (count($this->getGalleryImages()) > 0): ?>
    <div class="more-views-verticle">
       <a class="more-views-prev more-views-nav" href="javascript:void(0)" id="carousel-up" style="display: block;"> <i class="fa fa-angle-up"></i> </a>
       <div class="media-list">      
        <div style="top: 0px;" id="more-slides" class="verticl-carousel product-image-thumbs">
          <?php foreach ($this->getGalleryImages() as $_image): ?>
          <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" class="thumb-link cloud-zoom-gallery" rel="useZoom: 'zoom2', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>' " title="<?php echo $_product->getName();?>">
            <img class="img-responsive zoom-tiny-image" itemprop="image" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>"  />
          </a>
          <?php endforeach; ?> 
          </div>          
        </div>
        <a class="more-views-next more-views-nav" href="javascript:void(0)" id="carousel-down" style="display: block;"> <i class="fa fa-angle-down"></i> 
          </a>
          </div>
        <?php endif; ?>
        <div class="product-image">
          <div class="largeImg_wrap">
            <div id="wrap" style="top:0px;z-index:700;position:relative;">
              <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" class ="cloud-zoom" id="zoom2" rel="position: 'inside' , showTitle: false, adjustX:-4, adjustY:-4" style="position: relative; display: block;">
                <?php
                    $_img = '<img itemprop="image" id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image'); 
                ?>
              </a> 
            </div>
          </div>
        </div>
      </div>

<?php } ?> <!-- End For version 4 -->
