
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 	//$data= $this->getQuoteData() ;
 
?>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
   
      
   
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
     <li>
            <?php 
			echo $this->__('You will be redirected to CCavenuepay website when you place an order.') ?>
        </li>
		<p><img src="<?php echo $this->getSkinUrl('ccavenue/ccavenue.png') ?>"/></p>
		 <?php 
$cat_array = array();
$home_decor = 0;
$quote= Mage::getSingleton('checkout/session')->getQuote();
foreach ($quote->getAllItems() as $item) 
{
   $product = $item->getProduct();
   $cat_array_get = $product->getCategoryIds();
  foreach($cat_array_get as $cat_array_get) {
	$cat_array[] =   $cat_array_get;
  }
}
$cat_array = array_unique($cat_array);

unset( $cat_array[array_search( '2', $cat_array )] );



$cats = array();					
$children = Mage::getModel('catalog/category')->getCategories(110);
foreach ($children as $category) {
  
   $cats[] = $category->getID();
   
	$the_current_id =  $category->getID();
  $children_sub = Mage::getModel('catalog/category')->getCategories($the_current_id);
 if( $children_sub ) { foreach ($children_sub as $childr_sub) {
	  
	   $cats[] = $childr_sub->getID();
  }
  
 }
}


$result=array_diff($cat_array,$cats);
 $check_all_cats = count($result);

 if($check_all_cats == 0){
	 $home_decor = 1; 
 }
 else {
	$home_decor = 0;  
 }

?> <?php if($home_decor == 0) { ?>
<p>
        <label>
          <input  required type="radio" name="payashu" value="yes" id="payment_nvd_0" />
          25% Payment</label>
        <br />
       
        <label>
          <input  required type="radio" name="payashu" value="no" id="payment_nvd_1" />
          100 % Payment</label>
        <br />
     <?php } ?> </p>
    </ul>
</fieldset> 
