<?php
/** Magik_Quickview extension */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>

    <?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_one')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu1.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_two')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min2.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu2.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common2.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_three')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu3.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common3.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_four')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min4.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal4.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common4.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_five')) { ?>     
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu5.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common5.js" type="text/javascript"></script>
<?php } ?>

    <base target="_parent" />

</head>
<body class="page-empty <?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
    <div>
        <div class="mgkquickviewdetailpage container">
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
</body>
</html>
