<?php 
$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_three')) { ?> <!-- For version 3 -->
<div class="page-heading">
        <div class="page-title">
          <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
        </div><!--page-title-->
</div><!--page-heading-->
<?php } ?> <!-- For version 3 -->

<?php if(($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 5 -->
<div class="shop_header has_big_img">
    <div class="shop_header_image_background  parallax loaded" data-stellar-background-ratio="&quot;0.5&quot;"> </div>
    <div class="cms-bg-overlay"></div>
    <div class="container">
      <div class="page-title">
          <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
        </div>
    </div>
  </div>
<?php } ?> <!-- For version 5 -->

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3, 5 -->
  <div class="main-container col1-layout wow bounceInUp animated">
    <div class="main container">
<?php } ?> <!-- For version 3, 5 -->

    <div class="account-login">

      <?php if(($get_current_layout!='custom_static_page_three') && ($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude From version 3,5 -->
        <div class="page-title">
          <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
        </div><!--page-title-->
      <?php } ?> <!-- Exclude From version 3,5 -->

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <fieldset class="col2-set">
    <strong><?php echo $this->__('Retrieve your password here') ?></strong>
      <div class="content">        
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address"><?php echo $this->__('Email Address') ?><em class="required">*</em></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
      </div>  <!--content-->
      
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button  type="submit" title="<?php echo $this->__('Submit') ?>" class="button submit"><span><?php echo $this->__('Submit') ?></span></button>
        <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a>
      
    </fieldset>  <!--col2-set-->
</form>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate');
//]]>
</script>
</div>

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
    </div>
  </div>
<?php } ?> <!-- For version 3,5 -->