<?php $config = Mage::getStoreConfig('elantrasettings/elantrasettings_appearance'); 

$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>
  
<!--   nitesh  -->
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<?php if(Mage::app()->getRequest()->getRouteName() === 'cms' ){ ?>
<title><?php echo Mage::getSingleton('cms/page')->getContentHeading()?></title>
<?php  }
else { ?>
<title><?php echo $this->getTitle() ?></title>
<?php } ?>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no">
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="google-site-verification" content="DAumtLHNIqUfcwSdmOjuy8wlF99jtXe9jCPZLxfgU9c" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two')) { ?> <!--for version 1,2-->
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700,400,300,100' rel='stylesheet' type='text/css'>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_three')) { ?> <!--for version3-->
   <link href='https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Roboto:900italic,900,700italic,700,500italic,500,400italic,300italic,400,300,100italic,100' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_four')) { ?> <!--for version4-->
   <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_five')) { ?> <!--for version5-->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300,600,800,400italic,300italic,600italic,700italic,800italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<?php } ?>

<?php   if ( !empty($config['font']) ) : ?>
<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $config['font']); ?>' rel='stylesheet' type='text/css'>
<?php endif; ?>
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<script type="text/javascript">
var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
var SKIN_URL = '<?php echo $this->helper('core/js')->getJsSkinUrl('') ?>';
</script>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3iUXURCEOq6oBZ2ZwfyjmcrNOsgM16Ko";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>


<style type="text/css">
/*  update google Font  */
<?php   if ( !empty($config['font']) ) : ?>
body { font-family: '<?php echo $config['font']; ?>',  sans-serif !important;  } 
<?php endif; ?>
<?php   if ( !empty($config['header_bg_color']) ) : ?>
.header-container { background:<?php echo $config['header_bg_color']; ?> !important;  }
<?php endif; ?>
<?php if ( !empty($config['header_fg_color']) ) : ?>
.toplinks div.links div a, .header-top .welcome-msg, .block-language, .block-currency {color:<?php echo $config['header_fg_color']; ?> !important; }
<?php endif; ?>
<?php if ( !empty($config['footer_bg_color']) ) : ?>
.footer {background:<?php echo $config['footer_bg_color']; ?> !important; }
<?php endif; ?>
<?php if ( !empty($config['footer_fg_color']) ) : ?>
.footer-middle h4 {color:<?php echo $config['footer_fg_color']; ?> !important; }
<?php endif; ?>
<?php if ( !empty($config['content_bg_color']) ) : ?>
.page {background:<?php echo $config['content_bg_color']; ?> !important; }
<?php endif;  ?>
</style>

<?php /*?><script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script><?php */?>
 <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>/jquery.popupoverlay.js"></script>
 
  <script src="http://site4clientdemo.com/facebook_page/jquery.socialthings.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78475111-1', 'auto');
  ga('send', 'pageview');

</script>

<script>

$(function() {

	// load fb first. All buttons on the page will be created.
	// normally, this is enough.
	$.socialthings.facebook.loadJS();

	// extra button test.
	// apply `initFacebookThings` to create buttons against dynamically added DOM.
	var $extraButtons = $('#extraButtons');
	$('#addExtra').click(function() {
		var ids = [
			'fblikeboxsrc',
			'fblikebuttonsrc',
			'fbcommentsrc'
		];
		var index = Math.floor(Math.random() * 100) % 3; // 0 ~ 2
		var src = $(document.getElementById(ids[index])).html(); // get src
		var $newButton = $('<span></span>').html(src); // span wrap 
		$extraButtons.append($newButton); // then add,
		$newButton.initFacebookThings(); // and apply facebook button
	});

});

</script>
<script type="text/x-htmlsrc" id="fblikeboxsrc">
<div 
	class="fb-like-box"
	data-href="https://www.facebook.com/Yagotimbercom-1061546610576083/"
	data-show-faces="true"
	data-width="485"
	data-hight="215"
	data-stream="false"
	data-border-color="#ffffff"
	data-header="true"
></div>

</script>

    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>js-webshim/minified/polyfiller.js"></script>
    <script> 
        webshim.activeLang('en');
        webshims.polyfill('forms');
        webshims.cfg.no$Switch = true;
    </script>
