
<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate();
if(count($this->getStores())>1):
      if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_three')) { ?> <!-- For version 1, 3 -->
	  <div class="form-language">  
	    <ul class="lang">        
		  <?php foreach ($this->getStores() as $_lang): ?>       
		      <li><a href="<?php echo $_lang->getCurrentUrl();?>">
			<img src="<?php echo $this->getSkinUrl('images/flags/'.$this->htmlEscape($_lang->getCode()).'.png') ?>" alt="<?php echo $this->htmlEscape($_lang->getName()) ?>" />
			<span><?php echo $this->htmlEscape($_lang->getName()) ?></span>
		      </a></li>         
		  <?php endforeach;?>
	    </ul>
	  </div> <!--form-language-->
      <?php } ?> <!-- End For version 1, 3 -->

  <?php if(($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_four') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 2, 4, 5 -->

	   <div class="dropdown block-language-wrapper">
  <?php $storecode = Mage::app()->getStore()->getCode(); ?>
  <a href="#" class="block-language dropdown-toggle" data-target="#" data-toggle="dropdown" role="button"> <img src="<?php echo $this->getSkinUrl('images/flags/'.$storecode.'.png') ?>" alt="<?php echo $storecode; ?>"/> <?php echo Mage::app()->getStore()->getName(); ?> <span class="caret"></span> </a>
  
   <ul role="menu" class="dropdown-menu">        
        <?php foreach ($this->getStores() as $_lang): ?>       
            <li role="presentation"><a href="<?php echo $_lang->getCurrentUrl();?>" tabindex="-1" role="menuitem">
               <img src="<?php echo $this->getSkinUrl('images/flags/'.$this->htmlEscape($_lang->getCode()).'.png') ?>" alt="<?php echo $this->htmlEscape($_lang->getName()) ?>" />
               <?php echo $this->htmlEscape($_lang->getName()) ?>
            </a></li>         
        <?php endforeach;?>
   </ul>
</div> <!--dropdown block-language-wrapper-->
      <?php } ?> <!-- End For version 2, 4 -->

<?php endif;?>