<?php
/**
 * StarGenius_AskAnExpert extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       StarGenius
 * @package        StarGenius_AskAnExpert
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Question link widget template
 *
 * @category    StarGenius
 * @package     StarGenius_AskAnExpert
 * @author      Ultimate Module Creator
 */
?>
<?php $_questions = $this->getCurrentQuestions();?>
<?php if ($_questions) :?>
    <div class="questions-widget-link">
        <a href="<?php echo $_questions->getQuestionsUrl()?>"><?php echo $_questions->getName()?></a>
    </div>
<?php endif;?>
