<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_one')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu1.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_two')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min2.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu2.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common2.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_three')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu3.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common3.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_four')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min4.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal4.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common4.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_five')) { ?>     
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu5.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common5.js" type="text/javascript"></script>
<?php } ?>

</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
  <div id="page">
             <?php echo $this->getChildHtml('after_body_start') ?>

       <?php echo $this->getChildHtml('global_notices') ?>      
      
      <?php echo $this->getChildHtml('header') ?>

       <?php echo $this->getChildHtml('breadcrumbs') ?> 
		<div class="page-title">
        	
			<h1><?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getName();?></h1>
		</div>
           <!-- BEGIN Main Container col2-right --> 
            <div class="main-container col2-right-layout">
              <div class="main container">
                <div class="row">
                  <div class="col-main col-sm-12 wow bounceInUp animated">
              <?php echo $this->getChildHtml('global_messages') ?>
             <?php // echo $this->getChildHtml('content') ?>    
                     <div class="container">

  <?php     $category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$category = Mage::getModel('catalog/category')->load($category_id);
    $collection = Mage::getModel('catalog/product')->getCollection();
								$collection->addAttributeToSelect('*')->addAttributeToSort('price','ASC')->addCategoryFilter($category);
								$collection->setPageSize(8)->setCurPage(1);
								$products = $collection->getItems();
	 $category_name = Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription();
	 ?>  
 
<div class="wardor_shape01">
<ul>
<li><a href="<?php echo Mage::getBaseUrl(); ?>">HOME</a></li>
<li><a <?php if($category_name == 'l-shaped-wardrobe'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>l-shaped-wardrobe">L SHAPED</a></li>
<li><a <?php if($category_name == 'U'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>u-shaped-wardrobe">U SHAPED</a></li>
<li><a <?php if($category_name == 'PARALLEL'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>parallel-wardrobe">PARALLEL</a></li>
<li><a  <?php if($category_name == 'STRAIGHT'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>straight-wardrobe">STRAIGHT</a></li>
</ul>
</div>
 
      </div>
	  	  <ul id="list001" >	 
         <?php $i=1; foreach($products as $product_data) {?>  
      <?php 
		$productMediaConfig = Mage::getModel('catalog/product_media_config');

 $baseImageUrl = $productMediaConfig->getMediaUrl($product_data->getImage());
		
	
	 ?>
	 <li>
	 <div class="container">
       <div class="land01">
<div class="row">
<div class="col-md-8 col-sm-8 col-xs-12">
<div class="land01_img"><a href="#fadeandscalelerge<?php echo $i; ?>" class="fadeandscalelerge<?php echo $i; ?>_open" title="Click to Enlarge"><img alt="" src="<?php echo $baseImageUrl; ?>" /></a></div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="land01_detail">
<div class="heard001">

<?php 
       
	 
  $collection = Mage::getResourceModel('stargenius_productlikecount/productslike_collection')
                ->addFieldToFilter('product_sku', $product_data->getSku())
				->load();
		 $total_count = 0;
		  foreach ($collection->getItems() as $productslike) {
           
               $total_count =   $total_count + $productslike->getProductLiked();
              
        }
		
		
			 ?>
<p>
<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hart_1.png"> 
<?php 

 $collection_current = Mage::getResourceModel('stargenius_productlikecount/productslike_collection')
                ->addFieldToFilter('product_sku', $product_data->getSku())
				 ->addFieldToFilter('u_ipaddress',$_SERVER['REMOTE_ADDR'])
				->load(); 
				 if($collection_current->getItems()) { ?>
				<div id="heart_like<?php echo $product_data->getId(); ?>">	 <img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/heart.png"></div>
				<?php  }
               else {?>
	<div id="heart_like<?php echo $product_data->getId(); ?>" class="heard002"> 
    <button id="countplus<?php echo $product_data->getId();?>" ><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/heart.png"></button></div>
			<?php    }?>
<span id="uptotal<?php echo $product_data->getId();?>" ><?php echo $total_count; ?></span></p>

</div>
      
<ul>
<li><h2><?php echo $product_data->getName(); ?></h2></li>
<li><h6><?php echo $product_data->getDescription(); ?></h6></li>
<li><h7><B>BUY THIS LOOK  :</B> <?php echo $product_data->getShortDescription(); ?></h7></li>
</ul>
<a id="open_55592391" data-popup-ordinal="1" href="#fadeandscaledesigner<?php echo $i; ?>" class=" fadeandscaledesigner<?php echo $i; ?>_open"><div class="des09">Consult Designer</div></a>
<div class="share">Share This Look
<div class="social">      
       <ul class="link">

					<li class="fb">
	<a href="http://www.facebook.com/share.php?u=<?php echo $product_data->getProductUrl(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				
			</a>
			</li>

				<li class="tw">
			<a href="http://twitter.com/home?status=<?php echo $product_data->getProductUrl(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				
			</a>
			</li>

				<li class="pintrest">
<a href="http://pinterest.com/pin/create/link/?url=<?php echo $product_data->getProductUrl(); ?>&media=<?php echo  $baseImageUrl; ?>&description=<?php echo $product_data->getDescription(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;"></a>
			</li>

		<li class="googleplus">
			<a href="https://plus.google.com/share?url=<?php echo $product_data->getProductUrl(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				
			</a>
			</li>

	</ul>
	</div>
</div>
</div>
</div>
</div>
</div>
</div>

       <!-- Fade & scale -->
<div id="fadeandscaledesigner<?php echo $i; ?>" class="well" style="display:none;"><a class=" fadeandscaledesigner<?php echo $i; ?>_close close02">X</a>
<div class="col-md-5 col-sm-12 col-xs-12"><div class="pop-img1">
                            <div class="register007">
                                <ul>
                                    <li><img alt="Kit Price" src="<?php echo $this->getSkinUrl('kit-price.png'); ?>" /> <span>Starting from  <B>Rs 1,00,000</B></span></li>
                                    <li><img alt="Cupen 4" src="<?php echo $this->getSkinUrl('cupen4.png'); ?>" /> <span>10 years <B>WARRANTY</B></span></li>
                                    <li><img alt="Kit Delivery" src="<?php echo $this->getSkinUrl('kit-delivery.png'); ?>" /> <span><b>30 days </b> delivery</span></li>
                                    <li><img alt="Cupen 3" src="<?php echo $this->getSkinUrl('cupen3.png'); ?>" /> <span>Free <b>INSTALLATION</b></span></li>
                                </ul>
                            </div>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/register-popup.png" alt="Register" class="register-img">
                    </div>
       </div>
       <div class="col-md-7 col-sm-12 col-xs-12">
	<div class="bookdesigner">
        <div class="col-md-12 col-sm-12 col-xs-12"><?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','7')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
	</div>
    </div>
    </div>
</div>
<style>
#fadeandscalelerge<?php echo $i; ?> {
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
			  max-width: 900px;
			  
}
.popup_visible #fadeandscalelerge<?php echo $i; ?> {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
			max-width: 900px;
}
<style><!--
#fadeandscaledesigner<?php echo $i; ?> {
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
			  max-width: 900px;
}
.popup_visible #fadeandscaledesigner<?php echo $i; ?> {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
			max-width: 900px;
}

@media (max-width: 800px) {
	#fadeandscaledesigner<?php echo $i; ?> {width: 400px;}
	.pop-img1{display:none;}
	
}

@media (max-width: 500px) {
	#fadeandscaledesigner<?php echo $i; ?> {width: 300px;}
}




</style> 
<script type="text/javascript">
jQuery(document).ready(function () {

    jQuery('#fadeandscaledesigner<?php echo $i; ?>').popup({
        pagecontainer: ".container",
        transition: "all 0.3s"
    });

});
</script>
  <script type="text/javascript">
		
			
jQuery("#countplus<?php echo $product_data->getId(); ?>").click(function(){
	
var id = <?php echo $product_data->getId(); ?>;
var sku = '<?php  echo $product_data->getSku();  ?>';
var ip = '<?php echo $_SERVER['REMOTE_ADDR'] ?>';
var dataString = 'id='+ id + '&sku='+ sku + '&ip='+ ip;
// AJAX Code To Submit Form.
jQuery.ajax({
type: "POST",
url: "<?php echo Mage::getBaseUrl(); ?>productlikecount/productslike/ashu/",
data: dataString,
cache: false,
success: function(result){
jQuery("#uptotal<?php echo $product_data->getId(); ?>").html(result);
var heartl = '<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/heart.png">';
jQuery("#heart_like<?php echo $product_data->getId(); ?>").html(heartl);
}
});

});

</script>

<div id="fadeandscalelerge<?php echo $i; ?>" class="well" style="display:none;"><a class=" fadeandscalelerge<?php echo $i; ?>_close close02">X</a>
	<div class="lerge_box">   <img alt="" src="<?php echo $baseImageUrl; ?>" />    </div>
</div>

<script type="text/javascript">jQuery(document).ready(function () {

    jQuery('#fadeandscalelerge<?php echo $i; ?>').popup({
        pagecontainer: ".container",
        transition: "all 0.3s"
    });

});</script>
  


        
      </li> 
         <?php 
		 $i++;
		 }
		 
		 // loop end ?>  
</ul>
<div id="loading"><p align="center">Please wait.</p>
<p align="center">Loading Products...</p>
<p align="center"> <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/loader.gif" ></p></div>
<button id="btnproducts" class="load-btn" >Load More..</button>
<input value="2" id="pcount" name="pcount" type="hidden" />
<input value="9" id="icount" name="icount" type="hidden" />
</div>
 <script type="text/javascript">
		jQuery("#loading").hide();
			
jQuery("#btnproducts").click(function(){
	jQuery("#loading").show();
var category = <?php echo $category_id; ?>;
var pcount =  parseInt(jQuery("#pcount").val());
var icount =  parseInt(jQuery("#icount").val());
var dataString = 'category='+ category + '&pcount='+ pcount + '&icount='+ icount;
// AJAX Code To Submit Form.
jQuery.ajax({
type: "POST",
url: "<?php echo Mage::getBaseUrl(); ?>productlikecount/productslike/getproducts/",
data: dataString,
cache: false,
success: function(result){
	pcount = pcount +1;
	icount = icount +9;
	jQuery("#pcount").val(pcount);
	jQuery("#icount").val(icount);
	jQuery("#loading").hide();
jQuery("#list001").append(result);
}
});

});

		
		</script>

</div>
<?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription();?>
               </div><!--row--> 

			   </div><!--main container-->  
</div><!--main-container col2-right-layout-->

                 <!-- Logo Brand Block -->
      <?php if(($get_current_layout=='custom_static_page_one')) { ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_logo_brand_block')->toHtml() ?>
      <?php } ?>
      <?php if(($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_logo_brand2_block')->toHtml() ?> 
      <?php } ?>   


        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
  </div> <!--page-->

<!-- Mobile Menu-->
  <?php if(($get_current_layout!='custom_static_page_four')) { ?> <!-- Exclude from version 4 -->
      <div id="mobile-menu" >     
        <ul class="mobile-menu">
          <li><?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini-mob.phtml')->toHtml() ; ?></li>
            <?php echo $this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top_nav_mob.phtml')->toHtml() ; ?>
        </ul> <!--mobile-menu-->

        <?php if(($get_current_layout=='custom_static_page_three')) { ?> 
          <div class="top-links">
            <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude from version 5 -->
            <div class="lang-curr">
              <?php echo $this->getChildHtml('store_language') ?>     
              <?php echo $this->getChildHtml('custom_currency_selector') ?>
            </div><!--lang-curr-->
            <?php } ?> <!-- Exclude from version 5 -->
            <ul class="links">
              <li><a href="<?php echo $this->getUrl('')?>customer/account/" title="<?php echo $this->__('My Account') ?>"><?php echo $this->__('My Account') ?></a></li>
              <li><a href="<?php echo $this->getUrl('wishlist') ?>" title="<?php echo $this->__('Wishlist') ?>"><?php echo $this->__('Wishlist') ?></a></li>
              <?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1) { ?>
                <li><a href="<?php echo $this->getUrl('')?>onestepcheckout/" title="<?php echo $this->__('Checkout') ?>"><?php echo $this->__('Checkout') ?></a></li>
              <?php } else { ?>
                <li><a href="<?php echo $this->getUrl('')?>checkout/onepage/" title="<?php echo $this->__('Checkout') ?>"><?php echo $this->__('Checkout') ?></a></li>
              <?php } ?>
              <li><a href="<?php echo $this->getUrl('')?>blog" title="<?php echo $this->__('Blog') ?>"><span><?php echo $this->__('Blog') ?></span></a></li>
              <?php if(!Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li class="last"><a href="<?php echo $this->getUrl('')."customer/account/login/"; ?>" title="<?php echo $this->__('Log In') ?>"><span><?php echo $this->__('Log In') ?></span></a></li>
              <?php } ?>
              <?php if(Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li class="last"><a href="<?php echo $this->getUrl('')."customer/account/logout/"; ?>" title="<?php echo $this->__('Log Out') ?>"><span><?php echo $this->__('Log Out') ?></span></a></li>
              <?php } ?>
            </ul>
          </div><!--top-links-->
        <?php } ?>

      </div> <!--mobile-menu-->
     <?php } ?> <!-- Exclude from version 4 -->
      
</body>
</html>