<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_one')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu1.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_two')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min2.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu2.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common2.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_three')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu3.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common3.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_four')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min4.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal4.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common4.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_five')) { ?>     
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu5.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common5.js" type="text/javascript"></script>
<?php } ?>

</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
  <div id="page">
       <?php echo $this->getChildHtml('after_body_start') ?>

       <?php echo $this->getChildHtml('global_notices') ?>      
      
      <?php echo $this->getChildHtml('header') ?>

       <?php echo $this->getChildHtml('breadcrumbs') ?> 
           <!-- BEGIN Main Container col2-right --> 
            <div class="main-container col2-right-layout">
              <div class="main container">
                <div class="row">
                  <div class="col-main col-sm-12 wow bounceInUp animated">
              <?php echo $this->getChildHtml('global_messages') ?>
             <?php // echo $this->getChildHtml('content') ?>    
                     <div class="container">
                     <?php 
					 echo 'adsad';
					$categoryLink = Mage::getModel("catalog/category")->load(49)->getUrl();
$pos = strpos($categoryLink, '?');
 echo $categoryLink = ($pos>0) ? substr($categoryLink, 0, $pos) : $categoryLink; ?>
  
 
<div class="home-menu01">
<ul>
<li><a href="#">HOME</a></li>
<li><a class="active" href="#">BEDROOM</a></li>
<li><a href="#">LIVING</a></li>
<li><a href="#">DINING</a></li>
<li><a href="#">KITCHEN</a></li>
<li><a class="full01" href="#">FULL HOME PACKAGE</a></li>
</ul>
</div>
 <?php     $category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$category = Mage::getModel('catalog/category')->load($category_id);
$products = Mage::getModel('catalog/product')
    ->getCollection()
    ->addAttributeToSelect('*')
    ->addCategoryFilter($category)
    ->setOrder('price', 'ASC')
    ->load(); ?>  
      </div>
         <?php $i=1; foreach($products as $product_data) {?>  
      <?php 
		$productMediaConfig = Mage::getModel('catalog/product_media_config');

 $baseImageUrl = $productMediaConfig->getMediaUrl($product_data->getImage());
		 $bundled_product = new Mage_Catalog_Model_Product();		
	$bundled_product->load($product_data->getId());
 
 
	$selectionCollection = $bundled_product->getTypeInstance(true)->getSelectionsCollection(
		$bundled_product->getTypeInstance(true)->getOptionsIds($bundled_product),
		 $bundled_product
	);
 
	$bundled_items = array();
	foreach($selectionCollection as $option) 
	{
		$bundled_items[] = $option->product_id;
	}
	
	
	 ?>
       <div class="land01">
<div class="row">
<div class="col-md-8 col-sm-8 col-xs-12">
<div class="land01_img"><img alt="" src="<?php echo $baseImageUrl; ?>" /></div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="land01_detail">
<div class="heard"><img alt="" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/hart_1.png" /> <img alt="" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/heart.png" /><?php 
echo $reviewsCount = Mage::getModel('review/review')->getTotalReviews($product_data->getId(), true, Mage::app()->getStore()->getId());

?></div>
<ul>
<li><h2>Look Includes</h2></li>
<?php foreach($bundled_items as $bundled_item) { 
$product_load = Mage::getModel('catalog/product')->load($bundled_item);
?>
<li><?php echo $product_load->getName(); ?> : <span><?php echo  Mage::helper('core')->currency($product_load->getFinalPrice(), true, false); ?> /-</span></li>

<?php } ?>
</ul>
<a id="open_55592391" data-popup-ordinal="1" href="#fadeandscaledesigner<?php echo $i; ?>" class="fadeandscaledesigner<?php echo $i; ?>_open"><div class="des09">Consult Designer</div></a>
<div class="share">Share This Look
<div class="social">      
       <ul class="link">

					<li class="fb">
	<a href="http://www.facebook.com/share.php?u=<?php echo $product_data->getProductUrl(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				
			</a>
			</li>

				<li class="tw">
			<a href="http://twitter.com/home?status=<?php echo $product_data->getProductUrl(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				
			</a>
			</li>

				<li class="pintrest">
<a href="http://pinterest.com/pin/create/link/?url=<?php echo $product_data->getProductUrl(); ?>&media=<?php echo  $baseImageUrl; ?>&description=<?php echo $product_data->getDescription(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;"></a>
			</li>

		<li class="googleplus">
			<a href="https://plus.google.com/share?url=<?php echo $product_data->getProductUrl(); ?>" rel="nofollow" target="_blank" style="text-decoration:none;">
				
			</a>
			</li>

	</ul>
	</div>
</div>
</div>
</div>
</div>
</div>

       <!-- Fade & scale -->
<div id="fadeandscaledesigner<?php echo $i; ?>" class="well"><a class="fadeandscaledesigner<?php echo $i; ?>_close close02">X</a>
<div class="bookdesigner">
<h1>Consult Designer</h1>
<div class="pop-field">
<div class="pop-field2"><input id="options_9_text" class="field00_9" title="name" type="text" placeholder="name*" required value="" name="options[9]" /> <input id="options_11_text" class="field00_11" title="contact" type="text" placeholder="contact*" required value="" name="options[11]" /> <input id="options_12_text" class="field00_12" title="email" type="text" placeholder="email*" required value="" name="options[12]" /> <textarea id="options_14_text" class="field004" title="Tell us anything else you want exclusively for you, we would love to design it for you...." name="options[14]" placeholder="Describe your interior design project" required rows="5" cols="25"></textarea> <input id="options_9_text" class="field00_9_1" title="name" type="text" placeholder="Property Name" required value="" name="options[9]" /><select class="field00_9_2">
<option value="volvo">Select City</option>
<option value="volvo">Delhi</option>
<option value="saab">Noida</option>
<option value="opel">Greater Noida</option>
<option value="audi">Ghaziabad</option>
<option value="audi">Faridabad</option>
<option value="audi">Gurgaon</option>
</select></div>
<button class="button pop-submit" title="Submit" type="submit"><span><span>Submit</span></span></button></div>
</div>
</div>
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function () {

    jQuery('#fadeandscaledesigner<?php echo $i; ?>').popup({
        pagecontainer: '.container',
        transition: 'all 0.3s'
    });

});
// ]]></script>
<style><!--
#fadeandscaledesigner<?php echo $i; ?> {
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
			  width: 400px;
}
.popup_visible #fadeandscaledesigner<?php echo $i; ?> {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
}
--></style>  
        
     
         <?php 
		 $i++;
		 }
		 
		 // loop end ?>  



</div>

               </div><!--row--> 
              </div><!--main container-->        
            </div><!--main-container col2-right-layout-->

                 <!-- Logo Brand Block -->
      <?php if(($get_current_layout=='custom_static_page_one')) { ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_logo_brand_block')->toHtml() ?>
      <?php } ?>
      <?php if(($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_logo_brand2_block')->toHtml() ?> 
      <?php } ?>   


        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
  </div> <!--page-->

<!-- Mobile Menu-->
  <?php if(($get_current_layout!='custom_static_page_four')) { ?> <!-- Exclude from version 4 -->
      <div id="mobile-menu" >     
        <ul class="mobile-menu">
          <li><?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini-mob.phtml')->toHtml() ; ?></li>
            <?php echo $this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top_nav_mob.phtml')->toHtml() ; ?>
        </ul> <!--mobile-menu-->

        <?php if(($get_current_layout=='custom_static_page_three')) { ?> 
          <div class="top-links">
            <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude from version 5 -->
            <div class="lang-curr">
              <?php echo $this->getChildHtml('store_language') ?>     
              <?php echo $this->getChildHtml('custom_currency_selector') ?>
            </div><!--lang-curr-->
            <?php } ?> <!-- Exclude from version 5 -->
            <ul class="links">
              <li><a href="<?php echo $this->getUrl('')?>customer/account/" title="<?php echo $this->__('My Account') ?>"><?php echo $this->__('My Account') ?></a></li>
              <li><a href="<?php echo $this->getUrl('wishlist') ?>" title="<?php echo $this->__('Wishlist') ?>"><?php echo $this->__('Wishlist') ?></a></li>
              <?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1) { ?>
                <li><a href="<?php echo $this->getUrl('')?>onestepcheckout/" title="<?php echo $this->__('Checkout') ?>"><?php echo $this->__('Checkout') ?></a></li>
              <?php } else { ?>
                <li><a href="<?php echo $this->getUrl('')?>checkout/onepage/" title="<?php echo $this->__('Checkout') ?>"><?php echo $this->__('Checkout') ?></a></li>
              <?php } ?>
              <li><a href="<?php echo $this->getUrl('')?>blog" title="<?php echo $this->__('Blog') ?>"><span><?php echo $this->__('Blog') ?></span></a></li>
              <?php if(!Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li class="last"><a href="<?php echo $this->getUrl('')."customer/account/login/"; ?>" title="<?php echo $this->__('Log In') ?>"><span><?php echo $this->__('Log In') ?></span></a></li>
              <?php } ?>
              <?php if(Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li class="last"><a href="<?php echo $this->getUrl('')."customer/account/logout/"; ?>" title="<?php echo $this->__('Log Out') ?>"><span><?php echo $this->__('Log Out') ?></span></a></li>
              <?php } ?>
            </ul>
          </div><!--top-links-->
        <?php } ?>

      </div> <!--mobile-menu-->
     <?php } ?> <!-- Exclude from version 4 -->
      
</body>
</html>