<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_one')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu1.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_two')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min2.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu2.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common2.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_three')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu3.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common3.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_four')) { ?>  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min4.css" type="text/css" /> 
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal4.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common4.js" type="text/javascript"></script>
<?php } ?>

<?php if(($get_current_layout=='custom_static_page_five')) { ?>     
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/internal5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu5.css" type="text/css" />
   <script src="<?php echo $this->getSkinUrl(); ?>js/common5.js" type="text/javascript"></script>
<?php } ?>

</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
  <div id="page">
       <?php echo $this->getChildHtml('after_body_start') ?>

       <?php echo $this->getChildHtml('global_notices') ?>      
      
      <?php echo $this->getChildHtml('header') ?>

       <?php echo $this->getChildHtml('breadcrumbs') ?> 
	   <div class="page-title">
			<h1><?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getName();?></h1>
		</div>
           <!-- BEGIN Main Container col2-right --> 
            <div class="main-container col2-right-layout">
              <div class="main container">
                <div class="row">
                  <div class="col-main col-sm-12 wow bounceInUp animated">
              <?php echo $this->getChildHtml('global_messages') ?>
             <?php // echo $this->getChildHtml('content') ?>    
                     <div class="container">
               
               <p>

<script type="text/javascript" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/js/jquery.easing.min.js"></script>
<script type="text/javascript" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/js/jquery.mixitup.min.js"></script>
<script type="text/javascript">// <![CDATA[
jQuery(function () {
		
		var filterList = {
		
			init: function () {
			
				// MixItUp plugin
				// http://mixitup.io
				jQuery('#portfoliolist').mixitup({
					targetSelector: '.portfolio',
					filterSelector: '.filter',
					effects: ['fade'],
					easing: 'snap',
					// call the hover effect
					onMixEnd: filterList.hoverEffect()
				});				
			
			},
			
			hoverEffect: function () {
			
				// Simple parallax effect
				jQuery('#portfoliolist .portfolio').hover(
					function () {
						jQuery(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
						jQuery(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');				
					},
					function () {
						jQuery(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
						jQuery(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');								
					}		
				);				
			
			}

		};
		
		// Run the show!
		filterList.init();
		
		
	});
// ]]></script>
</p>
<div class="container">
  <?php     $category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$category = Mage::getModel('catalog/category')->load($category_id);
$products = Mage::getModel('catalog/product')
    ->getCollection()
    ->addAttributeToSelect('*')
    ->addCategoryFilter($category)
    ->setOrder('price', 'ASC')
    ->load(); 
	 $category_name = Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription();
	 ?>  
     
     
<div class="full_home_menu">
<ul>
<li><a <?php if($category_name == '2 BHK'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>full-packages-two-bhk.html">2 BHK I <span>730 sqft</span></a></li>
<li><a <?php if($category_name == '3 BHK'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>full-packages-three-bhk.html">3 BHK I <span>1200 sqft</span></a></li>
<li><a <?php if($category_name == '4 BHK'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>full-packages-four-bhk.html">4 BHK I <span>1680 sqft</span></a></li>
<li><a <?php if($category_name == 'VILLA'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>full-packages-villa.html">VILLA I <span>4500 sqft</span></a></li>
<li><a <?php if($category_name == 'Penthouse'){ ?>  class="active" <?php } ?> href="<?php echo Mage::getBaseUrl(); ?>full-packages-penthouse.html">Penthouse I <span>4000 sqft</span></a></li>
</ul>
</div>
<div class="full_home_slider">
<div id="caption-slide" class="slider-container">
<div class="slider">

  <?php $i=1; foreach($products as $product_data) {  $productType = $product_data->getTypeId();  if($productType =='bundle') {
	  ?>  
      <?php 
		$productMediaConfig = Mage::getModel('catalog/product_media_config');

 $baseImageUrl = $productMediaConfig->getMediaUrl($product_data->getImage());
		 $bundled_product = new Mage_Catalog_Model_Product();		
	$bundled_product->load($product_data->getId());
 
 

	$selectionCollection = $bundled_product->getTypeInstance(true)->getSelectionsCollection(
		$bundled_product->getTypeInstance(true)->getOptionsIds($bundled_product),
		 $bundled_product
	);
 
	$bundled_items = array();
	foreach($selectionCollection as $option) 
	{
		$bundled_items[] = $option->product_id;
	}
	
	
	 ?>
<!--start slide here-->
<div class="slide">
<img alt="" src="<?php echo $baseImageUrl; ?>" />
<div class="full_home_slider_text">
<div class="full_home_slider_left1">
<h2>This Package Include</h2>
<ul>
<?php $price=0;
foreach($bundled_items as $bundled_item) { 
$product_load = Mage::getModel('catalog/product')->load($bundled_item);
 $price = $product_load->getFinalPrice() +  $price;
?>
<li><?php echo $product_load->getName(); ?> :&nbsp; <span><?php echo  Mage::helper('core')->currency($product_load->getFinalPrice(), true, false); ?> /-</span>
</li>

<?php  } ?>
</ul>
</div>
<div class="full_home_slider_right1">Total Price<br /><span><?php echo  Mage::helper('core')->currency($price, true, false); ?>/-</span><br />
<a href="#fadeandscaledesigner" class="fadeandscaledesigner_open des09">Consult Designer</a>
</div>
</div>
</div>
 
<!-- end slide here-->
<?php  $i++; } 

 
  }?>
</div>
 <!--end slider here-->
<div id="prev" class="switch"><img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/prev.png" /></div>
<div id="next" class="switch"><img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/next.png" /></div>
</div>
</div>
<div class="full_heading">
<h2>THIS PACKAGE INCLUDE</h2>
<h3>THIS PACKAGE INCLUDE</h3>
</div>
<div class="main_filter">

<!-- get cat --> 
<ul id="filters" class="clearfix">
<li><span class="filter active" data-filter="<?php
    $currentCat = Mage::registry('current_category');

    if ( $currentCat->getParentId() == Mage::app()->getStore()->getRootCategoryId() )
    {
        // current category is a toplevel category
        $loadCategory = $currentCat;
    }
    else
    {
        // current category is a sub-(or subsub-, etc...)category of a toplevel category
        // load the parent category of the current category
        $loadCategory = Mage::getModel('catalog/category')->load($currentCat->getParentId());
    }
    $subCategories = explode(',', $loadCategory->getChildren());

    foreach ( $subCategories as $subCategoryId )
    {
        $cat = Mage::getModel('catalog/category')->load($subCategoryId);

        if($cat->getIsActive())
        {
            echo $cat->getUrlKey().' ';
        }
    }
?>"><div class="all01">&nbsp;</div>ALL</span></li>
<?php
    $currentCat = Mage::registry('current_category');

    if ( $currentCat->getParentId() == Mage::app()->getStore()->getRootCategoryId() )
    {
        // current category is a toplevel category
        $loadCategory = $currentCat;
    }
    else
    {
        // current category is a sub-(or subsub-, etc...)category of a toplevel category
        // load the parent category of the current category
        $loadCategory = Mage::getModel('catalog/category')->load($currentCat->getParentId());
    }
    $subCategories = explode(',', $loadCategory->getChildren());

    foreach ( $subCategories as $subCategoryId )
    {
        $cat = Mage::getModel('catalog/category')->load($subCategoryId);

        if($cat->getIsActive())
        { ?>
                   
		<li><span class="filter active" data-filter="<?php echo $cat->getUrlKey() ?>"><div class="<?php echo $cat->getUrlKey() ?>">&nbsp;</div><?php echo $cat->getName() ?></span></li>
		<?php } ?>
 <?php   }
?>

</ul>
<!-- get cat --> 

<!-- static filter -->
<!--
<ul id="filters" class="clearfix">
<li>
<span class="filter active" data-filter="living bedroom dining kids study-room wardrobe"><div class="all01">&nbsp;</div>All</span></li>
<li>
<span class="filter" data-filter="living"><div class="living">&nbsp;</div>Living</span></li>
<li>
<span class="filter" data-filter="bedroom"><div class="bedroom">&nbsp;</div>Bedroom</span></li>
<li>
<span class="filter" data-filter="dining"><div class="dining">&nbsp;</div>Dining</span></li>
<li>
<span class="filter" data-filter="kids"><div class="kids">&nbsp;</div>Kids</span></li>
<li>
<span class="filter" data-filter="study-room"><div class="study-room">&nbsp;</div>Study room</span></li>
<li>
<span class="filter" data-filter="wardrobe"><div class="wardrobe">&nbsp;</div>Wardrobe</span></li>
</ul>
-->
<div id="portfoliolist">


<?php 
			
                   
					
$products_bottom = Mage::getModel('catalog/product')
    ->getCollection()
    ->addAttributeToSelect('*')
    ->addCategoryFilter($category)
    ->setOrder('price', 'ASC')
    ->load(); 

foreach($products_bottom as $product_single){ 
	$productMediaConfig2 = Mage::getModel('catalog/product_media_config');

 $baseImageUrl2 = $productMediaConfig2->getMediaUrl($product_single->getImage());
 
  $productType = $product_single->getTypeId();  if($productType =='simple') {
?>

<!--product start here-->

<div class="portfolio <?php
			$get_categories = $product_single->getCategoryIds();
			unset($get_categories[0]);

 
foreach ($get_categories as $categories_id) {
$_category = Mage::getModel('catalog/category')->load($categories_id);
    
          echo $_category->getUrlKey().' ';
     
}
?>" data-cat="<?php  $get_categories = $product_single->getCategoryIds(); 
unset($get_categories[0]);


foreach ($get_categories as $categories_id) {
$_category = Mage::getModel('catalog/category')->load($categories_id);
    
          echo $_category->getUrlKey().' ';
     
}?>">
<div class="portfolio-wrLivinger"><img alt="" src="<?php echo  $baseImageUrl2; ?>" />
<div class="label">
<div class="label-text"><a class="text-title"><?php echo $product_single->getName(); ?></a></div>
<div class="label-bg">&nbsp;</div>
</div>
</div>
</div>
<?php } } ?>



<!--product end here-->

</div>
</div>
<div class="interior2">
<h4>BOOK FREE CONSULTATION</h4>
<div class="inter-book">
<h3>The consultation fee is absolutely free and there are no hidden charges</h3>
<script type="text/javascript">// <![CDATA[
function validateOptionsCallback(elmId, result)
					{
				        var container = $(elmId).up('ul.options-list');
				        if (result == 'failed') {
				            container.removeClassName('validation-passed');
				            container.addClassName('validation-failed');
				        } else {
				            container.removeClassName('validation-failed');
				            container.addClassName('validation-passed');
				        }
				    }
// ]]></script>
<?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','6')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
<script type="text/javascript">// <![CDATA[
var myForm = new VarienForm('custom_form', true);
// ]]></script>
<style type="text/css"><!--
#custom_form .fieldset, #custom_form .form-list {background-color: }
--></style>
<!--if(count($currentFormFieldsCollection))--> <!--if(isset($currentForm))--></div>
</div>
<div class="vik"> 
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Accordion_FDC')->toHtml();?>
<?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription(); ?>
</div>
</div>
               
                </div>
                </div>
               </div><!--row--> 
              </div><!--main container-->        
            </div><!--main-container col2-right-layout-->

                 <!-- Logo Brand Block -->
      <?php if(($get_current_layout=='custom_static_page_one')) { ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_logo_brand_block')->toHtml() ?>
      <?php } ?>
      <?php if(($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_logo_brand2_block')->toHtml() ?> 
      <?php } ?>   


        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
  </div> <!--page-->

<!-- Mobile Menu-->
  <?php if(($get_current_layout!='custom_static_page_four')) { ?> <!-- Exclude from version 4 -->
      <div id="mobile-menu" >     
        <ul class="mobile-menu">
          <li><?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini-mob.phtml')->toHtml() ; ?></li>
            <?php echo $this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top_nav_mob.phtml')->toHtml() ; ?>
        </ul> <!--mobile-menu-->

        <?php if(($get_current_layout=='custom_static_page_three')) { ?> 
          <div class="top-links">
            <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude from version 5 -->
            <div class="lang-curr">
              <?php echo $this->getChildHtml('store_language') ?>     
              <?php echo $this->getChildHtml('custom_currency_selector') ?>
            </div><!--lang-curr-->
            <?php } ?> <!-- Exclude from version 5 -->
            <ul class="links">
              <li><a href="<?php echo $this->getUrl('')?>customer/account/" title="<?php echo $this->__('My Account') ?>"><?php echo $this->__('My Account') ?></a></li>
              <li><a href="<?php echo $this->getUrl('wishlist') ?>" title="<?php echo $this->__('Wishlist') ?>"><?php echo $this->__('Wishlist') ?></a></li>
              <?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1) { ?>
                <li><a href="<?php echo $this->getUrl('')?>onestepcheckout/" title="<?php echo $this->__('Checkout') ?>"><?php echo $this->__('Checkout') ?></a></li>
              <?php } else { ?>
                <li><a href="<?php echo $this->getUrl('')?>checkout/onepage/" title="<?php echo $this->__('Checkout') ?>"><?php echo $this->__('Checkout') ?></a></li>
              <?php } ?>
              <li><a href="<?php echo $this->getUrl('')?>blog" title="<?php echo $this->__('Blog') ?>"><span><?php echo $this->__('Blog') ?></span></a></li>
              <?php if(!Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li class="last"><a href="<?php echo $this->getUrl('')."customer/account/login/"; ?>" title="<?php echo $this->__('Log In') ?>"><span><?php echo $this->__('Log In') ?></span></a></li>
              <?php } ?>
              <?php if(Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li class="last"><a href="<?php echo $this->getUrl('')."customer/account/logout/"; ?>" title="<?php echo $this->__('Log Out') ?>"><span><?php echo $this->__('Log Out') ?></span></a></li>
              <?php } ?>
            </ul>
          </div><!--top-links-->
        <?php } ?>

      </div> <!--mobile-menu-->
     <?php } ?> <!-- Exclude from version 4 -->
	 
	 
	 
	 <div id="fadeandscaledesigner" class="well">
		<a href="" class="fadeandscaledesigner_close close02">X</a>
		<div class="col-md-5 col-sm-12 col-xs-12">
			<div class="pop-img1">
				<div class="register007">
					<ul>
						<li><img alt="Kit Price" src="<?php echo $this->getSkinUrl('kit-price.png'); ?>" /> <span>Starting from  <B>Rs 1,00,000</B></span></li>
						<li><img alt="Cupen 4" src="<?php echo $this->getSkinUrl('cupen4.png'); ?>" /> <span>10 years <B>WARRANTY</B></span></li>
						<li><img alt="Kit Delivery" src="<?php echo $this->getSkinUrl('kit-delivery.png'); ?>" /> <span><b>30 days </b> delivery</span></li>
						<li><img alt="Cupen 3" src="<?php echo $this->getSkinUrl('cupen3.png'); ?>" /> <span>Free <b>INSTALLATION</b></span></li>
					</ul>
				</div>
				<img src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/register-popup.png" alt="Register" class="register-img">
			</div>
		</div>

	<div class="col-md-7 col-sm-12 col-xs-12">
		<?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','7')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
	</div>
		
	</div>

<script>
jQuery(document).ready(function () {

    jQuery('#fadeandscaledesigner').popup({
        pagecontainer: '.container',
        transition: 'all 0.3s'
    });

});
</script>

<style>
#fadeandscaledesigner {
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
}
.popup_visible #fadeandscaledesigner {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
}
</style>
   
  
      
</body>
</html>
