<div class="container">
<div class="slider-items-products">
<div class="new_title center">
<h2>&nbsp;<br />DESIGN YOUR HOME </h2>
<h3>Complete Furniture for your home</h3>
</div>
</div>


<div class="container clearfix">
<ul class="banner-images"  id="box"> 

<a href="http://www.yagotimber.com/full-packages-two-bhk.html"><li class="grid right-space margin-banner ">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Interior Design for 2BHK " src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/home2bhk.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-three-bhk.html"><li class="grid right-space margin-banner ">
<figure class="effect " style="visibility: visible;"><div class="wrapper"><img alt="Interior Design for 3BHK "  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/home3bhk.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-four-bhk.html"><li class="grid margin-banner ">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Interior Design for 4BHK "  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/home4bhk.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-villa.html"><li class="grid two-width right-space">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image4"  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago4.gif" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homevilla.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-penthouse.html"><li class="grid  two-height space011">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image5"  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepenthouse.jpg" /></div><figcaption>
</figcaption></figure>
</li></a>

</ul>
<div class="line01">&nbsp;</div>



</div>
<div class="fulltime" id="box">
<h5><br /><br />DESIGN IDEAS</h5>
<h2>EXQUISITE PRE-DESIGNED LOOKS</h2>
<div class="tabbs"><!-- Nav tabs -->
<ul class="nav nav-tabs1" role="tablist">
<li role="presentation"></li>
<li class="active" role="presentation"><a role="tab" href="#tab2" data-toggle="tab">BEDROOM</a></li>
<li role="presentation"><a role="tab" href="#tab3" data-toggle="tab">LIVING</a></li>
<li role="presentation"><a role="tab" href="#tab4" data-toggle="tab">DINING</a></li>
<li role="presentation"><a role="tab" href="#tab5" data-toggle="tab">KITCHEN</a></li>
<li role="presentation" class="highlight2"><a href="http://www.yagotimber.com/full-packages-two-bhk.html" class="highlight1">FULL HOME PACKAGES</a></li>
</ul>
<!-- Tab panes -->
<div class="tab-content1">
<div id="tab1" class="tab-pane" role="tabpanel">&nbsp;</div>
<div id="tab2" class="tab-pane active" role="tabpanel">
<div class="homelook01">
<div class="homelook01_img"><img alt=""  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago2.gif"   data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/home_look_01.jpg" />
<div class="homelook01_detail">Bedroom &nbsp; I &nbsp; Starting From <span>Rs.65,000</span> <a href="http://www.yagotimber.com/home-look-bedroom.html">EXPLORE MORE BEDROOM LOOKS</a></div>
</div>
<div class="homelook02_detail">
<div class="homelook02_left">
<h2>This look contains</h2>
<ul>
<li>Storage Bed : <span>Rs.35,000</span></li>
<li>Side Table : <span>Rs.8,000</span></li>
<li>Chest : <span>Rs.22,000</span></li>
</ul>
</div>
<div class="homelook02_right">All looks are customizable as per your requirement and taste. Simply book a free consultation and our designer will help you with all your home designing needs. <br /><a class="fadeandscaledesigner_open" href="#fadeandscaledesigner">Book free design consultation</a></div>
</div>
</div>
</div>
<div id="tab3" class="tab-pane" role="tabpanel">
<div class="homelook01">
<div class="homelook01_img"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/home_look_02.jpg" />
<div class="homelook01_detail">Living Room &nbsp; I &nbsp; Starting From <span>Rs.1,10,000</span> <a href="http://www.yagotimber.com/home-look-living.html">EXPLORE MORE LIVING LOOKS</a></div>
</div>
<div class="homelook02_detail">
<div class="homelook02_left">
<h2>This look contains</h2>
<ul>
<li>Sofa : <span>Rs.35,000</span></li>
<li>TV Cabinet : <span>Rs.30,000</span></li>
<li>Center Table : <span>Rs.15,000</span></li>
<li>Display Unit : <span>Rs.30,000</span></li>
<li><span class="emi_home">EMI</span> Available on 0% interest</li>
</ul>
</div>
<div class="homelook02_right">All looks are customizable as per your requirement and taste. Simply book a free consultation and our designer will help you with all your home designing needs.<br /><a class="fadeandscaledesigner_open" href="#fadeandscaledesigner">Book free design consultation</a></div>
</div>
</div>
</div>
<div id="tab4" class="tab-pane" role="tabpanel">
<div class="homelook01">
<div class="homelook01_img"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/home_look_03.jpg" />
<div class="homelook01_detail">Dining Room &nbsp; I &nbsp; Starting From <span>Rs.1,00,000</span> <a href="http://www.yagotimber.com/home-look-dining.html">EXPLORE MORE DINING LOOKS</a></div>
</div>
<div class="homelook02_detail">
<div class="homelook02_left">
<h2>This look contains</h2>
<ul>
<li>Dining Table : <span>Rs.35,000</span></li>
<li>Sofa : <span>Rs.30,000</span></li>
<li><span class="emi_home">EMI</span> Available on 0% interest</li>
</ul>
</div>
<div class="homelook02_right">All looks are customizable as per your requirement and taste. Simply book a free consultation and our designer will help you with all your home designing needs. <br /><a class="fadeandscaledesigner_open" href="#fadeandscaledesigner">Book free design consultation</a></div>
</div>
</div>
</div>
<div id="tab5" class="tab-pane" role="tabpanel">
<div class="homelook01">
<div class="homelook01_img"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/home_kitchen01.jpg" />
<div class="homelook01_detail">Modular Kitchen &nbsp; I &nbsp; Starting From <span>Rs.80,000</span> <a href="http://www.yagotimber.com/home-look-kitchen.html">EXPLORE MORE KITCHEN LOOKS</a></div>
</div>
<div class="homelook02_detail">
<div class="homelook02_left">
<h2>This look contains</h2>
<ul>
<li>10 year warranty</span></li>
<li>Wide range of designs</span></li>
<li>Fully customized offering </span></li>
<li><span class="emi_home">EMI</span> Available on 0% interest</li>
</ul>
</div>
<div class="homelook02_right">All looks are customizable as per your requirement and taste. Simply book a free consultation and our designer will help you with all your home designing needs. <br /><a class="fadeandscaledesigner_open" href="#fadeandscaledesigner">Book free design consultation</a></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- Fade & scale -->
<div id="fadeandscaledesigner" class="well"><a class="fadeandscaledesigner_close close02">X</a>
<div class="col-md-5 col-sm-5 col-xs-12">
<div class="pop-img1">
<div class="register007">
<ul>
<li><img alt="Kit Price"  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo $this->getSkinUrl('kit-price.png'); ?>" /> <span>Starting from  <B>Rs 1,00,000</B></span></li>
<li><img alt="Cupen 4" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif"  data-src="<?php echo $this->getSkinUrl('cupen4.png'); ?>" /> <span>10 years <B>WARRANTY</B></span></li>
<li><img alt="Kit Delivery" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif" data-src="<?php echo $this->getSkinUrl('kit-delivery.png'); ?>" /> <span><b>30 days </b> delivery</span></li>
<li><img alt="Cupen 3" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif"  data-src="<?php echo $this->getSkinUrl('cupen3.png'); ?>" /> <span>Free <b>INSTALLATION</b></span></li>
</ul>
</div>
<img class="register-img" alt="Register"  src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>loading_yago.gif"  data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/register-popup.png" /></div>
</div>
<div class="col-md-7 col-sm-7 col-xs-12">
<div class="bookdesigner">
<div class="col-md-12 col-sm-7 col-xs-12">
<?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','7')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>
</div>
</div>
</div>
</div>
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function () {

    jQuery('#fadeandscaledesigner').popup({
        pagecontainer: '.container',
        transition: 'all 0.3s'
    });

});
// ]]></script>
<style><!--
#fadeandscaledesigner {
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
}
.popup_visible #fadeandscaledesigner {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
}
--></style>
<script type="text/javascript" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/js/jquery.scrolling-tabs.js"></script>
<script type="text/javascript">// <![CDATA[
jQuery('.nav-tabs1').scrollingTabs();
// ]]></script>
