<p>&nbsp;</p>
<div class="container">
<div class="mod_kitchen01"><a href="#section1" class="active_mod">Home</a> <a href="#section2">Why Yago</a> <a href="#section3">Quality</a> <a href="#section4">Kitchen</a> <a href="#section5">Faq</a> <a href="#section6">Contact</a></div>
<div class="row tabing_md">
<div class="col-md-3 col-sm-3 col-xs-12 tabing_md_left">
<div id="tabing-1" class="tabing modactive"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/lshape_icon.png" /> L Shaped</div>
<div id="tabing-2" class="tabing"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/ushape_icon.png" /> U Shaped</div>
<div id="tabing-3" class="tabing"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/pshape_icon.png" /> Parallel</div>
<div id="tabing-4" class="tabing"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/ishape_icon.png" /> Island &nbsp; &nbsp;</div>
<div id="tabing-5" class="tabing"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_stardt_line.png" /> Straight</div>
</div>
<div class="col-md-9 col-sm-9 col-xs-12 tabing_md_right">
<div id="tabing-load-1" class="tabing-load"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/top_mod_l_shape.jpg" /></div>
<div id="tabing-load-2" class="tabing-load"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/top_mod_u_shape.jpg" /></div>
<div id="tabing-load-3" class="tabing-load"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/top_mod_p_shape.jpg" /></div>
<div id="tabing-load-4" class="tabing-load"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/top_mod_i_shape.jpg" /></div><a name="section2"></a>
<div id="tabing-load-5" class="tabing-load"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/top_modstrl_shape.jpg" /></div>
</div>
</div>
<div class="mod_kitchen02">
<h3>Yago Your First Choice</h3>
<h2>Many reasons to love us</h2>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="mod_design"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon01.png" />
<h2>Customized modular kitchen</h2>
<p>All the modular kitchens are designed keeping indian homes in mind.</p>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="mod_design"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon06.png" />
<h2>Unmatched quality</h2>
<p>At Yago we do not compromise with quality. You get the best.</p>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="mod_design"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon03.png" />
<h2>Lowest price guaranteed</h2>
<p>At Yago there are no middlemen therefore we can offer you the best price.</p>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="mod_design"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon04.png" />
<h2>4 weeks delivery</h2>
<p>We manufacture the modular kitchen in our production unit and deliver it in 4 weeks</p>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="mod_design"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon05.png" />
<h2>Free installation</h2>
<p>We install it for free and we make it sure your kitchen is ready to use.</p>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="mod_design"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon02.png" />
<h2>10 Years warranty</h2>
<p>We provide you with authorized warranty cards.</p>
</div>
</div>
</div>
<div class="mod_kitchen02 kitch_mobi">
<h3>Yago DESIGNS</h3>
<h2>There is something for everyone</h2>
<div id="kitchen_landing_page"><header><!--CAROUSEL HEADER TEXT--><!-- CAROUSEL-->
<div id="kitchen-landing-carousel" class="carousel slide carousel-fade" data-ride="carousel"><!-- Indicators --> <!-- Wrapper for slides -->
<div class="carousel-inner" role="listbox">&nbsp;</div>
<!-- Controls --></div>
<!-- CAROUSEL END--></header>
<div class="container">
<div class="row finishes">
<div class="finishes-img-01">
<div id="id-xm-rorate" class="xm-rorate">
<ul id="id-xm-content" class="xm-rorate-img clearfix">
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic001.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic002.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic003.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic004.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic005.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic006.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic007.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic008.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic009.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0010.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0011.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0012.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0013.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0014.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0015.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_pic0016.jpg" /></li>
</ul>
</div>
</div>
<div class="finishes-text">
<div class="finishes-text-wrap">
<div class="sm-line" style="display: block;">&nbsp;</div>
<h3>Finishes, tough and beautiful</h3>
<p>Yagotimber is an online shopping destination offering exclusive custom made &amp; ready to order furniture with the best price &amp; quality standards in the market.Yagotimber commits to offer a diverse range of products, ideas to grace your home, and unmatched customer service.</p>
<p>&nbsp;</p>
<p style="font-style: italic;">See all finishes, just hover your mouse</p>
<div class="finishes_tab"><!-- Nav tabs -->
<ul id="finishes_tab" class="nav nav-tabs" role="tablist">
</ul>
<!-- Tab panes -->
<div class="tab-content">
<div id="tab_color" class="tab-pane active" role="tabpanel">
<ul id="id-xm-control" class="xm-rorate-con clearfix">
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon001.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon002.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon003.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon004.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon005.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon006.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon007.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon008.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon009.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0010.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0011.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0012.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0013.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0014.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0015.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_icon0016.png" /></li>
<li id="id-xm-slider" class="xm-rorate-slider"></li>
</ul>
</div>
<div class="yago_gesign_exp"><a href="http://www.yagotimber.com/l-shaped-kitchen">Explore Kitchens &rarr;</a></div>
<a name="section3"></a>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="container" style="max-width: 950px;">&nbsp;</div>
</div>
</div>
<div class="mod_kitchen02">
<h3>Unmatched Quality</h3>
<h2>At yago, quality is our first preference</h2>
<div class="row tabing_md">
<div class="col-md-3 col-sm-3 col-xs-12 tabing_md_left">
<div class="mod_kit_tab1">
<ul class="tabs">
<li><a href="#">MARINE PLY</a></li>
<li><a href="#">HDF HMR</a></li>
<li><a href="#">MDF</a></li>
<li><a href="#">GLASS</a></li>
</ul>
</div>
</div>
<div class="col-md-9 col-sm-9 col-xs-12 tabing_md_right">
<div class="panes">
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/unmatched_01.jpg" /></div>
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/unmatched_02.jpg" /></div>
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/unmatched_03.jpg" /></div>
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/unmatched_04.jpg" /></div>
</div>
</div>
</div>
</div>
<div class="mod_kitchen03">
<h3>Counter top</h3>
<h2>Choose from our wide range of option</h2>
<div class="tabing_md02">
<div class="quali_modk">
<ul class="tabs5">
<li><a href="#">Granite</a></li>
<li><a href="#">Corian</a></li>
<li><a href="#">Quartz</a></li>
</ul>
</div>
<div class="tabing_md02_bottom">
<div class="panes5">
<div>
<div class="tabing_md02_bottom01"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/counter01.jpg" /></div>
</div>
<div>
<div class="tabing_md02_bottom01"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/counter02.jpg" /></div>
</div>
<div>
<div class="tabing_md02_bottom01"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/counter03.jpg" /></div>
</div>

</div>
</div>
</div>
</div>
<div class="mod_kitchen02">
<h3>Accessories and fittings</h3>
<h2>At yago, quality is our first preference</h2>
<div class="row tabing_md">
<div class="col-md-9 col-sm-9 col-xs-12 tabing_md_right">
<div class="panes1">
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/fitting_03.jpg" /></div>
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/fitting_01.jpg" /></div>
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/fitting_02.jpg" /></div>
<div><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/fitting_04.jpg" /></div>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12 tabing_md_left">
<div class="mod_kit_tab1">
<ul class="tabs1">
<li><a href="#">MODULAR</a></li>
<li><a href="#">DRAWERS</a></li>
<li><a href="#">HINGES</a></li>
<li><a href="#">WIRE BASKET</a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="mod_kitchen03">
<h3>Cabinet exterior</h3>
<h2>At yago, quality is our first preference</h2>
<div class="row tabing_md01">
<div class="col-md-3 col-sm-3 col-xs-12 tabing_md_left01">
<div class="mod_kit_tab3">
<ul class="tabs2">
<li><a href="#">HPL</a></li>
<li><a href="#">MEMBRANE</a></li>
<li><a href="#">POLYMER</a></li>
<li><a href="#">ACRYLIC</a></li>
</ul>
</div>
</div>
<div class="col-md-9 col-sm-9 col-xs-12 tabing_md_right01">
<div class="panes2">
<div>
<div class="kiten_part">
<h2>MATT</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_color01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_color02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_color03.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_color04.png" /></li>
</ul>
</div>
<div class="kiten_part">
<h2>HIGH GLOSS</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_glass01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_glass02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_glass03.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_glass04.png" /></li>
</ul>
</div>
<div class="kiten_part">
<h2>WOOD</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_wood01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_wood02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_wood03.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/hpl_wood04.png" /></li>
</ul>
</div>
</div>
<div>
<div class="mem_kitchen_part01">
<h2>MATT</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mem_wood01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mem_wood02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mem_wood03.png" /></li>
</ul>
</div>
<div class="mem_kitchen_part01">
<h2>HIGH GLASS</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mem_glass01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mem_glass02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mem_glass03.png" /></li>
</ul>
</div>
</div>
<div>
<div class="mem_kitchen_part02">
<h2>POLYMER</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/plymer01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/plymer02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/plymer03.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/plymer04.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/plymer05.png" /></li>
</ul>
</div>
</div>
<div>
<div class="mem_kitchen_part02">
<h2>ACRYLIC</h2>
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/acr01.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/acr02.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/acr03.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/acr04.png" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/acr05.png" /></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="mod_kitchen03">
<h3>Our Brands</h3>
<h2>At yago, quality is our first preference</h2>
<div class="kitchen_brand">
<ul>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_logo01.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_logo02.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_logo03.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_logo04.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_logo05.jpg" /></li>
<li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/kitchen_logo06.jpg" /></li>
</ul><a name="section4"></a>
</div>
</div>
<div class="mod_kitchen03">
<h3>Modular Kitchen</h3>
<h2>Choose from our side range of option</h2>
<div class="tabing_md02">
<div class="mod_kit_tab2">
<ul class="tabs3">
<li><a href="#">L Shaped</a></li>
<li><a href="#">U Shaped</a></li>
<li><a href="#">Parallel</a></li>
<li><a href="#">Island</a></li>
<li><a href="#">Straight</a></li>
</ul>
</div>
<div class="tabing_md02_bottom">
<div class="panes3">
<div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/l-shaped-kitchen"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_l_shape.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/l-shaped-kitchen">Explore</a></div>
</div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/l-shaped-kitchen"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_l_shape01.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/l-shaped-kitchen">Explore</a></div>
</div>
</div>
<div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/u-shaped-kitchen"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_u_shape.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/u-shaped-kitchen">Explore</a></div>
</div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/u-shaped-kitchen"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_u_shape01.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/u-shaped-kitchen">Explore</a></div>
</div>
</div>
<div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/parallel"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_p_shape.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/parallel">Explore</a></div>
</div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/parallel"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_p_shape01.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/parallel">Explore</a></div>
</div>
</div>
<div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/island"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_i_shape.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/island">Explore</a></div>
</div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/island"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_i_shape01.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/island">Explore</a></div>
</div>
</div>
<div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/straight-kitchen">
<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_p_shape.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/straight-kitchen">Explore</a></div>
</div>
<div class="tabing_md02_bottom0_left"><a href="http://www.yagotimber.com/straight-kitchen">
<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>images/kitchen_mod_p_shape01.jpg" /></a>
<div class="exp007"><a href="http://www.yagotimber.com/straight-kitchen">Explore</a></div>
</div>
</div><a name="section6"></a>
</div>
</div>
</div>
</div>
<div class="mod_kitchen02">
<h3>BOOK FREE CONSULTATION</h3>
<h2>No hidden charges, No condition apply</h2>
<div class="mod_kit_book">
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="mod_kit_book1"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_kit_icon1.png" />
<p>Fill the form or<br />simply call us</p>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="mod_kit_book1"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_kit_icon2.png" />
<p>Meet Yago<br />Designers</p>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="mod_kit_book1"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_kit_icon3.png" />
<p>Tell us your<br />Budget &amp; requirement</p>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="mod_kit_book1"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/mod_kit_icon4.png" />
<p>Leave the<br />rest on us!</p>
</div>
</div>
</div>
<div class="inter-book"><form id="custom_form" action="http://www.yagotimber.com/formbuilder/index/formsubmit/" enctype="multipart/form-data" method="post" name="custom_form">
<div class="pop-field">
<div class="pop-field2"><?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','6')->setTemplate('formbuilder/form.phtml')->toHtml(); ?></div>
</div><a name="section5"></a>
</form></div>
</div>
<div class="mod_kit_faq">
<h3>&nbsp;</h3>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Accordion_2')->toHtml();?>

<div class="why_home">
<div class="new_title center">
<h1>Your Smart Modular Kitchen with Yagotimber</h1>
</div>
<div class="why_home1">
<p class="Normal1" style="text-align: center;"><b></b></p>
<p class="Normal1">The kitchen is an intrinsic part of every house and a place where a lot of time is spent by several members of the family especially the ladies. Hence, it should be designed for convenience and functionality. Apart from this, more and more people are spending a lot of money to ensure that it's classy, stylish and contemporary. A modular kitchen combines all these aspects. Modular kitchen has revolutionized the interior designing of the house. This kitchen is not only stylish but also makes cooking easy. You can also add a fresh outlook to the style of your homes by our modular kitchen design and ideas available at our online furniture, home decor and design store, Yagotimber.com and we assure that we will give you the value for your money.</p>
<p class="Normal1">&nbsp;<b>What we provide you at Yagotimber online is worth your money!</b></p>
<p class="Normal1">Yagotimber provides you a variety of modular kitchens in segments like the L-shaped modular kitchen, U-shaped modular kitchen, Parallel modular kitchen, Island shaped modular kitchen and straight modular kitchen in an exclusive range of colors. Be it natural shades of different hues, you can surely get a kitchen according to your taste.</p>
<p class="Normal1">We believe that every client is different from one another in several ways. At Yagotimber we provide you with a complete customized solution. All the kitchens are designed keeping in mind the shape and size of the kitchen area in your apartment. Apart from that the finish, colour and texture of the kitchen are also suggested on the basis of the existing color, furniture and design of the area around the kitchen</p>
<p class="Normal1">All homemakers know the importance of a well-stored kitchen. From storing cereals to condiments, from pulses to beverages, from bakery goods to snacks items, or be it cutleries. A well organized kitchen can help in smooth working in the kitchen as it is easy to find things and use them as and when needed. Understanding your needs, we at www.yagotimber.com provide you ideas and tips by experts for your kitchen, be it small or big, which will make your kitchen well organized and smart, with sufficient storage space by using the kitchen intelligently. Our modular kitchen design includes kitchen appliances, built in technology chimneys to use it optimally, kitchen countertops, slab work and with all the accessories including the dishwasher, chimneys, cabinets, units of pull out drawers with adjustable shelves, used to store multiple utility items and utensils.</p>
<p class="Normal1">Now all these sophisticated and classy stuff designed and tested by our experts can be yours at www.yagotimber.com</p>
<p class="Normal1"><b>The Benefits of Your Dream Kitchen</b></p>
<p class="Normal1">Modular kitchen can be very advantageous. They are easy to fit, easy to clean and can be repaired easily. We provide you with ready to install pre-fabricated modular kitchen which makes installation extremely convenient and will be ready to give your kitchen a fashionable look which lens a great appeal to your interior decor. The kind of material we opt is durable and will beautify your kitchen.</p>
<p class="Normal1"><b>What Makes Yagotimber Unique?</b></p>
<p class="Normal1">At www.yagotimber.com we offer a range of fully customized modular kitchen design, ideas and tips to chose from and the price quoted are extremely genuine and affordable with a reasonable warranty period extending up to 10 years and an easy finance facility available on low interests. We use hardware of brands like hettich, caesarstone, saint gobain, hafele, century and others. We also offer you with our repair and easy returns services in case of any problems. All looks are customizable as per your requirement and taste. You can also book a consultation and our expert designers will help you with all your modular kitchen designing needs. At Yagotimber we have something unique to offer to each and every client who approaches us for a modular kitchen accessories and cabinets for their home. We design our kitchen understanding the requirement and budget of the client. Starting from Rs. 60,000 to any amount, we design lovable pocket-friendly kitchens.</p>
<p class="Normal1">Yagotimber.com is not only affordable but also the premium source to fetch you with impeccable distinction kitchenette. Its majestic grandeur is worth every penny you spend on it. You&rsquo;re just a click away to make your smart kitchen the kind you&rsquo;ve always dreamt of. Cook in style!&nbsp;</p>

<p class="Normal1">Modular kitchen is a modern and an essential trend: Kitchen is a crucial part of our homes and lives. It is a place where most of the time is spend of the members, because going to the kitchen after each half an hour is our favorite pastime. A kitchen should be designed for convenience and functionality. When people invest in such a thing like a kitchen, they ensure that it's classy, stylish and contemporary, and their money won't go in vain. Modular kitchen has revolutionized the interior decor of the house. It comprises of all the aspects which are needed to fulfill all your needs. A modular kitchen is easy to handle and we make it easy to install for your use in future aspects.&nbsp;</p>
<p class="Normal1">A modular kitchen here will be all about using the space of your kitchen intelligently. You should make sure that the kitchen is not only stylish but also it makes cooking easy. You can also add a fresh outlook to the style of your homes by our modular kitchen design and ideas.&nbsp; We have a variety of modular kitchen with alluring interior designs, furniture and all the accessories that will ever be needed for your kitchen in an exclusive range of colors be it natural shades of different hues that you can surely get according to your taste, from designs like U-shape, L-shape, G-shape, Island Style, and Straight Kitchen, Parallel Kitchen or Gallery kitchen. Following are the brief details about the kitchens.</p>
<p class="Normal1"><b>Spacious Straight Modular Kitchen</b>&nbsp;</p>
<p class="Normal1">This type of kitchens will be the most genius and masterly utilization of available space, convenience and more space for more kitchen activities will be the add-on in your straight modular kitchens. Being a good and worthy option for small spaced kitchens, it's also called single wall or one-wall kitchen. This effortless and seamless kitchen helps you use the larger appliances smartly placed under the bench top, so as to create as much space as possible so that the kitchen look spacious. It is built keeping in mind the requirements and needs of our customers&nbsp;</p>
<p class="Normal1"><b>Classy U-shaped Modular Kitchen</b>&nbsp;</p>
<p class="Normal1">If there is vast space available in your kitchen then U-shape modular kitchen is the best option for you as it covers all the three adjoining walls of the kitchen giving enough storage space and area to work around in the kitchen, with all the kitchenettes that you can ever think of. More than one person can work in this kitchen conveniently. The entire kitchen area can be divided into three zones viz. cooking zone, zone to keep all the appliances, dishwashing zone. This may help you to segregate better.&nbsp;</p>
<p class="Normal1"><b>Corner L-Shape Modular Kitchen</b></p>
<p class="Normal1">&nbsp;This corner shaped easy to handle modular kitchen appear as L-shape which occupies only two adjacent walls of the kitchen. The longer wall faces the room generally and the work decorum is maintained. The perfect installations of refrigerator, stove and sink at each point of the triangle which ensures peaceful work. This open layout helps you to segregate things better and do not make one interfere in the work of another.&nbsp;</p>
<p class="Normal1"><b>Hybrid G-Shape Modular Kitchen</b>&nbsp;</p>
<p class="Normal1">Ideal and perfect for large families, G-shape modular kitchen is the hybrid version of U-shape modular kitchen. Its unequaled utilization of space marks the personification of comfort. Build in the form the shape of alphabet &ldquo;G&rdquo; it provides extra cabinets and storage space for special appliances like in-built refrigerator, deep fryer, barbeque, etc. It is an automated sophistication.</p>
<p class="Normal1">&nbsp;<b>Appealing Island Style Modular Kitchen</b></p>
<p class="Normal1">&nbsp;Centrally focused, island style modular kitchen serves the dual purpose of adding a pleasing appeal and more counter space. A second oven, sink or dishwasher can be adding one to your kitchen to expand the functionality of the kitchen. Aside from being economical, it is also classy, stylish and luxurious.</p>
<p class="Normal1">&nbsp;<b>Parallel Modular Kitchen</b></p>
<p class="Normal1">&nbsp;If space is an issue in your kitchen, then a parallel or gallery modular kitchen can be a worthy option for your kitchen. It can be classified as one wall kept for work areas like for sink, worktop and oven and another wall for storage. Such modular kitchen ensures convenience of free movement for cooking in the kitchen.</p>
<p class="Normal1">&nbsp;All homemakers know the importance of a well-stored kitchen. From storing cereals to condiments, from pulses to beverages, from bakery goods to snacks items, or be it cutleries. A well organized and accessible kitchen can help in smooth working in the kitchen as it is easy to find things and use them as and when needed.</p>
<p class="Normal1">&nbsp;Vibrant, bold, natural and fresh color themes are in trend these days, Laminate finish comes in diverse designs and 30-40 color options to choose from in intelligently quoted prices. The laminate finish gives you a wide classic range of different texturing material for e.g.&nbsp; High-gloss, matte finishes, fabric finish, wooden texture, patterns, etc. Laminates are the most reasonable option for shutter finishes. Opting for PU Polish finish in higher segment kitchens gives the luxury look to the kitchen and they are available in different matte and hi-gloss colors. Other finishes are Acrylic finish, Membrane finish, Polyester finish etc. Following are the brief details about the materials that you can opt for your kitchen.</p>
<p class="Normal1">&nbsp;<b>Solid Wood</b></p>
<p class="Normal1">&nbsp;Solid wood, major, widely and commonly used in the decoration of modular kitchens, it is classified into two categories, softwood, and hardwood, derived from evergreen and deciduous trees respectively. Having facilities in like, base, shelves, back panel, walls or doors of modular kitchen cabinets more often real wood is preferred over other material types because it makes the material durable, reliable and offers a great finish. The sources for real wood are Sheesham, cherry, oak etc.</p>
<p class="Normal1">&nbsp;Years of hard use will also not make it weak, as it can handle any type of work traffic and still won't lose its charm and appealing look. The appeal is raw and classic and after polish, the wooden modular kitchen looks amazing and complete.</p>
<p class="Normal1">&nbsp;<b>Medium Density Fiberboard (MDF) Modular Kitchen</b></p>
<p class="Normal1">&nbsp;High pressurized engineered wood, medium density fiberboard is created using a single board which is taken out from multiple wood fibers. MDF provides a smooth texture and brings along with itself great finish and style, also it complements your taste and decor. MDF, not being as strong as other materials, is not preferred for high-density regions.</p>
<p class="Normal1">&nbsp;<b>Plywood</b></p>
<p class="Normal1">&nbsp;The use of plywood has been seen increasing in the past few years, because of its classic and alluring designs for kitchens. This engineered wood is derived from a special type of wood panel, processed and manufactured. Wood veneer is extensively used to obtain plywood. Plywood laminates give your kitchen a complete finish and opulent texture with pleasing looks.</p>
<p class="Normal1">&nbsp;<b>Stainless Steel Modular Kitchen</b></p>
<p class="Normal1">&nbsp;A stainless steel kitchen, therefore, provides a way out to help you get rid of issues such as leakage and termites and offers a long-lasting look at the same time. Stainless steel is expensive than wood and is a good conductor of electricity, thus least recommended by our experts.</p>
<p class="Normal1">&nbsp;Planning your budget accordingly and intelligently, as per required by hone home and space available can help you to take right decisions.</p>
<p class="Normal1">&nbsp;Material that you choose for your Modular kitchen should be reliable and durable as it will be the major cost factor. Smaller aspects like humidity, water leakage, heat, friction and load of the material should also be taken into consideration. For countertop, Granite can be the best option for Indian kitchen.&nbsp;&nbsp; Plywood cabinets are the cheapest option. The thickness of plywood adds further strength. Marine ply, which has water-repelling chemicals, can also be used. In a nutshell, you should keep in mind your home, the decor, and the suiting material while having a modular kitchen.</p>
<p class="Normal1">&nbsp;<b>Epic classic Modular Kitchen Finishes</b></p>
<p class="Normal1">&nbsp;Proper toning of your kitchen needs a right type of finish. You can choose from an ocean of options available for your modular kitchen finish. Let us take a look at few of them:</p>
<p class="Normal1">&nbsp;<b>Amazing Acrylic Finish</b></p>
<p class="Normal1">&nbsp;Acrylic finish is used to provide a glow to your modular kitchen. It enhances the aesthetic appeal of the kitchen. It has high durability and is not prone to damage, either caused by UV rays or moisture. The maintenance cost is low. It gives a dazzling look and can make your friends and neighbors go jealous.</p>
<p class="Normal1">&nbsp;<b>Seamless Stainless Steel Finish</b></p>
<p class="Normal1">&nbsp;Contemporary and sophisticated look along with unmatched qualities like, corrosion, stain resistant, economical, long lasting and nontoxic are some of the factors that say about stainless steel finish. It is customizable and you can also modify it, and have stainless steel finish embossed in your kitchens.</p>
<p class="Normal1">&nbsp;<b>Veneer Finish</b></p>
<p class="Normal1">&nbsp;Visually pleasing look in your kitchen can be yours if you go for a veneer finish. High on visual effects, this finish requires to be properly maintained as it is moderately resistant to factors like humidity, water, and UV rays.</p>
<p class="Normal1">&nbsp;<b>Membrane Finish</b></p>
<p class="Normal1">&nbsp;Traditionally used membrane finish is a durable as well as an economical choice. There are many factors that contribute to the widely usage of membrane finish in modular kitchens across the globe. Some of them include its smoothness, polish, resistance to water and humidity and durability. Its biggest advantage is that it can go along with both types of kitchens i.e. traditional as well as modern. All of these factors are cumulatively responsible for the wide usage of the membrane finish.</p>
<p class="Normal1">&nbsp;<b>Laminate Finish</b></p>
<p class="Normal1">&nbsp;It offers an ideal finish for your modular kitchen, Laminate finish, is considered to be superior to others in terms of its unequaled natural yet contemporary looks. It is highly resistant to water and moisture. Though it appears to be an expensive choice yet it is low on costs and is affordable and will give a perfect finish. The lifespan of a laminate finish is higher than any other material.</p>
<p class="Normal1">&nbsp;<b>Glossy Glass Finish</b></p>
<p class="Normal1">&nbsp;If you want to reach the zenith of style and sophistication then you can opt for glass finish that can make your modular kitchen look stunningly ultramodern. Strength, durability and safety factors are kept in mind while providing this finish to your kitchen. It is available in a spectrum of colors and provides high gloss finish to the kitchen. The maintenance is low.</p>
<p class="Normal1">&nbsp;<b>Matt Finish</b></p>
<p class="Normal1">&nbsp;High on demand, this smooth textured and low maintenance matt finish makes it to the top. The matt finish makes a subtle visual impact on the viewer's mind. Available in a gamut of colors right from neutral to vibrant ones, matt finish is something irresistible.</p>
<p class="Normal1">&nbsp;Adding accessories in your kitchen cabinets will help your workplace to be organized and easy to use, clean and will add extra space. On the other hand, while choosing Appliances, you should look for your budget. Hob, chimney, microwave or oven are the basic needs and these appliances come in various range, you can choose according to your budget. Don&rsquo;t go unnecessarily for high-end appliances if not required.</p>
<p class="Normal1">&nbsp;<b>&nbsp;Modular Kitchen Accessories</b></p>
<p class="Normal1">&nbsp;Modular Kitchens have brought an enormous change in the way we look at kitchens. Comes with stylish cabinets and ample storage facilities modular kitchens have provided great convenience and comfort to homemakers. Their efficiency has increased and cooking has become rather a joyful experience. With superior interior design styles, and state-of-the-craft cabinets, the trendy kitchen accessories required to turn the kitchen space advantageous are elaborated below:</p>
<p class="Normal1">&nbsp;<b>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Drawer Inserts</b></p>
<p class="Normal1">&nbsp;Maximum utilization of the space and thus increase the efficiency of the homemaker. With ingredients readily available within your reach in the drawer inserts, you don&rsquo;t have to complicate things. Things can be kept at one spot and you can organize your kitchen just like you want it to be. Moreover, you can customize your drawers using custom door fronts, unique hardware, etc.</p>
<p class="Normal1">&nbsp;<b>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Roll out Cabinets</b></p>
<p class="Normal1">&nbsp;Full-heighted cabinets, ingenious use of the given space. It can be used as a platform for storing all your cooking utensils, such as spatulas, crockery, broiler pans, lids etc.&nbsp; In order to give additional support to the cabinets, casters can be used.</p>
<p class="Normal1">&nbsp;<b>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Slotted Wood Block/Knife Cavities</b></p>
<p class="Normal1">&nbsp;Horizontal slotted wood block that can easily adjust into the drawer is a perfect way to store kitchen equipment. It is wise not to keep knives and other fine instruments loose in the drawers, which can hurt anyone who is using the kitchen. With knife cavities, you can well-versed and make a fine display of knives / forks and retain their sharp edges for years to come.</p>
<p class="Normal1">&nbsp;<b>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pegboards within Drawers</b></p>
<p class="Normal1">&nbsp;Pegboards within drawers work best as they allow you to use the drawers as per your needs. You can easily fix dividers based on the storage items and store your cooking utensils conveniently. They also work best for wine storage, especially when there&rsquo;s not enough space for it.&nbsp;</p>
<p class="Normal1">&nbsp;<b>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Drawer Dividers</b></p>
<p class="Normal1">&nbsp;Work as horizontal dividers in the front or back of the drawer offers a great solution for storing pots, lids, and casserole dishes.</p>
<p class="Normal1">&nbsp;<b>6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pull out Pantries</b></p>
<p class="Normal1">&nbsp;Commonly used in comparatively big spaced kitchens, which can help you declutter the space and make your kitchen organized. These do not have to be necessarily huge, but a regular-sized pantry can bring a big and meaningful difference to the space to resolve space dilemmas that you often face in the kitchen while cooking.</p>
<p class="Normal1">&nbsp;<b>7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Custom Pan</b></p>
<p class="Normal1">&nbsp;Custom pans bring dramatic change to your kitchen island countertop and provide an anchor to space.&nbsp; A custom pan improves the allure of the kitchen and the aroma of fresh, organic herbs and leaves you spellbound.</p>
<p class="Normal1">&nbsp;<b>8.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Open Shelving</b></p>
<p class="Normal1">&nbsp;Open Shelving looks amazing and helps you make a fine display of kitchen accessories. Each and every space can be used intelligently in order to store accessories. Open shelves bring the space alive and uplift the architecture of the space tremendously.</p>
<p class="Normal1">&nbsp;<b>9.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Glass Shelves</b></p>
<p class="Normal1">&nbsp;Eye-catching glass shelves in a well-appointed kitchen are even more appealing and convenient as it lets you easily make out what&rsquo;s stored in the front rows of jars. One of the finest kitchen accessories serves a dual purpose.</p>
<p class="Normal1">&nbsp;<b>10.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Built-in Dishwashers</b></p>
<p class="Normal1">&nbsp;Empowered with cutting-edge technology and greater performance. A little more expensive than you&rsquo;d expect, but are highly efficient and designed with energy saving features. The finest dishwashers are equipped with sharp stainless steel interiors, adjustable racks, and various spray units including multiple wash cycles. They also provide dry options and eco-friendly wash.</p>
<p class="Normal1">&nbsp;<b>11.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Corner Drawers</b></p>
<p class="Normal1">&nbsp;Corner drawers are often installed diagonally into the kitchen corners that offer a creative solution within the limited space. The fact that they are diagonally built, it makes them deeper from inside and hence allow you to store big kitchen essentials, such as silverware, stainless steel pots quite conveniently.</p>
<p class="Normal1">&nbsp;<b>12.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pull-out Trash Can</b></p>
<p class="Normal1">&nbsp;Other than cooking, kitchen space is utilized for various other purposes, such as cleaning utensils, chopping, grinding, and lot more due to which heaps of trash gets build-up. The very sight of trash spells negative energy in the space. However, the situation can be avoided with the help of pulling out trash cans that are used to hide unattractive bins and other objects.</p>
<p class="Normal1">&nbsp;<b>13.&nbsp;&nbsp; Appliance Garage</b></p>
<p class="Normal1">&nbsp;All of us wish for a clutter-free kitchen island, neatly organized which gives a sense of delight to the beholder. The appliance garages are used for the same purpose for keeping your toaster, blender and mixer at a meaningful distance to enable stress-free cooking to the users.</p>
<p class="Normal1">&nbsp;<b>14.&nbsp;&nbsp; Rolling Cart</b></p>
<p class="Normal1">&nbsp;You can use rolling carts for various purposes, such as for compact space, for chopping and grinding materials, as a bar cart when rolled into a room, etc.</p>
<p class="Normal1">&nbsp;<b>15.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cane Baskets</b></p>
<p class="Normal1">&nbsp;Used for storing fruits, vegetables &ndash; the cane baskets help maintain the flow of air to keep them fresh. Provides a rusty look to the kitchen.</p>
<p class="Normal1">&nbsp;Modular Kitchens come in a wide exquisite classic range of prices starting from Rs. 60,000 onwards. Get a good functional modular kitchen in an affordable price range of Rs. 150,000 to Rs. 300,000. The price of a kitchen depends on the area of the kitchen, material &amp; finish of the kitchen and the accessories selected by you. The cost of appliances is extra. Its majestic grandeur is worth every penny you spend on it. A smart kitchen is all you need to cook in style so what are you waiting for; you&rsquo;re just a click away to make your kitchen the kind you&rsquo;ve always dreamt of.</p>
</div>
</div>

</div>
</div>
<p>





   
   
   
            
<script type="text/javascript" src="http://cdn.jquerytools.org/1.2.6/full/jquery.tools.min.js"></script>
<script type="text/javascript">// <![CDATA[
jQuery( document ).ready(function() { 
 jQuery("#tabing-load-1").css('display','block');
jQuery("[id^='tabing-']").click(function() {
 var suffix = this.id.match(/\d+/);
 jQuery("[id^='tabing-']").removeClass("modactive");
 jQuery('#tabing-'+suffix).addClass("modactive");
 jQuery("[id^='tabing-load-']").css('display','none');
  jQuery('#tabing-load-'+suffix).css('display','block');
});
});
// ]]></script>
<script type="text/javascript">// <![CDATA[
// perform JavaScript after the document is scriptable.
jQuery(function() {
    // setup ul.tabs to work as tabs for each div directly under div.panes
    jQuery("ul.tabs").tabs("div.panes > div")
});

jQuery(function() {
    // setup ul.tabs to work as tabs for each div directly under div.panes
    jQuery("ul.tabs1").tabs("div.panes1 > div");
});

jQuery(function() {
    // setup ul.tabs to work as tabs for each div directly under div.panes
    jQuery("ul.tabs2").tabs("div.panes2 > div");
});

jQuery(function() {
    // setup ul.tabs to work as tabs for each div directly under div.panes
    jQuery("ul.tabs3").tabs("div.panes3 > div");
});

jQuery(function() {
    // setup ul.tabs to work as tabs for each div directly under div.panes
    jQuery("ul.tabs4").tabs("div.panes4 > div");
});

jQuery(function() {
    // setup ul.tabs to work as tabs for each div directly under div.panes
    jQuery("ul.tabs5").tabs("div.panes5 > div");
});


// ]]></script>
<script type="text/javascript" src="http://stage.www.yagotimber.com/skin/frontend/rwd/yagotimber/js/MicroSlider.js"></script>
<script type="text/javascript">// <![CDATA[
jQuery(function(){
	jQuery('#id-xm-rorate').Microslider();
});
// ]]></script>


<script type="text/javascript" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/js/valida.2.1.4.min.js"></script>
		<script type="text/javascript" >


			jQuery(document).ready(function() {

				// show Valida's version.
				jQuery('#version').valida( 'version' );

				// Exemple 1
				jQuery('.valida').valida();

				// Exemple 2
				/*
				jQuery('.valida').valida({

					// basic settings
					validate: 'novalidate',
					autocomplete: 'off',
					tag: 'p',

					// default messages
					messages: {
						submit: 'Wait ...',
						required: 'Este campo é obrigatório',
						invalid: 'Field with invalid data',
						textarea_help: 'Digitados <span class="at-counter">{0}</span> de {1}'
					},

					// filters & callbacks
					use_filter: true,
					before_validate: null,
					after_validate: null

				});
				*/

                // setup the partial validation
                jQuery('#partial-1').on('click', function( ev ) {
                    ev.preventDefault();
                    jQuery('#res-1').click(); // clear form error msgs
                    jQuery('form').valida('partial', '#field-1'); // validate only field-1
                    jQuery('form').valida('partial', '#field-1-3'); // validate only field-1-3
                });

			});

		</script>         
            

</p>
