<div class="interior">
<div class="container">
<div class="interior1"><a href="#1">3D DESIGN</a>  <a href="#3">KITCHEN</a> <a href="#4">WARDROBE</a> <a href="#5">HOME LOOK</a> <a href="#6">DESIGNERS</a> <a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>company-profile" >COMPANY PROFILE</a> <a href="#7">CONTACT US</a></div>
<div class="banner-home"><img alt="" src="<?php echo $this->getSkinUrl('images/home-banner.jpg'); ?>" /></div>
</div>
</div>
<div class="container"><a name="1"></a>
<div class="interior2">
<h5>3D DESIGN &amp; CONCEPT</h5>
<h2>2D &amp; 3D</h2>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="design01"><img alt="" src="<?php echo $this->getSkinUrl('images/inter01.png'); ?>" />
<h2>SCHEDULE MEETING</h2>
<p>Meet our designing experts and let us pamper you with our designs</p>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="design01"><img alt="" src="<?php echo $this->getSkinUrl('images/inter02.png'); ?>" />
<h2>MEASUREMENT</h2>
<p>We take the measurement and design as per your taste and preference</p>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="design01"><img alt="" src="<?php echo $this->getSkinUrl('images/inter03.png'); ?>" />
<h2>2D &amp; 3D FLOOR PLAN</h2>
<p>Get realistic 3D design which will help you to visualize the design better</p>
</div>
</div>
<div class="col-md-3 col-sm-3 col-xs-12">
<div class="design01"><img alt="" src="<?php echo $this->getSkinUrl('images/inter04.png'); ?>" />
<h2>QUOTATION</h2><a name="3"></a>
<p>Get quotation as per the design and quality preference</p>
</div>
</div>
<div class="col-md-12 col-sm-12 col-xs-12">
<div class="design_but"><a href="#7">CONTACT YAGO</a></div>
</div>
</div>
</div>

<div class="container">
	<div class="slider-items-products">
<div class="new_title center">
<h2>&nbsp;<br />FULL HOME DESIGN PACKAGE</h2>
<h3>Complete Furniture for your home</h3>
</div>
</div>


<div class="container clearfix">
<ul class="banner-images">

<a href="http://www.yagotimber.com/full-packages-two-bhk.html"><li class="grid right-space margin-banner ">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image1" class="b-lazy b-loaded" src="http://www.yagotimber.com/media/wysiwyg/home2bhk.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-three-bhk.html"><li class="grid right-space margin-banner ">
<figure class="effect " style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image2" class="b-lazy b-loaded" src="http://www.yagotimber.com/media/wysiwyg/home3bhk.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-four-bhk.html"><li class="grid margin-banner ">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image3" class="b-lazy b-loaded" src="http://www.yagotimber.com/media/wysiwyg/home4bhk.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-villa.html"><li class="grid two-width right-space">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image4" class="b-lazy b-loaded" src="http://www.yagotimber.com/media/wysiwyg/homevilla.jpg" /></div>  <figcaption>
</figcaption></figure>
</li></a>
<a href="http://www.yagotimber.com/full-packages-penthouse.html"><li class="grid  two-height space011">
<figure class="effect" style="visibility: visible;"><div class="wrapper"><img alt="Lazy load images image5" class="b-lazy b-loaded" src="http://www.yagotimber.com/media/wysiwyg/homepenthouse.jpg" /></div><figcaption>
</figcaption></figure>
</li></a>

</ul>
<div class="line01">&nbsp;</div>



</div>
</div>

<div class="container">
<div class="interior2">
<h5>MODULAR KITCHEN DESIGNS</h5>
<h2>BEAUTIFUL KITCHEN CUSTOMISED FOR YOU</h2>
<ul class="banner-images">
<li class="grid two-width right-space">
<div class="inter-slider">
<div id="slider-container" class="slider-container">
<div class="slider">
<div class="slide"><img alt="Category" src="<?php echo $this->getSkinUrl('images/moduler03.jpg'); ?>" /></div>
<div class="slide"><img alt="Category" src="<?php echo $this->getSkinUrl('images/moduler01.jpg'); ?>" /></div>
<div class="slide"><img alt="Category" src="<?php echo $this->getSkinUrl('images/moduler02.jpg'); ?>" /></div>
</div>
<div id="prev" class="switch"><img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/prev.png" /></div>
<div id="next" class="switch"><img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/next.png" /></div>
</div>
</div>
</li>
<li class="grid  two-height">
<div class="inter-brand">
<h4>Brand Name</h4>
<!--<div class="brand_box1">
<ul>
<li><a href="#">Urban Ladder</a></li>
<li><a href="#">Wooden Street</a></li>
<li><a href="#">Capri Cost</a></li>
<li><a href="#">Modular Kitchen</a></li>
<li><a href="#">Modular Kitchen</a></li>
<li><a href="#">Modular Kitchen</a></li>
</ul>
</div>--><a name="4"></a>
<div class="brand_logo"><a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo1.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo2.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo3.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo4.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo5.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo5-1.png'); ?>" /></a> <a href="http://www.yagotimber.com/modular-kitchen"><input class="explor1" type="button" value="book consultation" /></a></div>
</div>
</li>
</ul>
</div>
</div>
<div class="container">
<div class="interior2">
<div class="col-md-12">
<h5>WARDROBE DESIGNS</h5>
<h2>WARDROBE WITH INTELLIGENT STORAGE</h2>
</div>
<div class="inter-word">
<ul class="banner-images">
<li class="grid  two-height  right-space">
<div class="inter-brand1">
<h4>Brand Name</h4>
<!--<div class="brand_box1">
                <ul>
                <li><a href="#">Urban Ladder</a></li>
                <li><a href="#">Wooden Street</a></li>
                <li><a href="#">Capri Cost</a></li>
                <li><a href="#">Modular Kitchen</a></li>
                <li><a href="#">Modular Kitchen</a></li>
                <li><a href="#">Modular Kitchen</a></li>
                </ul>
                </div>-->
<div class="brand_logo"><a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/ward-logo.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/ward-logo1.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo3.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo4.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/b-logo5.png'); ?>" /></a> <a href="#"><img alt="offer banner3" src="<?php echo $this->getSkinUrl('images/ward-logo2.png'); ?>" /></a> <a href="http://www.yagotimber.com/wardrobe"><input class="explor1" type="button" value="book consultation" /></a></div>
</div>
</li>
<li class="grid two-width">
<div class="inter-slider">
<div id="slider-container1" class="slider-container1">
<div class="slider">
<div class="slide"><img alt="Category" src="<?php echo $this->getSkinUrl('images/wordrod1.jpg'); ?>" /></div>
<div class="slide"><img alt="Category" src="<?php echo $this->getSkinUrl('images/wordrod2.jpg'); ?>" /></div>
<div class="slide"><img alt="Category" src="<?php echo $this->getSkinUrl('images/wordrod3.jpg'); ?>" /></div>
</div><a name="5"></a>
<div id="prev" class="switch"><img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/prev.png" /></div>
<div id="next" class="switch"><img alt="" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/next.png" /></div>
</div>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="container">
    <div class="interior2">
        <h5>HOME LOOKS DESIGN</h5>
        <h2>EXQUISITE PRE-DESIGNED LOOKS</h2>
        <div class="inter-home">
        		<ul class="banner-images">
                    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>home-look"><li class="grid right-space two-height">
                    <figure class="effect wow fadeInLeft"><img alt="Category" src="<?php echo $this->getSkinUrl('images/product08.jpg'); ?>" /> <figcaption>
                    </figcaption></figure>
                    </li></a>
                    <a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>home-look"><li class="grid two-width">
                    <figure class="effect wow fadeInRight"><img alt="Category" src="<?php echo $this->getSkinUrl('images/product07.jpg'); ?>" /> <figcaption>
                    </figcaption></figure>
                    </li></a>
                    <a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>home-look"><li class="grid two-width right-space ">
                    <figure class="effect wow fadeInUp"><img alt="Category" src="<?php echo $this->getSkinUrl('images/living02.jpg'); ?>" /> <figcaption>
                    </figcaption></figure>
                    </li></a>
                    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>home-look"><li class="grid  two-height ">
                    <figure class="effect wow fadeInRight"><img alt="Category" src="<?php echo $this->getSkinUrl('images/product09.jpg'); ?>" /> <figcaption>
                    </figcaption></figure>
                    </li></a><a name="6"></a>
                    <!--<li class="grid margin-banner ">
                    <figure class="effect wow fadeInRight"><img alt="Category" src="<?php echo $this->getSkinUrl('images/blank.jpg'); ?>" /> <figcaption>
                    <div class="box2">FOXGLOBE &amp; STUDIO</div>
                    <div class="box3">INTERIORS &amp; DESIGNING</div>
                    <div class="banner-images_content">
                    <h2><a class="explor" href="#"><strong>EXPLORE</strong></a></h2>
                    </div>

                    </figcaption></figure>
                    </li>--></ul>
        
        </div>
    </div>
</div>
<div class="container">
<div class="interior2">
<div class="col-md-12">
<h5>DESIGNERS</h5>
<h2>OUR DESIGN EXPERTS</h2>
</div>
<div class="testi-inter">
<div class="row">
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="testi1">
<div class="testi1_img"><img alt="" src="<?php echo $this->getSkinUrl('images/desig003.jpg'); ?>" /></div>
<div class="testi1_text"><img alt="" src="<?php echo $this->getSkinUrl('images/designer1.png'); ?>" /><br />
<h2><span>Mahi Arora</span></h2>
<p>Experience- 4 years<br />Projects completed- 12<br />Expertise- Modular Kitchen</p>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="testi1">
<div class="testi1_img"><img alt="" src="<?php echo $this->getSkinUrl('images/desig002.jpg'); ?>" /></div>
<div class="testi1_text"><img alt="" src="<?php echo $this->getSkinUrl('images/designer2.png'); ?>" /><br />
<h2><span>Arjun Marwah</span></h2>
<p>Experience-5 years, <br />Projects Completed-24, <br />Expertise- Customized Furniture</p>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
<div class="testi1"><a name="7"></a>
<div class="testi1_img"><img alt="" src="<?php echo $this->getSkinUrl('images/desig001.jpg'); ?>" /></div>
<div class="testi1_text"><img alt="" src="<?php echo $this->getSkinUrl('images/designer3.png'); ?>" /><br />
<h2><span>Devank Sahni</span></h2>
<p>Experience-8 years, <br />Projects Completed- Above 100, <br />Expertise- Turn Key Designer</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="container">
<div class="interior2">
<h4>BOOK FREE CONSULTATION</h2>
<div class="inter-book">
<h3>The consultation fee is absolutely free and there are no hidden charges</h3>
<?php echo $this->getLayout()->createBlock('formbuilder/frontend_form')->setData('form_id','6')->setTemplate('formbuilder/form.phtml')->toHtml(); ?>

</div>
<div class="mata-dis">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Accordion_FDC')->toHtml();?>


<div class="why_home">
<div class="new_title center">
<h1>Home Interior Design Consultation Services</h1>
</div>
<div class="why_home1">

<p><span style="font-size: small;">Yagotimber.com is an online shopping destination where you can design, decorate and furnish your dream home in a very hassle free manner. We at Yagotimber believe that a home plays a very vital role in a person's life. It is a place where we cherish most beautiful moments of our life. So we strive to recreate and design your home in such a manner that it leaves a deep impact not only on your mind but your soul as well.</span></p>
<p><span style="font-size: small;"><b>Interior Design Consultation Services:</b></span></p>
<p><span style="font-size: small;">At Yagotimber we value each and every penny that a client spends. Hence we provide a free design consultation for all our clients irrespective of their location and size of work. You just simply need to book a design consultation on our website or call on our IVR number 8010-255-255 anytime. Our interior design consultant schedules a meeting with you and understands your requirement and suggests you with lots of ideas that best suits your requirement. We charge a very nominal fee only when the client is convinced with our design ideas and want take things further to measurement, 2D drawing, 3D visualization, and quotation. However, the amount which is charged for these four services is completely adjustable if we also do the execution of turnkey work for your project. The amount is non-refundable if you only want the measurement, 2D, 3D, and quotation for your place and nothing beyond that.</span></p>
<p ><span style="font-size: small;"><b>Full Home Interior Design Package/ Full Home Interior Designing Cost</b></span></p>
<p><span style="font-size: small;">Understanding the need and requirement of clients in the existing market scenario, we have formulated pre-designed full home packages for 2 BHK, 3BHK, 4 BHK, villa, and penthouse. You just simply need to click on any of these packages from our website according to your need and we will provide you with the approximate price that it might cost you for your home interior designing. To make things clear and transparent we have also provided the 3D images of the rooms that we will provide you in a particular package along with the furniture included in the package with prices for individual pieces.</span></p>
<p><span style="font-size: small;">However, you may switch, modify or customize any design as per your taste and requirement. Once you are convinced with our design package you just need to book a design consultation only or through call and leave the rest to us.</span></p>
<p><span style="font-size: small;"><b>Home Interior Design Ideas</b></span></p>
<p><span style="font-size: small;">Lately, we have found that a lot of clients surf the internet to get a lot of design ideas for their homes. However, the internet can only provide you with images and not prices. In our design ideas section, you can find a lot of interior design ideas in categories like living room interior design ideas, bedroom interior design ideas, dining room interior design ideas and kitchen interior design ideas. All these ideas come with a tentative price so that you can choose design as per your budget. You may choose any design that you like, book a design consultation, get it customized as per your taste and requirement, get a 3d visualization along with quotation, and finally get the look for your own place.</span></p>
<p><span style="font-size: small;"><b>Turn-Key Interior Designing Services</b></span></p>
<p><span style="font-size: small;">Yagotimber is a one stop solution to all you home designing needs. From selling furniture and home decor products online to complete home designing and execution, we do it all under one roof. You may simply buy a furniture or home decor product for your home directly from our online store. You may also book a design consultation and meet our interior designers for free. Furthermore, you can get you complete home designed and executed by our experts. We have collaborated with market leaders in categories like furniture manufacturing, home decor and furnishing product selling, painting, flooring, false ceiling, civil work etc. If we are executing your project we see to it that you need to consult no other person for any home designing and decorating needs.</span></p>
<p><span style="font-size: small;"><b>Major Services and Products</b></span></p>
<p><span style="font-size: small;">Yagotimber has a team of professionals in products and services like 2D drawing, 3D modeling and visualization, customized furniture for the home, design consultation, painting, flooring, false ceiling, wall paper, wooden flooring, wooden furniture, modern furniture, civil works, wiring, and others. We have an expert team of designers specialized in designing themes like the modern interior design, European design, ethnic design, contemporary designs and much more.</span></p>
<p><span style="font-size: small;">Next time when you are planning for a home makeover, just give a try to the home design services of Yagotimber, and we assure you, that we will leave no stone unturned to make your home a dream home. We provide our interior design consultation services throughout India, especially in Delhi NCR, Noida, Gurgaon, Ghaziabad and Faridabad.</span></p>
<p class="Normal1"><b>How it Works?</b></p>
<p class="Normal1">We at Yagotimber.com are providing you this golden opportunity to get the interiors of your beloved home designed by our professional experts who are creative, skilled and at the same time very dedicated towards service provided to you. We provide you the best design solutions and the steps involved in the process are extremely user-friendly. Here is the step by step procedure for your convenience, which can be followed to avail our hassle free service.</p>
<p class="Normal1"><b>See Designs in Design Ideas</b></p>
<p class="Normal1">On our online home design and decoration store, you will find a diverse range of latest design ideas. Everyone has their own idea but not all the ideas are feasible and neither every idea can be implemented upon every home. So here we give a huge list of modern design ideas for all types of homes. You can find an uncountable number of designs depending upon your home requirement and size.</p>
<p class="Normal1"><b>Shortlist Few</b></p>
<p class="Normal1">Upon seeing the designs what you have to do is, just make a list of your favorite designs that are available on our website. You can even add your own design idea for the consideration. Make sure to shortlist few extra designs which will be helpful for you if your favorite most design becomes infeasible for the shape and size of your home.</p>
<p class="Normal1"><b>Book a Consultation by Form or Phone</b></p>
<p class="Normal1">The next step will be to book a free consultation. You can book a consultation from us in two ways. First, you can complete the consultation form on our website Yagotimber.com by filling your details such as your name, contact number, email and postal address. Second, you can call us directly on our IVR number 8010-255-255 and book a consultation like you make an order from a restaurant. Both of the ways are extremely convenient.</p>
<p class="Normal1"><b>We Visit</b></p>
<p class="Normal1">After a successful consultation booking, a team from Yagotimber will visit your place to understand your requirements better and make a detailed report of what can be added, what should be added and what would be the best suitable design for your lovely home.</p>
<p class="Normal1"><b>We Suggest</b></p>
<p class="Normal1">Upon making the report, we will suggest the necessary changes and appropriate designs. Our team is such that it&rsquo;ll make sure none of your requirement goes unfulfilled. We will thoroughly go through your shortlisted designs and suggest you the design that best complements you and you sweet home.</p>
<p class="Normal1"><b>Measurement, 2D and 3D</b></p>
<p class="Normal1">When the design has been finalized verbally, there will be another inspection of your house for the measurement of its dimensions. A team will visit you to take an accurate measurement of your house and rooms. As the measurement is done 2D will be made for your home specifically. Then for a better understanding of designs 3D will be prepared with the proposed design of your home.</p>
<p class="Normal1"><b>Quotation</b></p>
<p class="Normal1">The design is finalized, sizes have been taken. So, now the price takes over the discussion. We quote an expenditure which will be required to e done by you to convert your house of bricks and cement into a home of love. The quotation that we provide is totally genuine and extremely fair. The price that we offer is evidently affordable and cheap. We make sure to offer our customers the best price for our best in class service. There is a decision to be taken between us on mutual terms to finalize the quotation. The ball is in your court now.</p>
<p class="Normal1"><b>Execution</b></p>
<p class="Normal1">When the budget is finalized, then the penultimate and as they say the most important step of the process arrives, the execution of the design idea. This step is the most vital and most demanding from our perspective. We start your work in our manufacturing plant. Initially, we manufacture the customized furniture and perform the other tasks which can and must be done on the site itself. Upon working on both fields we assemble every unit very gracefully. You just have to transfer the burden from your shoulder to ours and we make sure that the four walls which you gave us are returned to you in the form of a luxurious and a classy home.</p>
<p class="Normal1"><b>Completion</b></p>
<p class="Normal1">After accomplishing all these, we finally handover, your now so lovely property to you. Things can change in a matter of time but things can become better in just a matter of a decision. Decide to join hands with yagotimber.com and we make sure that your hard earned money is completely utilized and not a penny remain wasted keeping your sophisticated class quotient intact and strong.</p>
<p class="Normal1"><b>Why yago?</b></p>
<p class="Normal1">Well, this is a million dollar question and if understood properly can increase your status and class, at least a million times. This can only be understood after you experience the services and products of Yagotimber.com. But still, here we are providing few reasons for why yagotimber.com just because we have to.</p>
<p class="Normal1"><b>Online Presence</b></p>
<p class="Normal1">The online presence of Yagotimber.com is outstanding and that is very evident. We are easily reachable by one and all through the online channel. We are a growing organization and in spite of having such a tremendous online presence, we still are working very hard to make ourselves approachable to the few who are still remaining. We are a highly active organization on the World Wide Web.</p>
<p class="Normal1"><b>Wide Variety </b></p>
<p class="Normal1">It&rsquo;s the diverse range of variety of designs and furniture that we provide which makes us unique and keeps us ahead of our other counterparts. At Yagotimber.com you can find a never before range of products and services tailor-made for your requirement. With such huge variety, selection becomes little tough but the product that arrives is worth the hard work. I bet.</p>
<p class="Normal1"><b>Good Team</b></p>
<p class="Normal1">We have a great time which is dedicated towards your service. Each member of our team is an expert in their work. With a backup of great experience, our team is perhaps the best team of interior and furniture designers and each member of the team makes sure that you receive the best solution for your requirements.</p>
<p class="Normal1"><b>Professionalism</b></p>
<p class="Normal1">We have different teams for different tasks and that makes the process extremely hassle free. This simply depicts the professionalism and unidirectional approach of Yagotimber. The effort of each team member and each team at Yagotimber is an example of sheer professionalism.</p>
<p class="Normal1"><b>Transparency</b></p>
<p class="Normal1">You will find whole of our process to be extremely transparent with no hidden conditions and terms. We work on the policy of walking the talk. There&rsquo;s no hidden charge throughout our process.</p>
<p class="Normal1"><b>Technology Used as Tool</b></p>
<p class="Normal1">Technology is a boon to mankind, but it&rsquo;s a boon only when updated regularly. We, at yagotimber.com, make use of the best and the latest technology for manufacturing and other supplementary processes.</p>
<p class="Normal1"><b>All Under One Roof</b></p>
<p class="Normal1">We have all our stations and perform our entire operations under one roof. That leaves the minimum chance of misperception, miscommunication, and misunderstanding which ultimately leads to the best result.</p>
<p class="Normal1"><b>Interior Design Themes </b></p>
<p class="Normal1">We are the specialist in designing and provide our customer with designs of all forms.</p>
<p class="Normal1"><b>Modern</b></p>
<p class="Normal1">Our modern interior design themes look extremely neat and tidy with unadorned interiors and characterized by natural materials like leather, linen, wood and teak. These designs are super classy and superbly kept together.</p>
<p class="Normal1"><b>Contemporary</b></p>
<p class="Normal1">Contemporary interior designs are perhaps the simplest and yet so complex because there is no specific pattern to them. They take ideas from all the eras and change very rapidly. We provide our customers the updated and latest designs to cherish their time in the home.</p>
<p class="Normal1"><b>Ethnic</b></p>
<p class="Normal1">We have an extremely wide range of ethnic design ideas coming from various areas of the globe. And these designs are the epitome of sheer sophistication and raw class at the same time.</p>
<p class="Normal1"><b>European</b></p>
<p class="Normal1">What&rsquo;s better than European designs? Outrageous charm and royalty is what a European design brings along. At Yagotimber you get to find numerous European designs which are pre-designed as well as customizable.</p>
<p class="Normal1"><b>Others</b></p>
<p class="Normal1">There are uncountable other designs for you to go through and choose. Each design is nowhere less than the other ones. The luxury that these designs bring is unmatchable and unbeatable.</p>
<p class="Normal1"><b>Interior Designers</b></p>
<p class="Normal1">We have a team of over 50 professional designers who are highly experienced and motivated for the good work that Yagotimber is doing. Yagotimber.com is trying to improve the living standard of Indian population and elevate their status. We chose furniture as a medium to do that. At Yagotimber, every designer dreams of an India of class. And we are taking huge steps towards our goal of making our country a luxurious place to live in.</p>
<p class="Normal1">The designers at Yagotimber.com are super skilled and extremely talented. We recruited our designers on the basis of their excellence and experience in designing. Our designers have the ability to withstand all your requirements and generate the best result which is expected by you at the earliest time possible.</p>
<p class="Normal1">Once hired, designers at Yagotimber don&rsquo;t just do the job with their past knowledge and experience. But we provide a special training and workshops to our designers at regular interval to make them acquainted with the changing trends in the field of designing. We even have special sessions for our designers where they can understand the latest technological advancements to maintain the superiority of Yagotimber.com.</p>
<p class="Normal1">Yagotimber have recruited special purpose designers who are specialized in specific fields like modular kitchen designs, furniture designing, wall designer, wardrobe specialist, etc, who work exclusively in their own field to ensure best quality product and least complex processing?</p>
<p class="Normal1">Yagotimber provides its services all over India, especially in Mumbai, Delhi NCR region- Delhi, Gurgaon, Ghaziabad, Noida, and Faridabad. So, if you are and India, call us and if you are a Delhite, then don&rsquo;t forget to take our assistance in the process of designing, manufacturing, purchasing, measurement, design consultation and what not because we are the best. We don&rsquo;t say this, it&rsquo;s our customers who do.</p>
<p class="Normal1"><b>What Comes Under Interior Designing?</b></p>
<p class="Normal1"><b>Consultation</b></p>
<p class="Normal1">Consultation is very important as nobody can design the interiors of the home single handedly. So what&rsquo;s better than in getting a professional design consultant up for the job? There are you and for you there&rsquo;s Yagotimber. Join hands and let&rsquo;s make India beautiful.</p>
<p class="Normal1"><b>2D/3D Designs</b></p>
<p class="Normal1">If your floor is square, then your room is a cube and there&rsquo;s no better way to understand an interior design idea other than visualizing it on 2D and 3D because 2D or 3D alone will not give the best result.</p>
<p class="Normal1"><b>Furniture</b></p>
<p class="Normal1">Furniture is veins of a home. Life is not possible without furniture. Ranging from bed to table to chair, we are surrounded all around by furniture. Being surrounded by best furniture is a better idea. Where else can you find better furniture than yagotimber.com? We are an online furniture and designing showroom who deal in best in class furniture and most valuable designs ideas.</p>
<p class="Normal1"><b>Modular Kitchen</b></p>
<p class="Normal1">Food can be cooked with the help of just one stove, but in today&rsquo;s world we have money and we are willing to send. So, what&rsquo;s better than money being spent in taking care of the one who takes care of you, the housewives and housekeepers? So we have developed most comfortable and latest designed modular kitchen where the lady of the house can relax while cooking and in the end we get the best food.</p>
<p class="Normal1"><b>False Ceiling</b></p>
<p class="Normal1">Ceilings are made once at the time of building the house, but will the ceiling design trend remain same after few years? For this reason Yagotimber has brought false ceiling using which you get a chance to change the look of your ceiling without having to invest so much on new ceiling and renovation. Just purchase a false ceiling from Yagotimber and keep changing the top view of your room with changing trends.</p>
<p class="Normal1"><b>Flooring</b></p>
<p class="Normal1">The case of flooring is same as ceiling. Like you can&rsquo;t change ceiling if once built, similarly, floor can also not be changed before you break it or it starts breaking by its own. Temporary flooring or permanent, Yagotimber specializes in both. Extremely antique and unique floor designs at Yagotimber will make you want to break your floor.</p>
<p class="Normal1"><b>Wall Painting</b></p>
<p class="Normal1">With floor and ceiling the wall paints should also be of latest design and best quality. Because it&rsquo;s your home, we would like you to stay in class. Yagotimber also works to improve the interior decoration of the already decorated house. Wall paints add an aroma of the stupendous class of the lovely home and make life easier.</p>
<p class="Normal1"><b>Civil Work</b></p>
<p class="Normal1">Yagotimber even take the contract of building your home. Advantage of getting home build by yagotimber.com is that once they complete construction, they will be ones who will give your home a class and finishing touch and more importantly we will first consider the design ideas and after that only we will construct your building depending upon you design selection.</p>
<p class="Normal1"><b>Wallpaper</b></p>
<p class="Normal1">If few walls of the home have wallpapers on them, then that wallpaper increases the standard of the house manifold. Yagotimber is dedicated to beautifying your interiors by any means. Wallpapers that are available at Yagotimber are extremely trendy and classy.&nbsp;</p>
<p class="Normal1"><b>Lighting</b></p>
<p class="Normal1">Lighting has an important role to play in the home. For all the couples there, it&rsquo;s your opportunity to enjoy your love life a bit extra with lights from yagotimber.com. Company of your partner in a dim light is the best thing a person can ask for and we at Yago provide you this along with numerous other lightings at very reasonable rate.&nbsp;</p>
<p class="Normal1"><b>Home Furnishing</b></p>
<p class="Normal1">Home that is made but not furnished is not livable. There are some mountings that are necessary in a home like furniture, finishing and thousand other movable and non movable items. Yagotimber.com is an expert in home furnishing, be it in terms of designing or selling.</p>
<p class="Normal1"><b>Home Decor</b></p>
<p class="Normal1">Home decorative ranging from that of living room to bedroom to modular kitchen to garden to where not are available at yagotimber.com. These home decors are not just available but they are the best in class and latest in design. Yagotimber is an expert in home decor as our collection consists of home decors that are very rare and hard to find along with the common ones. These rare ranges include lamp, cane products, candles, glass decor, metal decor, clocks, garden accessories, god idols, etc.</p>
<p class="Normal1">We are best in whatever we do and we say that with proud. But still, we get up every day with short term goal of doing better than what we did yesterday. This approach is really helpful for us in keeping our focus intact and arrogance low.</p>


</div></div>


</div>
</div>
