<style>
.messages{display:none;}
</style>

<div class="container">
<div class="account-login">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra') ?>
    
    
    
   <div class="sell_heading">Sell on Yagotimber</div>
    <div class="row">
    	<div class="col-md-7 col-sm-7 col-xs-12">
        	<div class="sell_left"><a href="#section1"><img src="<?php echo $this->getSkinUrl('images/seller_now.png')?>" alt="" /></a></div>
        </div>
        <div class="col-md-5 col-sm-5 col-xs-12">
        	<div class="sell_right">
            	<form method="post" action="<?php echo Mage::getBaseUrl();?>marketplace/seller/create/">
                <input name="sell_mob" required="required"  pattern="[0-9]{10}" type="text" placeholder="Mobile No" class="sell_mob" />
                <input name="sell_email"  required="required" type="email" placeholder="Email" class="sell_email" />
                <input name="sell_com"  required="required" type="text" placeholder="Company Name" class="sell_com" />
                <input name="sell_city"  required="required" type="text" pattern="[A-Za-z]+" placeholder="City" class="sell_city" />
                <input name="sell_password"  required="required" type="password" placeholder="Enter Password" class="sell_password" />
                <div class="sell_terms"><input type="checkbox" /> Terms & Conditions</div>
               <input type="submit" value="Sign up" class="sell_submit" />
               </form>
                <div class="sell_allready">Already a seller <a href="#">login</a></div>
                
            </div>
        </div>
    </div>
    
    <div class="way_sell">
    	<h3>Why Sellers Love Yago!</h3>
    </div>
    
    <div class="row">
    	<div class="col-md-4 col-sm-4 col-xs-12">
        	<div class="sell_icon">
            	<img alt="" src="http://www.yagotimber.com/media/wysiwyg/sell_dashboard.png">
                <h2>User Friendly Dashboard</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
        	<div class="sell_icon">
            	<img alt="" src="http://www.yagotimber.com/media/wysiwyg/sell_management.png">
                <h2>Inventory Management</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
        	<div class="sell_icon">
            	<img alt="" src="http://www.yagotimber.com/media/wysiwyg/sell_permotion.png">
                <h2>Free Promotion</h2>
            </div>
        </div>
    </div>
    

<a name="section1"></a>
    
    <div class="sel_faq">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('elantra_accrod')->toHtml() ?> 

    </div>
    
    <div class="sell_expert">
    	<h2>FEEL FREE TO TALK TO US!</h2>
        
      <form method="post" action="<?php echo Mage::getBaseUrl(); ?>askanexpert/questions/ashu/">
        <textarea name="question_sg" class="sell_area" placeholder="Have Something in mind? Feel free to Discuss"></textarea>
        <input type="text" name="name_sg" placeholder="Mobile No" class="sell_exp01"/>
        <input type="text"  name="email_sg" placeholder="Email ID" class="sell_exp01"/>
        <a href="#"><input type="submit" value="Submit" class="sell_qes" /></a>
    </div>
    
    
    
    
    
    
    
    
    
    
    
    <script type="text/javascript">
                        //<![CDATA[
                        var dataForm = new VarienForm('login-form', true);
                        //]]>
    </script>
    
    
    
    
    
    
    
    
    
    
</div>
</div> 
