<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2.3
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */
?>
<div class="container">
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create Seller Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before') ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra') ?>
    <div class="my-account-wrapper"> <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <div class="personal_detail">
            
            <h2><?php echo $this->__('01 Personal Information') ?></h2>
            <ul class="form-list">
              <li class="fields">
                       
                       
                        <div class="field">
                            <label for="company_name" class="required"><em>*</em><?php echo $this->__('Name of Company*') ?></label>
                            <div class="input-box">
                                <input type="text" required="required" name="company_name" value="" title="<?php echo $this->__('Company Name') ?>" class="input-text " id="company_name" />
                            </div>
                        </div>
                        

           <div class="field">
                            <label for="company_type" class="required"><em>*</em><?php echo $this->__('Nature of organisation*') ?></label>
                            <div class="input-box">
                              <select name="company_type" class="required" style="width: 301px;">
<option  selected="">Please select</option>
<option value="Private Limited">Private Limited</option>
<option value="Proprietorship">Proprietorship</option>
<option value="Partnership">Partnership</option>
<option value="other">Other</option>
</select>   
               </div>
                        </div>
                        
                        
                        
                                <div class="field">
                            <label for="regadd" class="required"><em>*</em><?php echo $this->__('Address of Registered office*') ?></label>
                <div class="input-box">
                                <input type="text" required="required" name="regadd" title="<?php echo $this->__('Registered office') ?>" class="input-text " id="regadd" />
                            </div>
                        </div>
                         
                         
                          <div class="field">
                            <label for="shopadd" class="required"><em>*</em><?php echo $this->__('Address of Shop/Retail/Place of operation*') ?></label>
                <div class="input-box">
                                <input type="text"  required="required" name="shopadd" title="<?php echo $this->__('Address of Shop') ?>" class="input-text " id="shopadd" />
                            </div>
                        </div>
                        
                          <div class="field">
                            <label for="panno" class="required"><em>*</em><?php echo $this->__('Company/Individual PAN Number*') ?></label>
                <div class="input-box">
                                <input type="text"  required="required" name="panno" title="<?php echo $this->__('PAN Number') ?>" class="input-text " id="panno" />
                            </div>
                        </div>
                        
                        
                          <div class="field">
                            <label for="vatno" class="required"><em>*</em><?php echo $this->__('Company Service tax  or VAT number*') ?></label>
                <div class="input-box">
                                <input type="text"  required="required" name="vatno" title="<?php echo $this->__('VAT number') ?>" class="input-text " id="vatno" />
                            </div>
                        </div>
                        
                         <div class="field">
                            <label for="tinno" class="required"><em>*</em><?php echo $this->__('TIN Number *') ?></label>
                <div class="input-box">
                                <input type="text" required="required" name="tinno" title="<?php echo $this->__('TIN Number ') ?>" class="input-text " id="tinno" />
                            </div>
                        </div>
                        
                        
                         <div class="field">
                            <label for="cstno" class="required"><em>*</em><?php echo $this->__('CST Number*') ?></label>
                <div class="input-box">
                                <input type="text"  required="required" name="cstno" title="<?php echo $this->__('CST Number') ?>" class="input-text " id="cstno" />
                            </div>
                        </div>
                        
                         <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo $this->__('E-mail*') ?></label>
                <div class="input-box">
                                <input type="email" value="<?php if($_POST['sell_email']) { echo $_POST['sell_email']; }  ?>" name="email" title="<?php echo $this->__('E-mail') ?>" class="input-text " id="email" />
                            </div>
                        </div>
                        
                        
                         <div class="field">
                            <label for="director" class="required"><em>*</em><?php echo $this->__('Name of Directors/Partners/Owner *') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[A-Za-z]+" name="director" title="<?php echo $this->__('Name of Directors') ?>" class="input-text " id="director" />
                            </div>
                        </div>
                        
                 
                        
                        
                         <div class="field">
                            <label for="directoradd" class="required"><em>*</em><?php echo $this->__('Address of at least one director/owner *') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[A-Za-z]+" name="directoradd" title="<?php echo $this->__('Address of owner') ?>" class="input-text " id="directoradd" />
                            </div>
                        </div>
                        
                         <div class="field">
                            <label for="dinno" class="required"><em>*</em><?php echo $this->__('DIN number (in case of registered company)*') ?></label>
                <div class="input-box">
                                <input type="text" required="required" name="dinno" title="<?php echo $this->__('DIN number') ?>" class="input-text " id="dinno" />
                            </div>
                        </div>
                        
                        </div>
                     
                     <div class="opera_detail">   

<h2>02 Operational Details<em style="color:#FF0000">*</em></h2>
                 <div class="field">
                            <label for="contactp" class="required"><em>*</em><?php echo $this->__('Name of Contact Person*') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[A-Za-z]+" name="contactp" title="<?php echo $this->__('Name of Contact Person') ?>" class="input-text " id="contactp" />
                            </div>
                        </div>


                        <div class="field">
                            <label for="desig" class="required"><em>*</em><?php echo $this->__('Designation*') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[A-Za-z]+" name="desig" title="<?php echo $this->__('Designation') ?>" class="input-text " id="desig" />
                            </div>
                        </div>
                        
                          <div class="field">
                            <label for="landline" class="required"><em>*</em><?php echo $this->__('Landline Number*') ?></label>
                <div class="input-box">
                                <input type="text" pattern="[0-9]+" name="landline" title="<?php echo $this->__('Landline Number') ?>" class="input-text " id="landline" />
                            </div>
                        </div>
                        
                         <div class="field">
                            <label for="mobileno" class="required"><em>*</em><?php echo $this->__('Mobile Number*') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[0-9]{10}" name="mobileno" title="<?php echo $this->__('Mobile Number') ?>" class="input-text " id="mobileno" />
                            </div>
                        </div>
                        
                        
                    
                         <div class="field">
                            <label for="emailid" class="required"><em>*</em><?php echo $this->__('E-mail ID *') ?></label>
                <div class="input-box">
                                <input type="email"  name="emailid" title="<?php echo $this->__('E-mail ID') ?>" class="input-text " id="emailid" />
                            </div>
                        </div>
                        
                         <div class="field">
                            <label for="mobileno" class="required"><em>*</em><?php echo $this->__('Mobile Number *') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[0-9]{10}" name="mobileno" title="<?php echo $this->__('Mobile Number') ?>" class="input-text " id="mobileno" />
                            </div>
                        </div>
                        
                        </div>
                        
                        <div class="bank_main">
                        
                        <div class="bank01">

<h2>03 Bank Details<em style="color:#FF0000">*</em></h2>

                    <div class="field">
                            <label for="bankde" class="required"><em>*</em><?php echo $this->__('Bank Details  (Please send cancelled cheque)*') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[0-9]+" name="bankde" title="<?php echo $this->__('Bank Details') ?>" class="input-text " id="bankde" />
                            </div>
                        </div>
                       
                        <div class="field">
                            <label for="bankadd" class="required"><em>*</em><?php echo $this->__('Bank Address*') ?></label>
                <div class="input-box">
                                <input type="text" required="required" name="bankadd" title="<?php echo $this->__('Bank Address') ?>" class="input-text " id="bankadd" />
                            </div>
                        </div>
                        
                        
                         <div class="field">
                            <label for="accname" class="required"><em>*</em><?php echo $this->__('Account Name*') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[A-Za-z]+" name="accname" title="<?php echo $this->__('Account Name') ?>" class="input-text " id="accname" />
                            </div>
                        </div>
                        
                        
                         <div class="field">
                            <label for="accno" class="required"><em>*</em><?php echo $this->__('Account Number*') ?></label>
                <div class="input-box">
                                <input type="text" required="required"  pattern="[0-9]+" name="accno" title="<?php echo $this->__('Account Number') ?>" class="input-text " id="accno" />
                            </div>
                        </div>
                        
                         <div class="field">
                            <label for="acctyp" class="required"><em>*</em><?php echo $this->__('Type of Account*') ?></label>
                <div class="input-box">
                              <select name="acctyp" class="required" >
<option  selected="">Please Select</option>
<option value="Current">Current</option>
<option value="Saving">Saving</option>

</select>
                            </div>
                        </div>
 
                         <div class="field">
                            <label for="ifc" class="required"><em>*</em><?php echo $this->__('IFSC Code*') ?></label>
                <div class="input-box">
                                <input type="text" required="required" name="ifc" title="<?php echo $this->__('IFSC Code') ?>" class="input-text " id="ifc" />
                            </div>
                        </div>
                        
                           <div class="field">
                            <label for="micr" class="required"><em>*</em><?php echo $this->__('MICR Code*') ?></label>
                <div class="input-box">
                                <input type="text" required="required" name="micr" title="<?php echo $this->__('MICR Code') ?>" class="input-text " id="micr" />
                            </div>
                        </div>
                        
                        </div>
                       
                       <div class="bank02"> 
                 <h2>04 Export Details <span>(in case of an exporter)</span></h2>       
                           <div class="field">
                            <label for="exported" class="required"><em>*</em><?php echo $this->__('Have you exported earlier *') ?></label>
                <div class="input-box">
                                <label><input required="" name="exported" checked="checked" value="yes" type="radio">Yes</label>
        <label><input required="required" name="exported" value="no" type="radio">No</label>
                            </div>
                        </div>

             <div class="field">
                            <label for="exp_country" class="required"><em>*</em><?php echo $this->__('If yes, then which countries*') ?></label>
                <div class="input-box">
                              <select name="exp_country" style="width: 301px;">
<option value="-1" selected="">select..</option>
<option value="India">India</option>
<option value="England">England</option>
<option value="USA">USA</option>
<option value="UK">UK</option>
<option value="Japan">Japan</option>
<option value="Indonesia">Indonesia</option>
<option value="Italy">Italy</option>
<option value="Brazil">Brazil</option>
<option value="China">China</option>
<option value="New Zealand">New Zealand</option>
<option value="Nepal">Nepal</option>
<option value="UAE">UAE</option>
<option value="Norway">Norway</option>
<option value="Spain">Spain</option>
<option value="SriLanka">SriLanka</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Monaco">Monaco</option>
<option value="Thailand">Thailand</option>
<option value="Poland">Poland</option>
<option value="South Korea">South Korea</option>
<option value="France">France</option>
<option value="Singapore">Singapore</option>
<option value="Other">Other</option>
<option value="No">No</option>
</select>
                            </div>
                        </div>
                                 <div class="field">
                            <label for="iec" class="required"><em>*</em><?php echo $this->__('IEC Code ( For Exporters)*') ?></label>
                <div class="input-box">
                                  <input type="text" required="required" name="iec" title="<?php echo $this->__('IEC Code ( For Exporters)') ?>" class="input-text " id="iec" />
                            </div>
                        </div>

                      <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box email_name">
                        <input type="name" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                <?php endif ?>
            </ul>
        </div>
        <?php if ($this->getShowAddressFields()): ?>
            <div class="fieldset">
                <input type="hidden" name="create_address" value="1" />
                <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                     
                        <div class="field">
                            <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                            </div>
                        </div>
                    </li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                    
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="wide">
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                            </div>
                        </li>
                    <?php endfor; ?>
                    
                    <li class="fields">
                        <div class="field">
                            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                    </li>
                </ul>
                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />
            </div>
            
            </div>
            
            
        <?php endif; ?>
        <div class="bank03">
        <div class="fieldset">
            <h2><?php echo $this->__('05 Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="input-box">
            <input type="checkbox" id="privacy_policy" name="privacy_policy" value="1" title="<?php echo $this->__('I agree the Terms and Condition') ?>" class="checkbox required-entry">

            <label for="is_subscribed"><?php echo $this->__('I agree the Terms and Condition') ?> (<a href="<?php echo Mage::helper('cms/page')->getPageUrl(6) ?>" target="_blank"><?php echo $this->__('Terms and Condition'); ?></a>)</label>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form></div></div></div>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
<?php if ($this->getShowAddressFields()): ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
<?php endif; ?>
        //]]>
    </script>
</div>
</div>
</div>