<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.4
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */

        $id = Mage::getSingleton('customer/session')->getId();  ?>      
        <div class="page-title">
        <h3><?php echo $this->__('Sales Report'); ?>
        
         <?php
        $selectFilter = $data = $from = $to = '';
        $data = $this->getRequest()->getPost();
        if (isset($data['select_filter'])) {
            $selectFilter = $data['select_filter'];
        }
        switch ($selectFilter) {
            case "today":
                /**
                 *  today interval
                 */          
                $startDay = strtotime("-1 today midnight"); 
                $endDay = strtotime("-1 tomorrow midnight");
                $from = date("Y-m-d", $startDay);
                $to = date("Y-m-d", $endDay);
                $fromDisplay = date("Y-m-d", $startDay);
                $toDisplay = date("Y-m-d", $startDay);
                break;
            case "last week":
                /**
                 *  last week interval
                 */
                $to = date('d-m-Y');
                $toDay = date('l', strtotime($to));
                /**
                 *  if today is monday, take last monday
                 */
                if ($toDay == 'Monday') {
                    $startDay = strtotime("-1 monday midnight");
                    $endDay = strtotime("yesterday");
                } else {
                    $startDay = strtotime("-2 monday midnight");
                    $endDay = strtotime("-1 sunday midnight");
                }
                $from = date("Y-m-d", $startDay);
                $to = date("Y-m-d", $endDay);
                $to = date('Y-m-d', strtotime($to . ' + 1 day'));
                $fromDisplay = $from;
                $toDisplay = date("Y-m-d", $endDay);
                break;
            case "last month":
                /**
                 *  last month interval
                 */
                $from = date('Y-m-01', strtotime('last month'));
                $to = date('Y-m-t', strtotime('last month'));
                $to = date('Y-m-d', strtotime($to . ' + 1 day'));
                $fromDisplay = $from;
                $toDisplay = date('Y-m-t', strtotime('last month'));
                break;
            case "custom":
                /**
                 *  last custom interval
                 */
                $from = date('Y-m-d', strtotime($data['date_from']));
                $to = date('Y-m-d', strtotime($data['date_to'] . ' + 1 day'));
                $fromDisplay = $from;
                $toDisplay = date('Y-m-d', strtotime($data['date_to']));
                break;
            /**
             *  Convert local date to magento db date.
             */
        }

        if ($selectFilter == '') {
            $from = date('Y-m-01', strtotime('last month'));
            $to = date('Y-m-t', strtotime('last month'));
            $to = date('Y-m-d', strtotime($to . ' + 1 day'));
            $dbFrom = $from;
            $dbTo = date('Y-m-t', strtotime('last month'));
        } else {
            $dbFrom = Mage::getModel('core/date')->gmtDate(null, strtotime($from));
            $dbTo = Mage::getModel('core/date')->gmtDate(null, strtotime($to));
        }
        ?>
  
               <div class="mp_seller_sales_report_wr"><form class="mp_seller_sales_report" name="orders" method="post" action="">
                    <select name="select_filter" id="select_filter">
                        <option name="lastmonth" value="last month"  <?php if ($selectFilter == 'last month') { ?> selected="selected" <?php } ?>><?php echo $this->__('Last Month'); ?></option>
                        <option name="lastweek" value="last week"  <?php if ($selectFilter == 'last week') { ?> selected="selected" <?php } ?>><?php echo $this->__('Last Week'); ?></option>
                        <option name="custom" value="custom" <?php if ($selectFilter == 'custom') { ?> selected="selected" <?php } ?>><?php echo $this->__('Custom'); ?></option>
                        <option name="today" value="today" <?php if ($selectFilter == 'today') { ?> selected="selected" <?php } ?>><?php echo $this->__('Today'); ?></option>
                    </select>
                    <input type="text" name="date_from" class="txtbox" id="date_from" value="<?php
                    if ($selectFilter == '') {
                        echo date('m/d/Y', strtotime($dbFrom));
                    } else {
                        echo date('m/d/Y', strtotime($fromDisplay));
                    }
                    ?>" />
                    <input type="text" name="date_to" class="txtbox" id="date_to" value="<?php
                    if ($selectFilter == '') {
                        echo date('m/d/Y', strtotime($dbTo));
                    } else {
                        echo date('m/d/Y', strtotime($toDisplay));
                    }
                    ?>" />
                    <button type="submit" class="button"  title="<?php echo $this->__('Submit') ?>" name="filter_submit" id="multi_submit" ><span><span><?php echo $this->__('Submit') ?></span></span></button>
                </form></div> </h3>
                </div>
                <?php
                $id = Mage::getSingleton('customer/session')->getId();
                if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                    $groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
                    $marketplace_groupId = Mage::helper('marketplace')->getGroupId();
                    if ($groupId == $marketplace_groupId) {
                        $revenue = array();                      
                        $sellerProductCollection = $this->advancedSalesReportCollection($dbFrom, $dbTo, $id);
                        foreach ($sellerProductCollection as $_sellerProductCollection) {
                            $dateRevenue = Mage::getModel('core/date')->date(null, strtotime($_sellerProductCollection['created_at']));
                            $dateRevenue = date('F j, Y', strtotime($dateRevenue));
                            if (array_key_exists($dateRevenue, $revenue)) {
                                $revenue[$dateRevenue] = $revenue[$dateRevenue] + $_sellerProductCollection['seller_amount'];
                            } else {
                                $revenue[$dateRevenue] = $_sellerProductCollection['seller_amount'];
                            }
                        }
                        /**
                         *  Calculating all days between from and to dates
                         */
                        $salesAllDays = array();
                        $fromAllDays = strtotime($from);
                        $toAllDays = strtotime($to);
                        for ($currentSalesDay = $fromAllDays; $currentSalesDay < $toAllDays; $currentSalesDay += (60 * 60 * 24)) {
                            $currentDayString = date('F j, Y', $currentSalesDay);
                            $salesAllDays[$currentDayString] = 0;
                        }
                        $totalRevenue = array_sum($revenue);
                        /**
                         *  Assinging value to all days
                         */
                        foreach ($revenue as $key => $value) {
                            $salesAllDays[$key] = $value;
                        }
                        $revenueDayData = '';
                        foreach ($salesAllDays as $key => $value) {
                            $keyValue = date('M j, Y', strtotime($key));                            
                            $toolData= 'point { size: 6; shape-type: circle; fill-color: #2bc191}';
                            $revenueDayData.="data.addRow(['{$keyValue}', {$value}, '{$toolData}']);";
                        }
                    }
                }
                ?>
              <div class="content_wr"><div id="sales_chart_div" style="width: 780px; height: 300px; margin:15px auto;"></div>
                <script type="text/javascript" src="https://www.google.com/jsapi"></script>
                <script type="text/javascript">
                    google.load("visualization", "1", {packages: ["corechart"]});
                    google.setOnLoadCallback(drawChart);
                    function drawChart() {
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', '<?php echo $this->__("Date"); ?>');
                        data.addColumn('number', '<?php echo $this->__("Sales"); ?>');
                        data.addColumn({type: 'string', 'role': 'style'});
                		<?php echo $revenueDayData; ?>
                        var formatter = new google.visualization.NumberFormat({prefix: '$'});
                        formatter.format(data, 1);                     
                        var options = {                        		
                            width: 700, height: 250,
                            colors: ['#7d7d7d', '#7d7d7d'],
                            areaOpacity: 0.1,
                            vAxis: {title:'Sales',format: '<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getSymbol(); ?>###,###,###.00', textPosition: 'in', showTextEvery: 5, slantedText: false, titleTextStyle: {color: '#7d7d7d', fontSize: 12, italic: false, bold: true}, textStyle: {color: '#7d7d7d', fontSize: 10}},
                            hAxis: {title: '<?php if ($selectFilter == '') {  echo 'Last Month';  } else {   echo ucwords($selectFilter); }?>', titleTextStyle: {color: '#7d7d7d', fontSize: 12, italic: false, bold: true}, textPosition: 'out', showTextEvery: 1, slantedText: false, textStyle: {color: '#7d7d7d', fontSize: 10}},                                                      
                            chartArea: {left: 20, top: 30, width: "100%", height: "75%"},
                            tooltip: {isHtml: true},
                            legend: 'none',
                            pointSize: 10,
                            series: {
                                  0: { pointShape: 'circle' }                                  
                              }                            
                        };
                        var chart = new google.visualization.LineChart(document.getElementById('sales_chart_div'));
                        chart.draw(data, options);
                    }
                </script>
                <script type="text/javascript">
                    decorateTable('my-product-table');
                    // <![CDATA[
                    Calendar.setup({
                        inputField: 'date_from',
                        ifFormat: '%m/%e/%y',
                        button: 'special_from_date_trig',
                        align: 'Bl',
                        singleClick: true
                    });
        
                    Calendar.setup({
                        inputField: 'date_to',
                        ifFormat: '%m/%e/%y',
                        button: 'special_to_date_trig',
                        align: 'Bl',
                        singleClick: true
                    });
                    // ]]>
                    var select = $("select_filter").getValue();
                    console.log(select);
                    $('select_filter').onsubmit = function() {
                        if (select === 'custom') {
        
                            $('date_from').remove();
                            $('date_to').remove();
                        }
                        else
                        {
        
                            $('date_from').add();
                            $('date_to').add();
                        }
                    };
                </script>
          </div> 
