
<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct() ?>

<div class="price-block">
<?php echo $this->getPriceHtml($_product) ?>

<?php if ($_product->isAvailable()): ?>
    <p class="availability in-stock pull-right"><link itemprop="availability" href="http://schema.org/InStock"><span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock pull-right"><link itemprop="availability" href="http://schema.org/OutOfStock"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>


 <?php //echo $this->getPriceHtml($_product, false, '_clone') ?> 
 
</div><!--price-block-->