<?php
/**
 * Ship to multiple address template
 *
 * @see Mage_Checkout_Block_Multishipping_Addresses
 */
?>

<?php 
$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
<div class="main-container col1-layout wow bounceInUp animated">
  <div class="main container">
<?php } ?> <!-- For version 3,5 -->

        <div class="multiple_addresses multiple-checkout">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="table-responsive">
<form id="checkout_multishipping_form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
        <div class="page-title_multi">
            <h1><?php echo $this->__('Ship to Multiple Addresses') ?></h1>                                
        </div> <!--page-title_multi-->
        <div class="title-buttons">
       <button type="button" title="<?php echo $this->__('Enter a New Address') ?>" class="button new-address" onclick="$('add_new_address_flag').value=1; $('checkout_multishipping_form').submit();"><span><?php echo $this->__('Enter a New Address') ?></span></button>
    </div> <!--title-buttons-->
<div class="addresses">
    
    <fieldset class="">
        <input type="hidden" name="continue" value="0" id="can_continue_flag" />
        <input type="hidden" name="new_address" value="0" id="add_new_address_flag" />
        <?php echo $this->__('Please select shipping address for applicable items') ?>
        
        <table class="data-table" id="multiship-addresses-table">
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr>
                    <th><?php echo $this->__('Product') ?></th>
                    <th class="a-center"><?php echo $this->__('Qty') ?></th>
                    <th><?php echo $this->__('Send To') ?></th>
                    <th><?php echo $this->__('Remove') ?></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="100" class="a-right">                      
                      <button type="submit" title="<?php echo $this->__('Update Qty &amp; Addresses') ?>" class="button btn-update" onclick="$('can_continue_flag').value=0"><span><?php echo $this->__('Update Qty &amp; Addresses') ?></span></button>
                    </td>
                </tr>
            </tfoot>
            <tbody>
            <?php foreach ($this->getItems() as $_index => $_item): ?>
                <?php if ($_item->getQuoteItem()) :?>
                <tr>
                    <td><?php echo $this->getItemHtml($_item->getQuoteItem())?></td>
                    <td><input type="text" name="ship[<?php echo $_index ?>][<?php echo $_item->getQuoteItemId() ?>][qty]" value="<?php echo $this->htmlEscape($_item->getQty()) ?>" size="2" class="input-text qty" /></td>
                    <td><?php if ($_item->getProduct()->getIsVirtual()): echo $this->__('Shipping selection is not applicable.'); else: echo $this->getAddressesHtmlSelect($_item, $_index); endif; ?></td>
                    <td class="a-center"><a class="btn-remove btn-remove2" href="<?php echo $this->getItemDeleteUrl($_item) ?>" title="<?php echo $this->__('Remove Item') ?>" ></a></td>                    
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
         </fieldset> <!--multiple-checkout-->
    </div>    <!--addresses-->
       
</div> <!--table-responsive-->
        <script type="text/javascript">decorateTable('multiship-addresses-table')</script>
        <div class="buttons-set">         
            <a class="back-link" href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Shopping Cart') ?></a>   
            <button type="submit" title="<?php echo $this->__('Continue to Shipping Information') ?>" class="button btn-continue<?php if ($this->isContinueDisabled()):?> disabled<?php endif; ?>" onclick="$('can_continue_flag').value=1"<?php if ($this->isContinueDisabled()):?> disabled="disabled"<?php endif; ?>><span><?php echo $this->__('Continue to Shipping Information') ?></span></button>      
        </div>
 </form>
</div> <!--multiple_addresses-->

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
    </div>
  </div>
<?php } ?> <!-- For version 3,5 -->