<?php 
$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
<div class="main-container col1-layout wow bounceInUp animated">
  <div class="main container">
<?php } ?> <!-- For version 3,5 -->

<div class="multiple_addresses">
<div class="page-title">
   <h1><?php echo $this->__('Order Success') ?></h1>
</div>
<fieldset class="multiple-checkout">
    <h3 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h3>
    <p><?php echo $this->__('We are processing your order and you will soon receive an email with details of the order. Once the order has shipped you will receive another email with a link to track its progress.') ?></p>
    <?php if($_orderIds = $this->getOrderIds()): ?>
    <p>
        <?php $flag = false ?>
        <?php echo $this->__('Your order number is ') ?>
        <?php foreach ($_orderIds as $orderId=>$incrementId): ?>
            <?php if ($flag): ?>
                <?php echo ', ' ?>
            <?php endif; ?>
            <?php $flag = true ?>
            <a href="<?php echo $this->getViewOrderUrl($orderId) ?>"><?php echo $incrementId ?></a>
        <?php endforeach; ?>
    </p>
    <?php endif; ?>
    <?php echo $this->getChildHtml() ?>
    <div class="buttons-set">
        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?></span></button>
    </div>
</fieldset>  <!--multiple-checkout-->
</div> <!--multiple_addresses-->

<?php if(($get_current_layout=='custom_static_page_three') || ($get_current_layout=='custom_static_page_five')) { ?> <!-- For version 3,5 -->
    </div>
  </div>
<?php } ?> <!-- For version 3,5 -->