<?php if (Mage::getStoreConfig('elantrasettings/elantrasettings_products/upsell_product')): ?>
<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); 

?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_five')) { ?>
  <div class="upsell-pro wow bounceInUp animated">
    <div class="container">
     <div class="slider-items-products">
      <div class="new_title center">
        <h2><?php echo $this->__('People Also Bought ') ?></h2>
      </div> <!--new_title center-->
      <div id="upsell-products-slider" class="product-flexslider hidden-buttons">
          <div class="slider-items slider-width-col4 products-grid">
          <?php foreach($this->getItems() as $_link): ?> 
    <div class="item">
      <div class="item-inner">
            <div class="item-img">
              <div class="item-img-info">
                <a class="product-image" href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><img alt="<?php echo $this->htmlEscape($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image') ?>"></a>
                <?php echo $this->helper('elantrasettings')->getLabel($_link);  ?>
                <div class="actions">
                  <?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1) { ?> 
                    <div class="quick-view-btn"><a rel="nofollow" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_link->getId(); ?>" data-fancybox-type="iframe" class="magik-btn-quickview quick-view" data-original-title="<?php echo $this->__('Quickview') ?>" data-placement="right" data-toggle="tooltip" ><span><?php echo $this->__('Quick View') ?></span></a>
                     </div>
                  <?php }  ?>
                  <div class="link-wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>" data-original-title="<?php echo $this->__('Wishlist');?>" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Wishlist');?></span></a></div>
                  
                  <?php if($_link->isSaleable()): ?>
                    <div class="add_cart"><button type="button"  data-original-title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Cart') ?></span></button></div>        
                  <?php else: ?>
                    <p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?> 
                </div><!--actions-->
                <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!--Exclude from v5-->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_link->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!--Exclude from v5-->
              </div>
            </div>
            <div class="item-info">
              <div class="info-inner">
                <div class="item-title">
                   <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
                      <?php $prod_name = $this->htmlEscape($_link->getName()) ; 
                      if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
                 </a>
                </div>
                <?php if(($get_current_layout=='custom_static_page_five')) { ?> <!--for v5-->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_link->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!--for v5-->
                <div class="item-content">
                  <div class="price-box"><?php echo $this->getPriceHtml($_link, true) ?></div>
                </div>
              </div>
            </div>
          </div>
    </div><!--item-->       
       <?php endforeach ?>
     </div>
   </div>
 </div>
</div>
  </div>
<?php } ?>
<?php if(($get_current_layout=='custom_static_page_three')) { ?>

<div class="upsell-pro wow bounceInUp animated">
    <div class="container">
     <div class="slider-items-products">
      <div class="new_title center">
        <h2><?php echo $this->__('Upsell Products') ?></h2>
      </div> <!--new_title center-->
      <div id="upsell-products-slider" class="product-flexslider hidden-buttons">
          <div class="slider-items slider-width-col4 products-grid">
          <?php foreach($this->getItems() as $_link): ?> 
		  <div class="item">
	    <div class="item-inner">
		    <div class="item-img">
			<div class="item-img-info">
			      <a class="product-image" href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
				<img alt="<?php echo $this->htmlEscape($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image') ?>">
			      </a>

				<div class="item-box-hover">
					<div class="box-inner">
					      <?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1) { ?> 
						  <div class="product-detail-bnt"><a rel="nofollow" type="button" class="magik-btn-quickview button detail-bnt" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_link->getId(); ?>" data-fancybox-type="iframe" id="magik-btn-quickview_<?php echo $_link->getId()?>" data-original-title="<?php echo $this->__('Quickview') ?>" ><span><?php echo $this->__('Quick View') ?></span></a>
						  </div>
					      <?php }  ?>

					      <div class="actions">
						  <span class="add-to-links">
						      <a title="<?php echo $this->__('Add to Wishlist');?>" class="link-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>">
							<span><?php echo $this->__('Add to Wishlist');?></span></a> 
						      
						  </span> 
					      </div>
						  <?php if($_link->isSaleable()): ?>
						      <div class="add_cart">
							<button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
						      </div>
						  <?php else: ?>
							<p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
						  <?php endif; ?> 
  
					      
					</div>
                                </div>
                         </div>
		    </div>
		    <div class="item-info">
			      <div class="info-inner">
                                  <div class="item-title"><a title="<?php echo $this->htmlEscape($_link->getName()) ?>" href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a> </div>
                                  <div class="item-content">
				  <?php
					$summaryData = Mage::getModel('review/review_summary')
						->setStoreId($storeId)
						->load($_link->getId());
					if($summaryData->getRatingSummary()){ ?>
					    <div class="rating">
					    <div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
						</div> <!--rating-box-->
					    </div> <!--ratings-->
					    </div>
				  <?php } else { ?>  
					      <div class="rating"><div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div></div>
				  <?php } ?>

					
					<div class="item-price">
					  <div class="price-box"><?php echo $this->getPriceHtml($_link, true) ?></div>
					</div>
                                  </div>
                              </div>
		  </div>
          </div>
        </div><!--item-->
       <?php endforeach ?>
     </div>
   </div>
 </div>
</div>
  </div>


<?php } ?>

<?php if(($get_current_layout=='custom_static_page_four')) { ?>
<div class="upsell-pro wow bounceInUp animated">
    <div class="container">
      <div class="slider-items-products">
      <div class="new_title center">
	  <h2><?php echo $this->__('Upsell Products') ?></h2>
      </div> <!--new_title center-->
      <div id="upsell-products-slider" class="product-flexslider hidden-buttons">
	  <div class="slider-items slider-width-col4 products-grid">
		 <!-- Item -->
      <?php foreach($this->getItems() as $_link): ?> 
	    <div class="item">
	    <div class="item-inner">
		    <div class="item-img">
			<div class="item-img-info"> 
				<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"> 
				  <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image') ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>"> 
				</a>
				<div class="new-label new-top-left"><span>new</span></div>
				<?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1) { ?> 
						 <a rel="nofollow" type="button" class="magik-btn-quickview quickview-btn" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_link->getId(); ?>" data-fancybox-type="iframe"  data-original-title="<?php echo $this->__('Quickview') ?>" id="magik-btn-quickview_<?php echo $_link->getId()?>" ><span><?php echo $this->__('Quick View') ?></span></a>
						 
					      <?php }  ?>
			</div><!-- item-img-info -->
		    </div>
		    <div class="item-info">
			<div class="info-inner">
			    <div class="item-title"> <a href="#" title="<?php echo $this->htmlEscape($_link->getName()) ?>"> 
			    <?php echo $this->htmlEscape($_link->getName()) ?> </a> </div>
			    <div class="item-content">

				<?php
					$summaryData = Mage::getModel('review/review_summary')
						->setStoreId($storeId)
						->load($_link->getId());
					if($summaryData->getRatingSummary()){ ?>
					    <div class="rating">
					    <div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
						</div> <!--rating-box-->
					    </div> <!--ratings-->
					    </div>
				  <?php } else { ?>  
					      <div class="rating"><div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div></div>
				  <?php } ?>

				<div class="item-price">
					  <div class="price-box"><?php echo $this->getPriceHtml($_link, true) ?></div>
				</div>

				<div class="actions">
				    <a title="<?php echo $this->__('Add to Wishlist');?>" class="link-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>">
				    </a> 
				  <?php if($_link->isSaleable()): ?>
						      <div class="add_cart">
							<button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
						      </div>
						  <?php else: ?>
							<p data-original-title="<?php echo $this->__('Out of stock') ?>" data-placement="right" data-toggle="tooltip" class="availability out-of-stock"><span class="ava-out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
						  <?php endif; ?>
			
				 
				  
				</div>
			    </div>
			</div>
		    </div>


		   
	    </div>
	    </div><!--item-->

	    <?php endforeach ?>
	  </div><!--slider-items -->
      </div>
      </div><!-- slider-items-products-->
    </div>
</div>

<?php } ?>
<?php endif; ?>  <!-- end related product -->
<?php endif; ?>