<?php 
/* Top shopping Cart  */ 

$config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }

$get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>
<!-- for version 1,2 -->
<?php if(($get_current_layout=='custom_static_page_one') || ($get_current_layout=='custom_static_page_two') || ($get_current_layout=='custom_static_page_five')) { ?> 
<div class="cart-acc">
<div class="myaccount account1"><a href="http://www.yagotimber.com/home-look"><img alt="Home design" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/home-look.png"> DESIGN IDEAS</a>
<a class="fadeandscale_open account2" href="#popup1" data-popup-ordinal="0" id="open_12064212">
<img alt="Home Look Photo" src="http://www.yagotimber.com/skin/frontend/rwd/yagotimber/images/home-look2.png">CUSTOMISE</a>
</div>
<div class="top-cart-contain pull-right">
  <div class="mini-cart">
  <div class="basket"> 
  <?php if( $get_current_layout=='custom_static_page_five' ) {?>
      <a href="<?php echo $this->getUrl('checkout/cart') ?>"> 
	    <span class="cart_count">
		<?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount(); } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo "1"; }  else {echo "0"; } ?>
	    </span> 
	    <span class="price"><?php echo $this->__('My Cart');?> / <?php echo Mage::helper('core')->currency($this->getSubtotal(), true, false);?></span>
    </a>   

  <?php }else{?>  

	<a href="<?php echo $this->getUrl('checkout/cart') ?>"> 
	    <span class="cart_count">
		<?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount(); } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo "1"; }  else {echo "0"; } ?>
	    </span> <?php echo $this->__('My Cart');?> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
      </a>
  <?php } ?>
  </div> <!-- basket -->
  <div>
      <div class="top-cart-content">
         <?php $_items = $this->getRecentItems() ?>
         <?php if(count($_items)): ?>   

         <div class="actions">
              <button type="button" class="view-cart" onclick="window.location='<?php echo $this->getUrl('checkout/cart') ?>';" title="<?php echo $this->__('View Cart') ?>" ><span><?php echo $this->__('View Cart') ?></span></button>                 
        <?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1){?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>onestepcheckout/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
        <?php }else{ ?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>checkout/onepage/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
        <?php }?>
            </div>  <!--actions-->

            
            <ul id="cart-sidebar" class="mini-products-list">
               <?php foreach($_items as $_item): ?>
                   <?php echo $this->getItemHtml($_item) ?>
               <?php endforeach; ?>               
            </ul>                              
            
            
           <?php else: ?>               
                <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping cart.') ?></p>               
            <?php endif ?>
      </div> <!--top-cart-content-->
  </div>
  </div> <!--mini-cart-->
</div>
</div> <!--top-cart-contain pull-right-->
<?php } ?> <!-- End for version 1,2 -->

<!-- for version 3 -->
<?php if(($get_current_layout=='custom_static_page_three')) { ?> 

  <div class="mini-cart">
    <div class="basket"> 
      <a href="<?php echo $this->getUrl('checkout/cart') ?>">
        <span> <?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount(); } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo '1'; }  else { echo '0'; } ?> </span>
      </a>
    </div>
  
        <div style="display: none;" class="top-cart-content">
      
         <?php $_items = $this->getRecentItems() ?>
         <?php if(count($_items)): ?> 
          <div class="block-subtitle">
            <div class="top-subtotal">
              <?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount() . ' items,' ; } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo '1 item,'; }  else { echo '0 item,'; } ?> 
              <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?> 
            </div>
          </div>
          <ul id="cart-sidebar" class="mini-products-list">
               <?php foreach($_items as $_item): ?>
                   <?php echo $this->getItemHtml($_item) ?>
               <?php endforeach; ?>               
            </ul>  
            
            <div class="actions">
                              
<?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1){?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>onestepcheckout/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
        <?php }else{ ?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>checkout/onepage/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
        <?php }?>

            </div>  <!--actions-->
           <?php else: ?>               
                <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping cart.') ?></p>               
            <?php endif ?>
          
        </div>
      
    </div>
  
<?php } ?> <!-- End for version3 -->

<!-- for version 4 -->
<?php if(($get_current_layout=='custom_static_page_four')) { ?> 
<div class="top-cart-contain pull-right">
<div class="mini-cart">
  <div class="basket"> 
      <a href="<?php echo $this->getUrl('checkout/cart') ?>"><span class="cart-title"><?php echo $this->__('My Cart') ?></span><span class="cart-total"><?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount(); } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo '1'; }  else { echo '0'; } ?> </span></a>
  </div>
      <div>
      <div class="top-cart-content">
         <?php $_items = $this->getRecentItems() ?>
         <?php if(count($_items)): ?>   
           <div class="block-subtitle">

            <div class="top-subtotal">
                 <?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount() . ' items,'; } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo '1 item,'; }  else { echo '0 item,'; } ?>                
                 <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>            
            </div> <!--top-subtotal-->
          </div> 
            <ul id="cart-sidebar" class="mini-products-list">
               <?php foreach($_items as $_item): ?>
                   <?php echo $this->getItemHtml($_item) ?>
               <?php endforeach; ?>               
            </ul>                                          
            <div class="actions">                              
<?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1){?>
                    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>onestepcheckout/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
              <?php }else{ ?>
                    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>checkout/onepage/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
              <?php }?>       
        <a class="view-cart" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View Cart') ?>"><span><?php echo $this->__('View Cart') ?></span></a>
            </div>  <!--actions-->
           <?php else: ?>               
                <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping cart.') ?></p>               
            <?php endif ?>
      </div> <!--top-cart-content-->
  </div>
  </div> <!--mini-cart-->
</div><!--top-cart-contain pull-right-->
<?php } ?> <!-- End for version 4 -->
