
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>

<?php $config2 = Mage::getStoreConfig('web/default/cms_home_page'); 
       $delimeterPosition = strrpos($config2, '|');
       if ($delimeterPosition) {
          $config2 = substr($config2, 0, $delimeterPosition);
       }
?>
<?php $get_current_layout = Mage::getModel('cms/page')->load($config2, 'identifier')->getRootTemplate(); ?>

<?php if($this->getItemCount()): ?>
<div class="related-pro wow bounceInUp animated">
  <div class="container">
<div class="slider-items-products">
  
   <div class="new_title center">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
   </div> <!--new_title center-->

 <div class="category-products1">
   <div id="related-products-slider" class="product-flexslider hidden-buttons">
    <div class="slider-items slider-width-col4 products-grid">
    <?php foreach ($this->getItems() as $_item): ?>

    <?php if(($get_current_layout=='custom_static_page_three')) { ?> <!-- Exclude from version 3 -->

    <div class="item">
  <div class="item-inner">
    <div class="item-img">
      <div class="item-img-info">
        <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img alt="<?php echo $this->htmlEscape($_item->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image') ?>"></a> 
        <div class="item-box-hover">
          <div class="box-inner">
            <?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1){?> 
              <div class="product-detail-bnt">
                <a rel="nofollow" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_item->getId(); ?>" data-fancybox-type="iframe" class="magik-btn-quickview button detail-bnt" id="magik-btn-quickview_<?php echo $_item->getId()?>"><span><?php echo $this->__('Quick View') ?></span></a>
              </div>
            <?php }  ?> 
            <div class="actions">
              <span class="add-to-links">
                 <a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"><span><?php echo $this->__('Add to Wishlist') ?></span></a>
                 <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                   <a href="<?php echo $_compareUrl ?>" class="link-compare add_to_compare" title="<?php echo $this->__('Add to Compare');?>"><span><?php echo $this->__('Add to Compare') ?></span></a>
                 <?php endif; ?>
              </span>
            </div><!--actions-->
            <div class="add_cart">
              <?php if($_item->isSaleable()): ?>
                <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
              <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
              <?php endif; ?> 
            </div><!--add_cart-->
          </div><!--box-inner-->
        </div><!--item-box-hover-->
      </div><!--item-img-info-->
    </div><!--item-img-->
    <div class="item-info">
      <div class="info-inner">
        <div class="item-title">
            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>">
                  <?php $prod_name = $this->htmlEscape($_item->getName()) ; 
                  if(strlen($prod_name) > 17) {echo substr($prod_name,0,17)."...";}else {echo $prod_name;}?>
             </a>
         </div> <!--item-title-->
         <div class="item-content">
           <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_item->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
            <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
            <?php } ?>
            <div class="item-price"><?php echo $this->getPriceHtml($_item, true) ?></div>
         </div><!--item-content-->
      </div><!--info-inner-->
    </div><!--item-info-->
  </div><!--item-inner-->
</div> <!--item-->

    <?php } else { ?>  <!-- for version 1,2,4,5 -->

        <div class="item">

 <div class="item-inner">
            <div class="item-img">
              <div class="item-img-info">
                <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img alt="<?php echo $this->htmlEscape($_item->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image') ?>"></a>
                <?php echo $this->helper('elantrasettings')->getLabel($_item);  ?>
                <div class="actions">
                  <?php  if(Mage::app()->getStore()->getConfig('elantrasettings/elantrasettings_quickview/enable')==1) { ?> 
                    <div class="quick-view-btn"><a rel="nofollow" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_item->getId(); ?>" data-fancybox-type="iframe" class="magik-btn-quickview quick-view" data-original-title="<?php echo $this->__('Quickview') ?>" data-placement="right" data-toggle="tooltip" ><span><?php echo $this->__('Quick View') ?></span></a>
                     </div>
                  <?php }  ?>
                  <div class="link-wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" data-original-title="<?php echo $this->__('Wishlist');?>" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Wishlist');?></span></a></div>
                  <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                    <div class="link-compare"><a href="<?php echo $_compareUrl ?>" data-original-title="<?php echo $this->__('Compare');?>" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Compare');?></span></a></div>
                  <?php endif; ?>
                  <?php if($_item->isSaleable()): ?>
                    <div class="add_cart"><button type="button"  data-original-title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')" data-placement="right" data-toggle="tooltip"><span><?php echo $this->__('Add to Cart') ?></span></button></div>        
                  <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?> 
                </div><!--actions-->
                <?php if(($get_current_layout!='custom_static_page_five')) { ?> <!-- Exclude from v5 -->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_item->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!-- Exclude from v5 -->
              </div>
            </div>
            <div class="item-info">
              <div class="info-inner">
                <div class="item-title">
                   <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>">
                      <?php $prod_name = $this->htmlEscape($_item->getName()) ; 
                      if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
                 </a>
                </div>
                <?php if(($get_current_layout=='custom_static_page_five')) { ?> <!-- for v5 -->
                <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_item->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
                <?php } ?> <!-- for v5 -->
                <div class="item-content">
                  <div class="price-box"><?php echo $this->getPriceHtml($_item, true) ?></div>
                </div>
              </div>
            </div>
          </div>
 
</div> <!--item-->

  <?php } ?> <!-- for version 1,2,4,5 -->

    <?php endforeach; ?>  
  </div>
    </div> 
</div><!--category-products-->
</div>
</div>
</div>  <!--crosssell-->
<script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
<?php endif; ?>

