<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>

    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>

     
    <?php if (count($_categories) > 0): ?>
      <div class="top-categories wow bounceInUp animated">
        <div class="row">
         <div class="slider-items-products container">
          <div id="top-category" class="product-flexslider hidden-buttons">
            <div class="slider-items slider-width-col4">
              <?php foreach($_categories as $_category): ?>            
                 <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>   
                    <?php $_subcategories = $_category->getChildrenCategories() ?>
                      <?php foreach($_subcategories as $_subcategory): ?>
                        <?php $_subcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>                                                                            
                          <?php if($_subcategory->getElantraCustomImage()) { ?>
                            <div class="item">
                             <div class="pro-img">
                              <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                               <img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$_subcategory->getElantraCustomImage()  ?>" alt="<?php echo $_subcategory->getName() ?>" />
                               <div class="pro-info"><?php echo $_subcategory->getName() ?></div>
                              </a>
                             </div><!--pro-img-->  
                            </div><!--item-->
                           <?php } ?> 
                  <?php endforeach; ?>
                <?php endforeach; ?>
              </div><!-- slider-items slider-width-col4 products-grid--> 
            </div><!--best-seller-slider-->
          </div><!--slider-items-products container-->
        </div><!--row-->   
      </div><!--top-categories wow bounceInUp animated-->
     <?php endif; ?>