<?php 
/**
 * StarGenius_ProductLikeCount extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       StarGenius
 * @package        StarGenius_ProductLikeCount
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * ProductsLike list template
 *
 * @category    StarGenius
 * @package     StarGenius_ProductLikeCount
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_productslikes = $this->getProductslikes(); ?>
<div class="page-title productslike-title">
    <h1><?php echo Mage::helper('stargenius_productlikecount')->__('ProductsLikes') ?></h1>
</div>
<?php if ($_productslikes->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="productslike-list-container">
    <?php foreach ($_productslikes as $_productslike) : ?>
        <div class="productslike-list-item">
            <a href="<?php echo $_productslike->getProductslikeUrl()?>">
                <?php echo $_productslike->getProductSku();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('stargenius_productlikecount')->__('There are no productslikes at this moment');?>
<?php endif;?>
