<?php
/**
 * StarGenius_ProductLikeCount extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       StarGenius
 * @package        StarGenius_ProductLikeCount
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * ProductsLike view template
 *
 * @category    StarGenius
 * @package     StarGenius_ProductLikeCount
 * @author      Ultimate Module Creator
 */
?>
<?php $_productslike = $this->getCurrentProductslike();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title productslike-title">
    <h1><?php echo $_productslike->getProductSku(); ?></h1>
</div>
<div class="productslike-view">
    <div class="productslike-product_id">
        <?php echo Mage::helper('stargenius_productlikecount')->__('Product ID');?>:<?php echo $_productslike->getProductId();?>

    </div>
    <div class="productslike-product_sku">
        <?php echo Mage::helper('stargenius_productlikecount')->__('Product SKU');?>:<?php echo $_productslike->getProductSku();?>

    </div>
    <div class="productslike-product_liked">
        <?php echo Mage::helper('stargenius_productlikecount')->__('Product Liked');?>:<?php echo $_productslike->getProductLiked();?>

    </div>
    <div class="productslike-u_ipaddress">
        <?php echo Mage::helper('stargenius_productlikecount')->__('IP Address');?>:<?php echo $_productslike->getUIpaddress();?>

    </div>

</div>
